### ISSUE TITLE
Timing Attacks on cron.key

### ISSUE THREAD

**Issue by sean-nicholas** [firebase/functions-samples#100]
https://github.com/firebase/functions-samples/blob/master/delete-unused-accounts-cron/functions/index.js#L36 compares two keys with !==

I think this might be vulnerable to timing attacks. What about using https://www.npmjs.com/package/secure-compare instead?

Same thing here: https://github.com/firebase/functions-samples/blob/master/github-to-slack/functions/index.js#L38

**Comment by jamesdaniels** [comment]
Nice catch, want to take a stab at a pull request?

**Comment by sean-nicholas** [comment]
Okay :)
