### ISSUE TITLE
Thumbnails example - ECONNRESET

### ISSUE THREAD

**Issue by mrp14** [firebase/functions-samples#107]
Hello,

I developed something really close to Thumbnails example provided here, and sometimes (often) I'm getting this error when uploading or deleting files from Storage : 

```
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)
```

I found #78, but I checked that a promise is returned everytime.
Here is some code snippet, for the deletion part : 

**index.js**
```
exports.exampleFunction = functions.storage.object().onChange(event => {
    return f_thumbnails.exampleFunction(event);
});
```

**example_function.js**
```js
module.exports = exports = function (_admin, _config) {
    admin = _admin;
    config = _config;

    return {
        "exampleFunction": function (event) {
            return exampleFunction(event);
        }
    };
};

const exampleFunction = function (event) {
    const gcsSourceFilePath = event.data.name;
    const gcsSourceFilePathSplit = gcsSourceFilePath.split('/');
    const gcsBaseFolder = gcsSourceFilePathSplit.length > 0 ? gcsSourceFilePathSplit[0] : '';
    const gcsSourceFileName = gcsSourceFilePathSplit.pop();
    const gceSourceFileDir = gcsSourceFilePathSplit.join('/') + (gcsSourceFilePathSplit.length > 0 ? '/' : '');

    // Not an image
    if (!event.data.contentType.startsWith('image/')) {
        console.log('Not an image !');
        return;
    }

    // Thumbnail
    if (gcsSourceFileName.startsWith(config.IMAGES_THUMBNAIL_PREFIX)) {
        console.log('Thumbnail !');
        return;
    }

    const bucket = gcs.bucket(event.data.bucket);
    const gcsThumbnailFilePath = gceSourceFileDir + config.IMAGES_THUMBNAIL_PREFIX + gcsSourceFileName;


    // File deletion
    if (event.data.resourceState === 'not_exists') {
        console.log('Thumbnail deletion : ' + gcsThumbnailFilePath);
        return bucket.file(gcsThumbnailFilePath).delete().then(() => {
            console.log('Deleted thumbnail ' + gcsThumbnailFilePath);
        });
    }
    ...
```

I also created this [StackOverflow post](http://stackoverflow.com/questions/43224994/firebase-storage-cloud-functions-econnreset).

Thanks.

**Comment by nicolasgarnier** [comment]
Let's handle that on StackOverflow :)

**Comment by martemorfosis** [comment]
@nicolasgarnier This was happening to me too. Filed bug report [0-1088000016633] ECONNRESET Error happens randomly and halts function execution.

**Comment by chris-me** [comment]
Yes, I really think this is an open issue as I can confirm the problem. My function sometimes runs completely and sometimes throws this error.
Mine also is close to / derived from the provided image convert example.

**Comment by mcdonamp** [comment]
@martemorfosis and @chris-me 

The issue appears to be related to bucket and object ACLs not being set up properly. Here's a bash script (using the `gsutil` tool, available [here](https://cloud.google.com/sdk/docs/)):

```
#! /bin/bash
PROJECT = "<your-project-id>"
BUCKET = "<your-bucket-name>"

# Set bucket ACLs
# This will enable storage functions to deploy again
gsutil -m acl ch -p owners-$PROJECT:O gs://$BUCKET
gsutil -m acl ch -p editors-$PROJECT:O gs://$BUCKET
gsutil -m acl ch -p viewers-$PROJECT:R gs://$BUCKET

# Set default object/bucket ACLs
# This makes it so any new objects added have the proper ACLs
gsutil defacl ch -p owners-$PROJECT:O gs://$BUCKET
gsutil defacl ch -p editors-$PROJECT:O gs://$BUCKET
gsutil defacl ch -p viewers-$PROJECT:R gs://$BUCKET

# Recursively set object ACLs
# This will fix all existing objects if any are broken
gsutil -m acl -r ch -p owners-$PROJECT:O gs://$BUCKET
gsutil -m acl -r ch -p editors-$PROJECT:O gs://$BUCKET
gsutil -m acl -r ch -p viewers-$PROJECT:R gs://$BUCKET
```

**Comment by chris-me** [comment]
@mcdonamp I never used gsutil, just want to use Firebase functions as described in this repo :-) For the understanding: can you tell me if this is some bug at Firebase Beta (that will be fixed somewhen in the future), or where does this error occurs from? At the moment the functions are not useable for me as sometimes it works, and sometimes it just throws this error:

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)

**Comment by katowulf** [comment]
How your bucket ended up in a bad state is unclear at this point. Mike is investigating.

The solution is to follow Mike's instructions and run gsutil commands he's provided.

**Comment by inlined** [comment]
I think the ECONNRESET issue is an issue in the `google-cloud-node` module and have filed https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2254 to escalate.

**Comment by mrp14** [comment]
IMO, it seems to be related to Google Storage servers. When it comes up, every call ends up as ECONNRESET for several minutes.  For example, yesterday 4 calls between 8:16PM and 8:23PM (UTC+2) crashed, while 5 successive calls this morning finished with no errors.

Another point, to join @inlined remark and issue, is that it only happens when using google-cloud-node. I never had any problem uploading files to Storage client-side, using iOS or Android Firebase SDK, even while all server calls (Firebase functions with google-cloud-node) do ECONNRESET.

**Comment by chris-me** [comment]
@mcdonamp yes of course, thank you for looking into this.

I can also confirm never have any problems handling files client side (JS / Web SDK)

**Comment by mrp14** [comment]
Someone on OS linked this  : https://issuetracker.google.com/issues/36667671
Visibly we just have to wait for a new release or use [this patch](https://github.com/hayanmind/google-cloud-node/commit/19d7e9f1eb472eacbe31e3b3428a14d24790342b) 

If someone can confirm this is working (can't try this out today)

**Comment by Belindachenhj** [comment]
I did all the things above, but still get this error somotimes, why it's not stable?

**Comment by katowulf** [comment]
If you did all the things above, then surely you [read about the bug in the public issue](https://b.corp.google.com/issues/36667671), and also [noted the patch](https://github.com/hayanmind/google-cloud-node/commit/19d7e9f1eb472eacbe31e3b3428a14d24790342b)?

Closing this issue to prevent further "me too" discussions. Follow the public bug and file separate issues as needed.
