### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by gyss** [firebase/functions-samples#110]
Hi,
could you give examples of how to unit test properly these functions?

**Comment by CodingDoug** [comment]
Have you seen this?  https://firebase.google.com/docs/functions/unit-testing

**Comment by gyss** [comment]
Yes, I'm going through that document. But I thought that maybe was a good idea to have the unit tests on these functions to culminate them.

**Comment by gyss** [comment]
Do you accept PR for this issue?

**Comment by martosoler** [comment]
Were you able to do something with this? I was looking for a way of doing this and using ES6 at the same time.

**Comment by soumak77** [comment]
You can try out this library which I maintain: https://github.com/soumak77/firebase-mock

**Comment by nicolasgarnier** [comment]
A new package for functions testing was released. Please take a look at https://firebase.google.com/docs/functions/unit-testing
