### ISSUE TITLE
Stripe iOS

### ISSUE THREAD

**Issue by jitaek** [firebase/functions-samples#117]
Hello,

I'm trying to understand how functions can replace my current backend (ruby app on Heroku) that is set up and working for iOS payments.

From what I've done so far, it was simple to create customers and charge them by writing to the RTDB. 
However, I'm not sure how to retrieve the customer's sources and populate the customer's existing cards into the `STPPaymentMethodsViewController`.

For example, if the customer previously used two cards, `STPPaymentMethodsViewController` would show two sources and the customer would be able to choose one.

Would I have to set up a custom checkout process that:

1. Reads in the user's tokens from `/stripe_customers/{userId}/sources/{pushId}/token`
2. Show them in a user-readable format in my app
3. Based on the user's selected card, tell Stripe to update the customer's default source,
4. And finally charge the customer by writing to the RTDB

I feel like I'm not thinking through this properly and that there must be a better way, any help would be greatly appreciated, thanks!

**Comment by rldaulton** [comment]
@jitaek -

In stripe, each source has a unique id attached to it. So each of your user's payment sources have a unique identifier, something like `card_1A8GS095u396X3`, that you can safely store. 

Therefore, when you go do display a list of sources to the customer for them to choose, an consequently select a `default`, you can use the source id's that you've stored to [retrieve the sources](https://stripe.com/docs/api#source_object) and safely display them to your user for choosing. 

Hope this helps

**Comment by jitaek** [comment]
Thanks for the follow up - I'll keep this in mind!

**Comment by rldaulton** [comment]
@jitaek if this helped you solve your problem, could you close this issue please?

**Comment by jpsanabria** [comment]
@jitaek do you have any front end Swift code that you would be willing to share. I've just setup the Cloud Functions and trying to figure out the basics of STPPaymentContext

**Comment by jitaek** [comment]
In my `retrieveCustomer` method in the STPBackendAPIAdapter subclass, I have something like this. It's still a work in progress but this is working so far for me.
`let userStripeRef = FIREBASE_REF.child("stripe_customers").child(userID)
        userStripeRef.observeSingleEvent(of: .value, with: { snapshot in
            
            // get the user's stripeID
            guard let stripeDict = snapshot.value as? [String:AnyObject], let customerID = stripeDict["customerID"] as? String else { return }
   
            // get the user's list of sources
            if let sourcesDict = stripeDict["sources"] as? [String:[String:AnyObject]] {
                
                // attach each existing source to the customer
                for (_, source) in sourcesDict {

                    if let id = source["id"] as? String, let brand = source["brand"] as? String, let last4 = source["last4"] as? String, let expMonth = source["exp_month"] as? UInt, let expYear = source["exp_year"] as? UInt, let funding = source["funding"] as? String {
                        print("ADDING SOURCE")
                        let card = STPCard(id: id, brand: .visa, last4: last4, expMonth: expMonth, expYear: expYear, funding: .credit)
                        self.sources.append(card)
                        
                    }

                }
            }
            
            let customer = STPCustomer(stripeID: customerID, defaultSource: self.sources.first, sources: self.sources)
            completion(customer, nil)
            print(self.sources.count)
            return
            
        })`
