### ISSUE TITLE
Functions deployed successfully but still not working

### ISSUE THREAD

**Issue by abdulrehman3725** [firebase/functions-samples#121]
First of all the steps you have mentioned for this project is limited. I searched and then managed to deploy but after deploying functions I got error as below: 
"searchentry: undefined
 indexentry: undefined"

The log of functions in Firebase:

AlgoliaSearchNetworkError: getaddrinfo ENOTFOUND rb72z01uwb-2.algolianet.com rb72z01uwb-2.algolianet.com:443
    at ClientRequest.error (/user_code/node_modules/algoliasearch/src/server/builds/node.js:227:14)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Another Error is:
Function killed. Error: quota exceeded

I am currently using Blaze Plan.

**Comment by prescottprue** [comment]
Looks like it might be that your Algolia instance is not being found (meaning incorrect config). Are you sure you entered the environment info correctly?

**Comment by abdulrehman3725** [comment]
firebase functions:config:set algolia.app_id="myAlgoliaAppId" algolia.api_key="myAlgoliaApiKey"

I am using this command 
Here I enter my application id from the algolia in place of app_id and Admin Api key in place of api_key
i have tried without quotes and with quotes but errors are same

I have tried different code that ran easily. My config for that code was the same as this.

I enter the following command before configuring environment

```
-> cd functions
-> firebase functions:config:set algolia.app_id="myAlgoliaAppId" algolia.api_key="myAlgoliaApiKey" 
-> cd ..
-> firebase deploy --only functions
-> successfully deployed
```

I have searched these steps on Google but I guess there may be some mistake in my steps!

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team.
