### ISSUE TITLE
Support for webp format in imagemagick

### ISSUE THREAD

**Issue by nicktunac** [firebase/functions-samples#128]
Error occurred when converting .jpg to .webp in imagemagic

Here's my code.

`
return spawn('convert', [tempLocalFile, "/tmp/output.webp"]).then(() => {
                console.log('Thumbnail created at output.webp');
                // Uploading the Thumbnail.
                return bucket.upload("/tmp/output.webp", {
                    destination: thumbFilePath
                }).then(() => {
                    console.log('Thumbnail uploaded to Storage at', thumbFilePath);
                });
            });
`

Error produced in firebase functions log

`
ChildProcessError: `convert /tmp/output.jpg /tmp/output.webp` failed with code 1
    at ChildProcess.<anonymous> (/user_code/node_modules/child-process-promise/lib/index.js:132:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
`

**Comment by ovaris** [comment]
Hi, I also can confirm that webp converting fails, I sent bug report here https://firebase.google.com/support/contact/bugs-features/

**Comment by darthsitthiander** [comment]
The error is still persisting. Using Angular 5.

**Comment by fjeansilva** [comment]
Someone has found some solution to this error?

**Comment by jhuleatt** [comment]
Internal tracking bug: `111066093`

The workaround for this is to follow the [Sharp sample](https://github.com/firebase/functions-samples/tree/master/image-sharp), since Sharp [does support .webp](http://sharp.dimens.io/en/stable/api-output/#webp).
