### ISSUE TITLE
SSL Exception for Functions end-points on Android 

### ISSUE THREAD

**Issue by joelfernandes19** [firebase/functions-samples#134]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

https://us-central1-android-clean-architectu-38a86.cloudfunctions.net/

**Failing Function code used (including require/import commands at the top)**
https://us-central1-android-clean-architectu-38a86.cloudfunctions.net/helloWorld

**Steps to set up and reproduce**
Make a `GET` request to the above endpoint on Android API 23 and below. It will result in a SSL exception: `javax.net.ssl.SSLHandshakeException: Connection closed by peer`

**Sample data pasted or attached as JSON (not an image)**
Open your terminal, and try to connect the host with OpenSSL with the following command:

`openssl s_client -connect us-central1-android-clean-architectu-38a86.cloudfunctions.net:443`

### Debug output

**Screenshots**

<img width="872" alt="screen shot 2017-05-01 at 11 28 44 pm" src="https://cloud.githubusercontent.com/assets/4933738/25588460/f6b335ac-2ec5-11e7-97a9-37d7c035988d.png">

### Expected behavior

Should connect to the host 

### Actual behavior

SSL handshake is failing.  On Android API 19, 22, 23, it throws the exception, however, it works on Android API 25.

**Comment by puf** [comment]
Cross-posted from http://stackoverflow.com/questions/43720248/cloud-functions-for-firebase-with-http-triggers-throws-ssl-exception

**Comment by mbwalas** [comment]
As endpoint is over SNI you need to specify -servername, try running:
`openssl s_client -servername us-central1-android-clean-architectu-38a86.cloudfunctions.net -connect us-central1-android-clean-architectu-38a86.cloudfunctions.net:443`

then with 

 `openssl s_client -servername us-central1-android-clean-architectu-38a86.cloudfunctions.net -connect us-central1-android-clean-architectu-38a86.cloudfunctions.net:443 -no_tls1_2`

you can see that it also negotiated TLS 1.1.

Not an android expert so can't comment why this doesn't work on Android.

**Comment by johnozbay** [comment]
I'm getting a very similar {"message":"Remote host closed connection during handshake"} from Fastspring's webhooks when they hit my HTTPS triggered Cloud Functions. Still trying to figure out the cause ~ but my first guess is the TLS version.

**Comment by mbleigh** [comment]
You might want to check to make sure your http library supports SNI.

**Comment by johnozbay** [comment]
@mbleigh Forgive my confusion. Do you mean the HTTP library running Fastspring's Webhooks? ( It's a hosted e-commerce system which I have no control over ) Is there any way I can know if this is them / firebase for sure? If so I can push them to give me a better explanation.

**Comment by mbleigh** [comment]
Hmm, sorry, I think I misread your question, so my advice doesn't apply.
