### ISSUE TITLE
Environment Config (Integers)

### ISSUE THREAD

**Issue by sketchthat** [firebase/functions-samples#141]
Following these instructions you cannot set an integer as an environment value.
https://firebase.google.com/docs/functions/config-env

```
$ firebase functions:config:set someservice.key=1234 --project my-project-abc123
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled

Error: HTTP Error: 400, Invalid value at 'variable.text' (TYPE_STRING), 1234
```

Also tried to wrap in single (`'`) and double (`"`) quotes, same result.

Firebase should be able to save integers (or convert them to strings) for use within environment configs.

**Comment by Bengejd** [comment]
Maybe try it again, because I set it just fine yesterday using these exact same commands, using double quotes, but I didn't include the "--project my-project-abc123" addition that you have.

**Comment by sketchthat** [comment]
Same problem when I drop the `--project` flag.

Works once I make the variable a string (by including a character in the variable).

If you don't have any characters it doesn't appear to work.

```
$ firebase functions:config:set someservice.key=1234
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled

Error: HTTP Error: 400, Invalid value at 'variable.text' (TYPE_STRING), 1234
$ firebase functions:config:set someservice.key="1234"
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled

Error: HTTP Error: 400, Invalid value at 'variable.text' (TYPE_STRING), 1234

Having trouble? Try firebase functions:config:set --help

$ firebase functions:config:set someservice.key="1234a"
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions
```

**Comment by sketchthat** [comment]
Closing this issue, I opened it in the wrong repo and it's already been reported in the `firebase-tools` repo;

https://github.com/firebase/firebase-tools/issues/327
