### ISSUE TITLE
Typscript sample and tutorial

### ISSUE THREAD

**Issue by odick** [firebase/functions-samples#148]
Hi all,
Where can we get a typescript example?
Including any tutorial to setup the typescript environment
Currently, I'm new to typescript

Thank you

**Comment by ultrasaurus** [comment]
added https://github.com/firebase/functions-samples/tree/master/typescript-getting-started

**Comment by ultrasaurus** [comment]
If you have questions or run into any problems with it, please open an issue with the details.
