### ISSUE TITLE
Request new Sample

### ISSUE THREAD

**Issue by vsmori** [firebase/functions-samples#150]
Hello Guys,

i would like to know if you have a good recommendation how to handle OnWrite logic.

Taking this example as reference:

https://github.com/firebase/functions-samples/blob/acaec08802bf85d5b74ce03fed045ac69916b9e6/fulltext-search/functions/index.js

if ALGOLIA (external provider) has a outage, the databases will be out of sync.

How to find the records that have not been synced, and sync then again?

Regards,
Vitor

**Comment by maticzav** [comment]
You could create a `synced` value inside every instance, which is set to __true__ if Algolia responds with success and __false__ if it doesn't. 

Hope it helps!

**Comment by nicolasgarnier** [comment]
+1 to what @maticzav suggested. To have something really reliable you could save a `synced` flag when the Algolia call is successful and have a cron job which, for instance, every 24h would check if there are some unsynced values and try to sync them again. Maybe even send an email to your production engineer if one or both fail.
