### ISSUE TITLE
Readme files are misleading with respect to Firebase plans.

### ISSUE THREAD

**Issue by vr001** [firebase/functions-samples#154]
I see in most of the projects Readme.md, (eg. Full-text search via Algolia, moderate-images) there is something like "Enable Billing on your Firebase project by switching to the Blaze or Candle plans".

Is there a plan called Candle exists in firebase? At least, I don't see [here](https://firebase.google.com/pricing/). 

Also, why do we need to enable billing for testing cloud functions? Especially when you are talking between Google Cloud components?

**Comment by nicolasgarnier** [comment]
The Candle plan is the older name of the fixed cost plan (now Flame). Thanks for pointing this out. We'll update these READMEs.

The reason you need to enabled billing for these two samples is:
 - Full-text search via Algolia: In this sample you'll need to do requests to a non-Google service (Algolia) and this currently requires to have billing enabled for abuse reasons.
 - moderate-images: This sample uses the Cloud Vision API which requires to have billing enabled.

**Comment by vr001** [comment]
Thank you very much. I appreciate the acknowledgement Nicolas.

**Comment by nicolasgarnier** [comment]
Fixed in the READMEs
