### ISSUE TITLE
more straightforwarded authorized endpoints

### ISSUE THREAD

**Issue by p3sn** [firebase/functions-samples#156]
Hi, 

Based on your example of authorized https endpoint I created a function with a slightly different approach. It uses less modules and maybe it's a bit more straightforward. 

Please let me know your thoughts about it:
https://github.com/p3sn/Firebase/blob/master/verify_token/index.js

Regards, Peter

**Comment by leblancmeneses** [comment]
Also authorized-https-endpoint  doesn't work.

log prints:
Check if request is authorized with Firebase ID token
Signed-in user: undefined

I expected 401 given I didn't pass a bearer token.

**Comment by borismus** [comment]
Bumping this. The sample [here](https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/functions/index.js) is broken.

cc @nicolasgarnier @cdock1029

**Comment by nicolasgarnier** [comment]
@borismus, Just fixed it. Well it was build before we had local emulation. So even the local version was trying to request the deployed URL. (so it would only work after you've deployed). Fixed it so that the locally served version requests the local URL.

**Comment by nicolasgarnier** [comment]
@leblancmeneses > Things work for me. For instance with curl:

```bash
nivco-macbookpro2:sd nivco> curl -v http://localhost:5000/hello
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /hello HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.50.2
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< x-powered-by: Express
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: 0
< vary: Origin, Accept-Encoding, Authorization, Cookie
< content-type: text/html; charset=utf-8
< content-length: 12
< etag: W/"c-dAuDFQrdjS3hezqxDTNgW7AOlYk"
< date: Fri, 12 Jan 2018 13:36:03 GMT
< connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0
```
