### ISSUE TITLE
Uppercaser example might cause an infinite loop

### ISSUE THREAD

**Issue by ChanSek** [firebase/functions-samples#158]
The example mentioned in [https://github.com/firebase/functions-samples/blob/master/quickstarts/uppercase/functions/index.js](url), just converts the message into uppercase and writes it back to DB. This might cause the cloud function to be triggered again and so on.

This should show how to stop this situation.

`const uppercase = original.toUpperCase();
if (uppercase == original) return`

This might work. Not sure as I am unaware of JS and it's APIs.

**Comment by katowulf** [comment]
If you try to write a value to the DB and it doesn't actually change, there's no event triggered, so this shouldn't be able to cause an infinite loop. If you've seen otherwise, please submit with a repro and be sure to use the required issue template.

**Comment by nicolasgarnier** [comment]
Also in this sample we are writing the uppercased string to a different
path on which there is no functions triggers :)

**Comment by inlined** [comment]
And one final nit: you probably want `===` :)
In JavaScript `42 == '42'` but `42 !== '42'`
