### ISSUE TITLE
Hi I am attempting to do exactly as you say in the sample but I get this error in the console: Please log in via your web browser and try again. I already put the mail and password as environment variables but this keeps happening.  Hope you can help me!

### ISSUE THREAD

**Issue by miguelc95** [firebase/functions-samples#159]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by morganchen12** [comment]
Hey, please fill out the issue template and list in detail the steps you took, then reopen this issue.
