### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by Venryx** [firebase/functions-samples#16]
The links are broken, in the following Readme page: https://github.com/firebase/functions-samples/tree/master/limit-children

They are:
https://github.com/firebase/functions-samples/blob/master/limit-children/function/index.js
https://github.com/firebase/functions-samples/blob/master/limit-children/function/package.json

When they should be:
https://github.com/firebase/functions-samples/blob/master/limit-children/functions/index.js
https://github.com/firebase/functions-samples/blob/master/limit-children/functions/package.json

**Comment by nicolasgarnier** [comment]
Thanks @Venryx! fixed as part of 3083469

By the way (just for next time) you can easily edit files using the GitHub UI:

![image](https://cloud.githubusercontent.com/assets/3766663/23784835/30b4ef6a-0519-11e7-87f0-f3db0b80ed2e.png)

And this would have created a PR automatically :)

It just seems that, in this case, it might actually have been less work for you :D
