### ISSUE TITLE
Delete file from storage

### ISSUE THREAD

**Issue by black09bb** [firebase/functions-samples#164]
Hello,
i create app where user can set backgound to your profile. My function start generationg thumbnail when file is upload and on list of user another user see showName and thumbnail background profile.

I have problem when user add another photo. I don’t know how to delete file in my storage. I set new value to background data in user. But this is only replace link. How to delete? Someone mayby have working code for generating thumbnail and delete old?

**Comment by maticzav** [comment]
Hi! 
I couldn't write any sample code, but I found some references which could help!

You probably use [gcs-node library](https://www.npmjs.com/package/@google-cloud/storage), which already has an implemented method for [deleting files](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.37.0/storage/file?method=acl.delete) and then you can just nest everything with `then`-s (Promises). 

Hope it helps!

**Comment by black09bb** [comment]
Hi, unfortunatelly its not working, i tested it some days ago, but i found another solution. gcs have same great function like : gcs.deleteFiles() and its working :D
