### ISSUE TITLE
Firebase call returns http post failure in addition to error message when registering a user that already exists

### ISSUE THREAD

**Issue by fearonf** [firebase/functions-samples#166]
The code calling Firebase is: 

  var email = vm.username;
                    var password = vm.password;

                    firebase.auth().createUserWithEmailAndPassword(email, password).then(function(){
                        console.log("user created in firebase");

                        //Create a new user in the secur database too, for user profile

                         $http.post('/api/users/register',user).then(function(result) {
                             console.log("User profile added to secur database too")
                             console.log(result);
                             vm.message = 'Successful registration, please login.';

                         }).catch(function(error) {
                             console.log(error);

                         })

                    }) .catch(function (error) {
                        // Handle Errors here.
                        var errorCode = error.code;
                        var errorMessage = error.message;

                 
                        vm.error = errorMessage;
                        vm.message='';
                        console.log(vm.error);

                    });

Input: a@b.c       password: aaaaaa
When error returned is 'the email address is badly formatted' , just the message is returned in the console log: 
The email address is badly formatted.

Input: a@gmail.com password: aaaaaa
when error returned is 'The email address is already in use by another account.' the following is logged in the console: 
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=*********************** 400 ()
register-controller.js:67 The email address is already in use by another account.

**Comment by nicolasgarnier** [comment]
@fearonf could you tell me what samples is impacted here? :)

**Comment by gghanshyam01** [comment]
Having same issue. Can't understand what is going wrong

**Comment by jhuleatt** [comment]
Closing since nobody has provided info on which sample this happens in. If someone has more evidence of this issue, feel free to comment and I can reopen.
