### ISSUE TITLE
Feature Request: add default .gitignore to ignore node_modules

### ISSUE THREAD

**Issue by quanvuong** [firebase/functions-samples#17]
This is awesome. Thank you for making it happen!

**Comment by nicolasgarnier** [comment]
You're Welcome!

By the way there is a .gitignore that ignores node_modules:
https://github.com/firebase/functions-samples/blob/master/.gitignore#L2
Please double checks if this works for you :)

**Comment by quanvuong** [comment]
that should work, but I meant for when I run `firebase init functions`

**Comment by quanvuong** [comment]
I'm sorry if this is the wrong place to suggest feature requests for that. I'm not sure where else to do that ...

**Comment by nicolasgarnier** [comment]
Oh I see, can you please file your feature request under https://github.com/firebase/firebase-tools/issues for consideration please?

**Comment by quanvuong** [comment]
yup just did

**Comment by ackvf** [comment]
Just created new repository and my git gui client as well as IDE went crazy. I could not even kill the process :)

**Comment by jimmykane** [comment]
Is this working now or what? I just did an init and my IDE crashed due to the missing ingore rule

**Comment by nicolasgarnier** [comment]
It looks like this was added back in October: https://github.com/firebase/firebase-tools/pull/939

**Comment by jimmykane** [comment]
I just did a fresh setup. Something is wrong :-(

**Comment by nicolasgarnier** [comment]
Yup I confirm it's not there... Let's comment on the PR

**Comment by nicolasgarnier** [comment]
I commented here: https://github.com/firebase/firebase-tools/issues/272

**Comment by jimmykane** [comment]
Thanks @nicolasgarnier !

**Comment by nicolasgarnier** [comment]
@jimmykane actually, never mind. I do have the .gitignore fie generated (I was not checking hidden files):

![image](https://user-images.githubusercontent.com/3766663/49771735-d459c580-fcea-11e8-97e3-8d7ee04a8559.png)
