### ISSUE TITLE
New Request: Sample with remote config

### ISSUE THREAD

**Issue by Rovel** [firebase/functions-samples#171]
I was thinking of a solution where I listen when a remote config value changes and then fire a notification to a specific topic or all users.

I' searched around but didn't found any material around remote config and functions. can it be done?

Thanks in advance.

**Comment by jamesdaniels** [comment]
We do not have remote config hooks for Cloud Functions at this time.

**Comment by Rovel** [comment]
Any plans on that?


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-06-09 20:42 GMT-03:00 James Daniels <notifications@github.com>:

**Comment by jamesdaniels** [comment]
I'll note the feedback for the team, but we don't comment on future roadmap. Keep an eye our future releases.

Thanks!

**Comment by saenzramiro** [comment]
It will be awesome if **Remote Config** can be used for web apps also. Creating a function to return the configuration it was an alternative but seems like we can't. 😢 

Also offer have Analytics for web apps inside Firebase it's a good one. I know we can use https://analytics.google.com but it's not inside Firebase. 😉

**Comment by tthiagomartinho** [comment]
@jamesdaniels Remote API was released, right? Any chance of a new sample containing it?
