### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by jjhesk** [firebase/functions-samples#173]
Having trouble? Try firebase deploy --help
➜  menuPlatforms git:(master) ✗ firebase deploy

=== Deploying to 'mmfo-52563'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Problem preparing functions directory for upload.

**Comment by jamesdaniels** [comment]
The problem will be in your log, if you think you've found a bug with [firebase-tools](https://github.com/firebase/firebase-tools) I recommend opening an issue there.

**Comment by AbdelhalimAhmed** [comment]
i think you should update nodeJs version
