### ISSUE TITLE
es2017-transpile: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mrose** [firebase/functions-samples#179]
### How to reproduce these conditions
Attempted to deploy vanilla example of es2017-transpile to firebase, following the instructions in the README. All went well until attempting firebase deploy.

### Debug output

$ firebase deploy -m "first attempt" --only functions

=== Deploying to 'redacted'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

ReferenceError: regeneratorRuntime is not defined
    at /private/var/folders/fh/...redacted.../index.js:23:112
    at Object.<anonymous> (/private/var/folders/fh/...redacted/index.js:25:208)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11

Having trouble? Try firebase deploy --help

Needless to say, firebase deploy --help did not help in the least.
Googling the interwebs lead me to:

http://mysticcoders.com/blog/fixing-regenerator-runtime-error-integrating-redux-saga

and so I performed 

yarn add babel-polyfill

and added import 'babel-polyfill'; to the top of index.es7
Also, did yarn run prepare (even though yarn add does the install as well. ugh.)

### Et Voila

$ firebase deploy --only functions

=== Deploying to 'redacted'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (24.35 KB) for uploading
✔  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: updating function helloWorld...
✔  functions[helloWorld]: Successful update operation.
✔  functions: all functions deployed successfully!

✔  Deploy complete!

#### please consider updating the README

**Comment by mrose** [comment]
**Edit**: a review of the babel changelog here:
https://github.com/babel/babel/blob/master/CHANGELOG.md
indicates that I might have had a less recent version in my cache which may be responsible for these results.

**Comment by murilovmachado** [comment]
Well, import 'babel-polyfill' didn't work for me.
I've got the same error: regeneratorRuntime is not defined.

**Comment by nicolasgarnier** [comment]
Hey @mrose, @murilovmachado,

What happens when you run `npm run prepare` (or`babel ./*.es7 --presets latest --retain-lines -d ./` direclty) from the `functions` directory (which is the step before `firebase deploy`)? any errors?

**Comment by nicolasgarnier** [comment]
Never mind, I was able to replicate the issue. Thanks for the pointer @mrose mrose, looking into it.

**Comment by nicolasgarnier** [comment]
Fixed! You can have a look at 762ef3c if interested :)

**Comment by ChristianTucker** [comment]
@nicolasgarnier  Running into this problem today.

**Comment by nicolasgarnier** [comment]
Can you open a new issue @ChristianTucker ? and add more details about what's wrong. This issue was fixed in 762ef3c704ff32782a4b8c9d55ccae0260a1c181.
