### ISSUE TITLE
Feature Request: Cloud Function should support user.sendEmailVerification() like client sdk

### ISSUE THREAD

**Issue by Sun3** [firebase/functions-samples#181]
Feature Request:

The ```user.sendEmailVerification()``` needs to be supported by Firebase Cloud Functions. This is available in client side but not server side. When using Cloud Functions to create new users we also need to automatically send Email Verification before new user can use our apps. This is currently as stopping block for our apps.

At this point the ```user.sendEmailVerification()``` gives error that function is not found.

```
    admin.auth().createUser({
        email: emailAddress,
        emailVerified: false,
        password: password,
        displayName: '', //name,
        disabled: false
    })
        .then(function (user) {
            // A error representation of the newly created user is returned
            console.log("Created Firebase User successfully with id: ", user.uid);
            console.log("user.emailVerified:", user.emailVerified);

            // Send Email Verification
            user.sendEmailVerification()
                .then(function (emailSent) {
                    console.log('emailSent ', emailSent);
                })
                .catch(function (error) {
                    console.log('emailSent error ', error);
                });

    // ... Additional code below
```

Thank you and I am open to any suggestions.

**Comment by inlined** [comment]
Refiling under github.com/firebase/firebase-admin-node The admin SDK is the server-side SDK for all backend code, including Cloud Functions. This is the team that can help you with your feature request.

**Comment by Sun3** [comment]
Thanks...
