### ISSUE TITLE
Sending Welcome Email on user create not working with Mailgun

### ISSUE THREAD

**Issue by coder3101** [firebase/functions-samples#186]
I am on Spark Plan and I am using Mailgun to deliver mails to my user when they create an account and delete it. I am following the mailgun-js docs and I am pretty sure I am doing things correctly.  But on my Firebase functions console I am getting error  **error: getaddrinfo enotfound api.mailgun.net api.mailgun.net:443**

Sorry if this is not a Firebase issue but I would be happy if anyone could provide me correct way to implement this feature using Mailgun.

Thank You, 
Firebase

**Comment by coder3101** [comment]
Okay I upgraded to Blaze Plan, and now it is working fine. I would suggest the maintainers/contributors of this project to please specify in the Readme that, outbound requests are not available in free version.. so to use sendgrid, Mailgun one needs to upgrade the plan. Thank you..

**Comment by nicolasgarnier** [comment]
Just added a note for that. Thanks for pointing this out @coder3101
