### ISSUE TITLE
const gcs = require('@google-cloud/storage')({keyFilename: 'service-account-credentials.json'});

### ISSUE THREAD

**Issue by gustavobrian** [firebase/functions-samples#188]
Please, si your add the credential, show link instruction to get de json service account, your sample is for senior programer function firebase and excluded the new user firebase !!!!! rrrrrrrrrrr

**Comment by jenperson** [comment]
There are directions on how to generate the Service Account Key in the README.

**Comment by MurWade** [comment]
False @jenperson

**Comment by dshukertjr** [comment]
This service account key is supposed to be kept private(not to be uploaded to a public directory like github), right?
