### ISSUE TITLE
firebase.auth.AuthCredential.provider is deprecated. Please use the providerId field instead.

### ISSUE THREAD

**Issue by DenFav** [firebase/functions-samples#191]
### How to reproduce these conditions

Stripe

`[Warning] firebase.auth.AuthCredential.provider is deprecated. Please use the providerId field instead. (firebase-auth.js, line 99)
`
1. I followed all the steps.
2. On the step 3 I have downloaded stripe source code and copied it to the project folder
3. Enabled Google authentication for my project in firebase
4. After login in I see the screen with my email, Sigh out button and three dots(see image link) 

### Debug output

**[Warning] firebase.auth.AuthCredential.provider is deprecated. Please use the providerId field instead. (firebase-auth.js, line 99)**

**Screenshots**
http://prntscr.com/fupbxw

### Expected behavior

Expected to see adding card and make payment page

### Actual behavior
Can see only my email, Sigh out button and three dots( as presented on the screenshot

**Comment by josuesossou** [comment]
having same issue too

**Comment by orabs** [comment]
same here

**Comment by jhuleatt** [comment]
Stripe was overhauled in #728
