### ISSUE TITLE
custom icon in notification

### ISSUE THREAD

**Issue by UncleJey** [firebase/functions-samples#192]
Hi guys!

sending notification with firebase admin functions.

> function sendViaFCM(uid, tokens, senderName, recName, pIcon) 
> {
>   var nm = recName.split(' ')[0];
>       let payload = 
>       {
>         notification: 
>         {
>           title: `${nm}! You have new gift!`,
>           body: `${senderName} sent you gift!`,
>           icon: 'notify_icon_small',
> 	  sound: 'default'
>         }
>       };
> 
>    return admin.messaging().sendToDevice(tokens, payload);
> }
> 

can't find docs or example how to customize icon from sender profile recieving from user's info
uri like this
"https://scontent.xx.fbcdn.net/v/t1.0-1/s100x100/10413424_556871067767327_58026553066132523_n.jpg?oh=c254b933b74ec238bbc1d84dcbe39a6a&oe=5A01AED6"

this sample have icon.
but it does not work
https://github.com/firebase/functions-samples/blob/master/fcm-notifications/functions/index.js

**Comment by jamesdaniels** [comment]
See [admin.Messasing.NotificationMessagePayload#icon in the reference guide](https://firebase.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload#icon): for the Web this is an image URL + Android it's a drawable resource in your application.
