### ISSUE TITLE
EXIF-Images, getting metadatafails

### ISSUE THREAD

**Issue by Sagar-AppLogics** [firebase/functions-samples#196]
Copy entire "[functions-samples/exif-images/](https://github.com/firebase/functions-samples/tree/master/exif-images)" project and deploy as is.

Upload an image to Storage,

Log will display an error:

`TypeError: Cannot read property 'match' of undefined
    at imageMagickOutputToObject (/user_code/index.js:77:23)
    at spawn.then.result (/user_code/index.js:58:24)`

the particular function that fails is (line: 75):

`function imageMagickOutputToObject(output)`

The point at which it fails in this function is (Line: 77):

`const lines = output.match(/[^\r\n]+/g);`

from the error message the variable (passed to this function) "output" is "undefined".

So going to the call of this function in the body of the `functions.storage.object().onChange` (Line: 33). You will see the call to the imageMagickOutputToObject call is made which reads (Line: 58):

const metadata = imageMagickOutputToObject(result.stdout);

According to the error message the `result` object does not contain a key called `stdout`.

I Logged a JSON.stringify() on the result object and found it only had two keys, childProcess and code.
Child process was the only key to contain a subkey stdout, so i rewrote the line 58 to:

`const metadata = imageMagickOutputToObject(result.childProcess.stdout);`

when doing this, the `output` variable is no longer undefined - i.e  passed to  (line: 75):

`function imageMagickOutputToObject(output)` 

this however now yields the following error in the functions log:

`TypeError: output.match is not a function
    at imageMagickOutputToObject (/user_code/index.js:77:24)
    at spawn.then.result (/user_code/index.js:58:24)`

This suggests that the match function is not working or the object variable is not in an expected format. This feature would make so much sense! would be great to have working 👍  :)

**Comment by SamMatthewsIsACommonName** [comment]
I'm having the same issue. However the output of result.childProcess.stdout seems to be unrelated (i.e specific to the process):
````
Socket {
  connecting: false,
  _hadError: false,
  _handle: null,
  _parent: null,
  _host: null,
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { finish: [ [Function: onSocketFinish] ],
     _socketEnd: [Function: onSocketEnd],
     close: [Function] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: true,
     ended: true,
     finished: true,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: true,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: false,
  allowHalfOpen: false,
  destroyed: true,
  _bytesDispatched: 0,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  read: [Function],
  _consuming: true,
  _idleNext: null,
  _idlePrev: null,
  _idleTimeout: -1,
  write: [Function: writeAfterFIN] }
````

**Comment by nicolasgarnier** [comment]
Looks like we needed an additional option to the `.spawn` call to gather `stdout`. We forgot to add this when we switched from `.exec` to `.call`.

Should be fixed now :)
