### ISSUE TITLE
Errors accessing public folder for server side render

### ISSUE THREAD

**Issue by larry-travelbytes** [firebase/functions-samples#199]
I am running the isomorphic-react-app example and when I deploy I am getting 404 errors for the client.bundle.js which is deployed in the public folder.

Do I need to set anything up to give the cloud function access to the public folder?

Any advice please, seems like I just don't have access to the public folder.

**Comment by larry-travelbytes** [comment]
Seems I was accessing the site with the incorrect URL instead of hitting the Hosted site I was calling the function directly, which rendered the server-side generated HTML.

**Comment by nicolasgarnier** [comment]
Yup that must have been it :)
