### ISSUE TITLE
functions: Cannot start emulator.

### ISSUE THREAD

**Issue by nhathiwala** [firebase/functions-samples#200]
Hi, I'm unable to emulate my functions. It shows following error:
`Cannot start emulator. Error: Cannot find module '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node'`

Is it a bug or is there any fault in my firebase-tool setup?

**Comment by nicolasgarnier** [comment]
Hey @nhathiwala,

I never came accross this in my setup. Maybe try de-installing and re-installing `firebase-tools` just in case :)

**Comment by tzs007** [comment]
same sh*t here... I uninstalled and reinstalled firebase-tools but nothing happened...

I tried it on Windows 10 built in linux bash.

**Comment by inlined** [comment]
@tzs007 It seems like there's an issue with gRPC, which is a separate (also Google driven) library. Can you try running

```bash
npm install -g grpc
```

And see if that completes successfully? There may have been an issue installing this module that was lost in other noise when you installed `firebase-tools`. If there are errors when installing grpc, can you file an issue at [https://github.com/grpc/grpc](https://github.com/grpc/grpc) and reference this one?

**Comment by nicolasgarnier** [comment]
Closing, please let us know/reopen if you are still having the issue after trying @inlined command.

**Comment by jaycreate** [comment]
Hi there, 
I try many ways still getting same error

It's show 
`functions: Cannot start emulator. Error: Cannot find module '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node'`

When I try to install it again it was success 
but it show installed via remove like this

`[grpc] Success: "/usr/local/lib/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64/grpc_node.node" is installed via remote`

When I look in directory 
`/usr/local/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary`

there is nothing inside as well and and still could not run Functions in local.
My System is: macOS Sierra 10.12.6

Please give me some advice, thank you in advance.
