### ISSUE TITLE
Error parsing triggers: Cannot find module './db.json'

### ISSUE THREAD

**Issue by alxvallejo** [firebase/functions-samples#203]
I'm trying to add image-sharp so i can automatically generate thumbnails. I've ran npm install at the functions level and added the following modules:

```
const functions = require("firebase-functions");
const gcs = require("@google-cloud/storage")();
const path = require("path");
const sharp = require("sharp");
const _ = require("lodash");
const os = require("os");
```
When I run `firebase deploy` I get this message at `functions: preparing functions directory for uploading...`

```
Error: Error parsing triggers: Cannot find module './db.json'
Try running "npm install" in your functions directory before deploying.
```

If i remove those new module dependencies from my index.js i don't get the error.

**Comment by inlined** [comment]
A quick google search suggests that this is an error that can happen with the `mime-db` node extension. This is imported indirectly by `@google-cloud/storage` via the `mime-types` library.

Just in case the node modules aren't installed correctly, I would consider running `npm install` from within your `functions` directory and trying again. If that doesn't work, I may need to see all of your `firebase-debug.log` to better diagnose what's happened. There's a good chance I'll need to either send you to the `google-cloud-node` NPM repo for a bug report or to the proper Firebase support channels since this bug doesn't really have anything to do with Cloud Functions, its SDKs, or any particular sample.

**Comment by joemanfoo** [comment]
I'm having an issue as well with `Cannot find module ...` however my issue is that it cannot find `sharp` which is installed (I can open up a node terminal and run `const sharp = require('sharp')`).

All the logs point to are:
`!  functions[resizeProduct]: Deploy Error: Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'sharp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:24:13)

    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

and the code: `at Object.<anonymous> (/user_code/index.js:24:13)`
is: `const sharp = require('sharp')`

Node version is 6.11.1, firebase-tools I just updated last night to 3.9.2

All of th code had previously updated functions properly in the past and there's been no code changes other than to a .json file.

I tried the `npm install` to make sure all modules were installed and the output from that was all modules were current.

**Comment by inlined** [comment]
It's possible that "sharp" is loading in a node terminal because it's been installed globally. Can you verify that you have a directory `functions/node_modules/sharp`?

**Comment by joemanfoo** [comment]
`
    PS C:\Users\------\Documents\GitHub\------\functions> cd .\node_modules\sharp\
    PS C:\Users\------\Documents\GitHub\------\functions\node_modules\sharp> dir
    
    
    Directory: C:\Users\------\Documents\GitHub\------\functions\node_modules\sharp
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----         8/8/2017  12:06 AM                build
    d-----         8/8/2017  12:06 AM                docs
    d-----         8/8/2017  12:06 AM                lib
    d-----         8/8/2017  12:06 AM                node_modules
    d-----         8/8/2017  12:06 AM                src
    d-----         8/8/2017  12:06 AM                vendor
    -a----        11/8/2016   7:01 AM            148 .npmignore
    -a----         1/5/2017   5:18 PM           9809 binding.gyp
    -a----        1/14/2017   6:23 AM           4213 binding.js
    -a----        3/24/2017  12:58 PM           3998 CONTRIBUTING.md
    -a----       10/26/2013  10:57 AM          10273 LICENSE
    -a----         8/8/2017  12:06 AM           5296 package.json
    -a----         1/5/2017   5:23 PM           2625 README.md


    PS C:\Users\------\Documents\GitHub\------\functions\node_modules\sharp>`

It's installed local

**Comment by joemanfoo** [comment]
The curious issue here is the previously the sharp module would and did install on GCF but now it does not. I commented out the line to `require('sharp')` in the `index.js` file but left the dependency in the `package.json` and the `firebase deploy --only functions` worked. 

So it seems as though there's a problem with GCFs `npm install`ing

Maybe this thread should be on the firebase-tools repo rather than here...

**Comment by joemanfoo** [comment]
Seems my issue was with the version of `sharp` I upgraded to sharp@0.18.1 as is listed in the sample functions and deployment worked...however there's incompatibility with my code and the newer version of `sharp` but at least I can deploy functions successfully once again.

**Comment by inlined** [comment]
Glad to hear you're sorted out. We'll look at updating the dependencies in the sample.

**Comment by jyoungqu** [comment]
@inlined - I think you're code and dependencies are fine, it was dependency on my end (sharp@0.17.1) that wouldn't install on GCF, once I upped my version of Sharp all was well.

**Comment by joemanfoo** [comment]
@inlined - I think you're code and dependencies are fine, it was dependency on my end (sharp@0.17.1) that wouldn't install on GCF, once I upped my version of Sharp all was well.
