### ISSUE TITLE
Remove crypto package dependency

### ISSUE THREAD

**Issue by rmehlinger** [firebase/functions-samples#204]
Three of the example functions in this project, `github-to-slack`, `instagram-auth`, and `linkedin-auth`, use the [NPM crypto module](https://www.npmjs.com/package/crypto), rather than the built-in [NodeJS crypto module](https://nodejs.org/api/crypto.html). Unfortunately, the NPM crypto module has no license, is at version 0.0.3, and has not been touched in six years. I suspect that the original authors intended to use the built-in NodeJS crypto library. As each of these three packages is intended to be run in a NodeJS environment, they should use the NodeJS crypto library.

## https://github.com/Gozala/crypto/issues/14

**Comment by nicolasgarnier** [comment]
Thanks for the PRs!
