### ISSUE TITLE
Error parsing triggers: Cannot find module

### ISSUE THREAD

**Issue by alexsanderkhitev** [firebase/functions-samples#208]
Hello! I'm trying to do a function that I will use in a couple of other functions. Each function is in different files.

My function that I will use in several other functions looks like this.

```
exports.createAppBadge = function(categoryID, dataID, senderID) {

};

```
I tried to use it in another function and try to make a delpoy.

`const createAppBadge = require('AppBadges/createAppBadge.js');
`

But I always get an error.

Error: Error parsing triggers: Cannot find module ''AppBadges/createAppBadge.js'

I also tried to make a function inside a class, but I get the same thing.

Although I use database trigger functions from this directory and it works well. eg

within index.js 
`exports.removeAppBadge = require("./AppBadges/removeAppBadge.js");
`

Please tell me how can I fix this? Thanks!

**Comment by nicolasgarnier** [comment]
Hey @alexsanderkhitev,

If your file is in the `./functions/AppBadges/` folder it looks like normally `exports.removeAppBadge = require('./AppBadges/removeAppBadge');` should work.

Also just FYI this seems more of a general NodeJS issue then an issue with one of the samples in this repo. It seems using StackOverlfow would be more appropriate for this.

Cheers!
