### ISSUE TITLE
i couldn't give any imput in cmd prompt after this session

### ISSUE THREAD

**Issue by srikanthpodugu** [firebase/functions-samples#212]
i  hosting: Serving hosting files from: app
+  hosting: Local server: http://localhost:5000

127.0.0.1 - - [18/Aug/2017:04:18:39 +0000] "GET / HTTP/1.1" 404 139 "-" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
127.0.0.1 - - [18/Aug/2017:04:18:59 +0000] "GET /favicon.ico HTTP/1.1" - - "http://localhost:5000/" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
127.0.0.1 - - [18/Aug/2017:04:19:07 +0000] "GET / HTTP/1.1" 404 139 "-" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
127.0.0.1 - - [18/Aug/2017:04:19:07 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
127.0.0.1 - - [18/Aug/2017:04:40:10 +0000] "GET / HTTP/1.1" 404 139 "-" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

**Comment by nicolasgarnier** [comment]
Please re-open an issue with more details about your exact issu, a step by step way to replicate the issue, expected result and experienced result.

In general please follow the issue template :)
