### ISSUE TITLE
All samples should have firebase-functions version updated

### ISSUE THREAD

**Issue by laurenzlong** [firebase/functions-samples#219]
Addresses https://github.com/firebase/functions-samples/issues/214

The samples use outdated firebase-functions, and this causes some issues since there's been some major features added. The latest SDK is 0.6.2

**Comment by laurenzlong** [comment]
firebase-admin should also be updated to `~5.2.1`

**Comment by samtstern** [comment]
This is solved by @dpebot , our new best friend.
