### ISSUE TITLE
Cannot find module 'mkdirp-promise'

### ISSUE THREAD

**Issue by Midhilaj** [firebase/functions-samples#22]
Error: Error parsing triggers: Cannot find module 'mkdirp-promise'
[full code ](https://github.com/firebase/functions-samples/blob/master/generate-thumbnail/functions/index.js)
       # firebase deploy --only functions 

=== Deploying to '0000000'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'mkdirp-promise'

Try running "npm install" in your functions directory before deploying.

Having trouble? Try firebase deploy --help

**Comment by nicolasgarnier** [comment]
Have you tried running "npm install" in the `functions` directory first? :)

**Comment by nicolasgarnier** [comment]
PS: I just updated the README with more details at: https://github.com/firebase/functions-samples/tree/master/generate-thumbnail

**Comment by Midhilaj** [comment]
root@midhilaj-Notebook-PC:/opt/functions# firebase deploy --only functions 
=== Deploying to '000000000201298'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
✔  runtimeconfig: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

/tmp/fbfn_47581M37zw7OZEyV/index.js:84
    Contact GitHub API Training Shop Blog About 
            ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:16:9)
    at Module._compile (module.js:571:32)

**Comment by Midhilaj** [comment]
thumbnail size is greater than original image ??
check below image
https://firebasestorage.googleapis.com/v0/b/admob-app-id-9019201298.appspot.com/o/thumb.png?alt=media&token=022b5efc-7237-494a-a1c1-662fc37b1f1d

**Comment by nicolasgarnier** [comment]
The function will generate a "thumbnail" that fits inside a 200x200px box with a default compression quality of 85% for JPEGs.
If you upload an image that's already smaller than 200x200px then this will indeed make a larger image (also same problem if you upload a JPEG with compression lower than 85%). This is a sample so feel free to modify so that it fits your own need. For instance you can lower the compression quality by passing something like `-quality 70%` and make the image smaller by changing the `THUMB_MAX_HEIGHT` and `THUMB_MAX_WIDTH` values.

**Comment by Midhilaj** [comment]
token issue how to make equal token for both thumb and original
