### ISSUE TITLE
Auth Trigger doesn't include displayName for email+password registration

### ISSUE THREAD

**Issue by codeofsumit** [firebase/functions-samples#221]
Hey there,

so at the firebaseui login flow, I can provide a "first & lastname", which on the frontend login callback will be available through `displayName`.

![image](https://user-images.githubusercontent.com/2399810/29741518-1e69d66e-8a6f-11e7-97a2-4fbdd791da4f.png)
![image](https://user-images.githubusercontent.com/2399810/29741531-51490faa-8a6f-11e7-8e99-79696b7b1695.png)

However, when I want to access this data from a firebase cloud function on creation of a user, the `displayName` property is missing from the payload inside `event.data`.

```js
exports.saveUserData = functions.auth.user().onCreate(event => {
  const user = event.data; // The Firebase user.
  console.log(event);
  const uid = user.uid;
  const email = user.email; // The email of the user.
  const displayName = user.displayName; // The display name of the user.
  const photoURL = user.photoURL || 'https://firebasestorage.googleapis.com/v0/b/medaku-b583e.appspot.com/o/default_avatar.png?alt=media&token=4cb3410a-8bb4-4b48-be09-a2226f5584ad'; // The display name of the user.
  const [firstname, lastname] = displayName ? displayName.split(' ') : ['Fallback Name, as displayName might be missing', 'lastname'];

  console.log('new user registered: ', user);

  const newUser = {
    uid,
    profile: {
      firstname,
      lastname,
      photoURL,
      email: {
        address: email,
        verified: false,
      },
      createdAt: Date.now(),
    }
  }


  return admin.database().ref(`users/${uid}`).set(newUser);
});
```

the two `console.logs` output this data in the functions logs

```
{ data: 
   { email: 'lala@gmail.com',
     metadata: 
      { createdAt: 2017-08-26T12:59:48.000Z,
        lastSignedInAt: 2017-08-26T12:59:48.000Z },
     uid: 'XYRmB99wkpMZhQeJ84v1DTlj5oF3' },
  eventId: 'ad174ea3-e5d6-4e51-92b8-2b67dafbaf4c',
  eventType: 'providers/firebase.auth/eventTypes/user.create',
  notSupported: {},
  resource: 'projects/memema-lala',
  timestamp: '2017-08-26T12:59:48.535Z',
  params: {} }
```

```
new user registered:  { email: 'lala@gmail.com',
  metadata: 
   { createdAt: 2017-08-26T12:59:48.000Z,
     lastSignedInAt: 2017-08-26T12:59:48.000Z },
  uid: 'XYRmB99wkpMZhQeJ84v1DTlj5oF3' }
```

For the facebook login, the `displayName` property is available on the frontend callback and the cloud function. It's just the email flow that is different.

How can I access displayName from the email flow inside my cloud functions?

**Comment by codeofsumit** [comment]
closing this for https://github.com/firebase/firebase-functions/issues/95

**Comment by eclewlow** [comment]
This example basically doesn't work, according to this thread.

https://github.com/firebase/functions-samples/blob/62379ddeec765c44c21f88b53b2c8ef4077201a2/quickstarts/email-users/functions/index.js#L49

**Comment by eclewlow** [comment]
Oh, actually. Well, it works with firebase-admin.
https://firebase.google.com/docs/auth/admin/manage-users#create_a_user
