### ISSUE TITLE
Isomorphic React App@AdminSDK: ERROR in ../functions/~/firebase-admin/lib/auth/credential.j

### ISSUE THREAD

**Issue by valorloff** [firebase/functions-samples#222]
Hi!
Due to 
`const firebase = global.firebase || require('firebase');`
deprecated, impossible tie new Firebase Admin SDK by reason of webpack errors:
```
ERROR in ../functions/~/firebase-admin/lib/auth/credential.js
Module not found: Error: Can't resolve 'fs' in '/home/valaoffice/projects/dst-iso/functions/node_modules/firebase-admin/lib/auth'
ERROR in ../functions/~/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'net'
```
and so on.
Please give correct webpack.config

**Comment by nicolasgarnier** [comment]
Hey @valorloff 

We need to update the versions of libraries used in the project. Have you tried updating to the latest versions? Just change the values in the `functions/package.json` file as discussed in #219

**Comment by nicolasgarnier** [comment]
Alternatively, I am working on an isomorphic react+redux+functions template in https://github.com/nicolasgarnier/friendlypix-web-react

It's not full ready and cleaned up yet but the current state is already usable. When it's ready I'll move part of it over here.

**Comment by valorloff** [comment]
package.json:
```
"dependencies": {
    "firebase": "3.9.0",
    "firebase-admin": "^5.2.1",
    "firebase-functions": "^0.6.2",
    "lodash": "4.17.4",
    "react": "15.5.4",
    "react-dom": "15.5.4",
    "react-router": "4.1.1",
    "react-router-dom": "4.1.1"
  }
```
if i change oldscool firebase to new forebase-admin: firebase-database.js:
```
// const firebase = global.firebase || require('firebase');
const admin = require('firebase-admin');
const initializeApp = config => {
  if (firebase.apps.length === 0) {
    admin.initializeApp(config);
    // firebase.initializeApp(config);
  }
```   
```
WARNING in ../functions/~/hash-stream-validation/index.js
Module not found: Error: Can't resolve 'fast-crc32c' in '/home/valaoffice/projects/dst-iso/functions/node_modules/hash-stream-validation'
 @ ../functions/~/hash-stream-validation/index.js 5:8-30
 @ ../functions/~/@google-cloud/storage/src/file.js
 @ ../functions/~/@google-cloud/storage/src/index.js
 @ ../functions/~/firebase-admin/lib/storage/storage.js
 @ ../functions/~/firebase-admin/lib/storage/register-storage.js
 @ ../functions/~/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js

WARNING in ../functions/~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ../functions/~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ../functions/~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

ERROR in ../functions/~/firebase-admin/lib/auth/credential.js
Module not found: Error: Can't resolve 'fs' in '/home/valaoffice/projects/dst-iso/functions/node_modules/firebase-admin/lib/auth'
 @ ../functions/~/firebase-admin/lib/auth/credential.js 22:9-22
 @ ../functions/~/firebase-admin/lib/firebase-namespace.js
 @ ../functions/~/firebase-admin/lib/default-namespace.js
 @ ../functions/~/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js

ERROR in ../functions/~/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'net' in '/home/valaoffice/projects/dst-iso/functions/node_modules/faye-websocket/lib/faye/websocket'
 @ ../functions/~/faye-websocket/lib/faye/websocket/client.js 2:13-27
 @ ../functions/~/faye-websocket/lib/faye/websocket.js
 @ ../functions/~/firebase-admin/lib/database/database.js
 @ ../functions/~/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js

ERROR in ../functions/~/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'tls' in '/home/valaoffice/projects/dst-iso/functions/node_modules/faye-websocket/lib/faye/websocket'
 @ ../functions/~/faye-websocket/lib/faye/websocket/client.js 3:13-27
 @ ../functions/~/faye-websocket/lib/faye/websocket.js
 @ ../functions/~/firebase-admin/lib/database/database.js
 @ ../functions/~/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js
```
and so on large error list

**Comment by nicolasgarnier** [comment]
Both `firebase` and `firebase-admin` are required for that sample. `firebase` gets packaged for the client, it is not deprecated. See: https://www.npmjs.com/package/firebase

it looks like the latest errors that you get maybe be happening in an older version of webpack which happens with some Node environments configurations. Can you try to upgrade to webpack v3.5.5 ? (change that in the package.json inside `isomorphic-react-app/src/package.json`)

Otherwise you can also check https://github.com/nicolasgarnier/friendlypix-web-react which is using the latest of everything.

**Comment by valorloff** [comment]
seems, friendlypix-web-react without SSR?

**Comment by valorloff** [comment]
after webpack upgrade, errors 
`Module not found: Error: Can't resolve`
also upgraded :)
```
WARNING in ../functions/node_modules/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ../functions/node_modules/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

WARNING in ../functions/node_modules/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ../functions/node_modules/hash-stream-validation/index.js
Module not found: Error: Can't resolve 'fast-crc32c' in '/home/valaoffice/projects/dst-iso/functions/node_modules/hash-stream-validation'
 @ ../functions/node_modules/hash-stream-validation/index.js 5:8-30
 @ ../functions/node_modules/@google-cloud/storage/src/file.js
 @ ../functions/node_modules/@google-cloud/storage/src/index.js
 @ ../functions/node_modules/firebase-admin/lib/storage/storage.js
 @ ../functions/node_modules/firebase-admin/lib/storage/register-storage.js
 @ ../functions/node_modules/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js

ERROR in ../functions/node_modules/google-auth-library/lib/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in '/home/valaoffice/projects/dst-iso/functions/node_modules/google-auth-library/lib/auth'
 @ ../functions/node_modules/google-auth-library/lib/auth/googleauth.js 21:11-35
 @ ../functions/node_modules/google-auto-auth/index.js
 @ ../functions/node_modules/gcs-resumable-upload/index.js
 @ ../functions/node_modules/@google-cloud/storage/src/file.js
 @ ../functions/node_modules/@google-cloud/storage/src/index.js
 @ ../functions/node_modules/firebase-admin/lib/storage/storage.js
 @ ../functions/node_modules/firebase-admin/lib/storage/register-storage.js
 @ ../functions/node_modules/firebase-admin/lib/index.js
 @ ../functions/firebase-database.js
 @ ./containers/App.jsx
 @ ./containers/ClientApp.js
```
src/package.json:
```
"devDependencies": {
    "babel-core": "6.24.1",
    "babel-loader": "7.0.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "webpack": "^3.5.5"
  }
```

**Comment by nicolasgarnier** [comment]
Friendlypix-web-react has SSR/Isomorphism on Google Cloud Functions. See: https://github.com/nicolasgarnier/friendlypix-web-react/blob/master/microservices/renderTemplate.js

**Comment by valorloff** [comment]
what is diffs between friendlyPix and functions/Isomorphic React App ?

**Comment by nicolasgarnier** [comment]
Here are a few differences:

 - It's using redux and the react-redux-firebase library
 - It's authenticating users from the client on the server so that we can pre-render even private data.
 - It's not packing a server bundle, instead it runs all the files through Babel and simply leaves all the JS files to be uploaded on the server.
 - It has NPM scripts to run in local/dev mode.

**Comment by valorloff** [comment]
Thanks, very interesting!
But what about upgrade to firebase-admin initialize app?
Can you help me with that bunch errors?
Or ignore it yet ?

**Comment by nicolasgarnier** [comment]
Don't upgrade to firebase-admin. Switch back to firebase. The code is supposed to run on the client and firebase-admin does not work on a web page.

**Comment by valorloff** [comment]
But functions/firebase-database.js works on server!
and how about warning:

> The 'credential' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.

**Comment by nicolasgarnier** [comment]
Ah yes, I see why this happens...

This is happening because when rendered on the server we are using a setup which is normally for firebase-admin (but we are trying to pass it to 'firebase'). It would be best not to do that so the sample is not accurate anymore.

The best would be to generate a file with the firebase configuration (you can use the firebase CLI for that). This what i do in friendlypix (there is an npm script which generates the firebase config file and then i use it in the ./frontend/App.jsx

**Comment by valorloff** [comment]
Yes!
That's what I need! thanks for 
`createfirebaseconf`
and
`const firebaseConfig = require('./firebase-config.json').result;`

**Comment by valorloff** [comment]
thanks
