### ISSUE TITLE
Login issues when no user

### ISSUE THREAD

**Issue by Ionut-Milas** [firebase/functions-samples#226]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by nicolasgarnier** [comment]
Closing because there is no details on the bug report but please if you are stil facing an issue r discovered a bug feel free to reopen one and add more details (at least a description of the issue and which sample is impacted :)
