### ISSUE TITLE
docs(readme): add a Table Of Contents or create a Minisite

### ISSUE THREAD

**Issue by adamlaz** [firebase/functions-samples#233]
## Summary 
* It would be great to have a simple Table of Contents at the top of the [README.md](https://github.com/firebase/functions-samples/blob/master/README.md). 
  _* Numbered list w/ Titles_
* It'd be even better to have a static site with better ux than readme.md. 
  _* Titles & Descriptions_
  _* Screenshots_
  _* Tags and/or Categories_

## Why?
There are quite a few cloud functions now and it's hard to know what is in here without following the repo activity or spending time+ to grok. 

---

> I will try to add more comments with additional information, or submit a PR if I can!

**Comment by nicolasgarnier** [comment]
:+1: Actually I have some plan to create a standalone minisite for this repo. Just a plan now as I didn't even get started yet. (And sure, a ToC in the mean time would make sense and be nice)

With a minisite we could also list other (3rd party) repos and maybe also allow Firebase samples that are not Cloud Functions specific.

**Comment by samtstern** [comment]
I believe this is now solved in a few ways:

  1. There is a TOC
  2. We can customize the UX here: https://firebaseopensource.com/projects/firebase/functions-samples/
