### ISSUE TITLE
Can't Run Stripes Sample Locally

### ISSUE THREAD

**Issue by ilyaigpetrov** [firebase/functions-samples#239]
### How to reproduce these conditions

1. `npm install -g firebase-tools` (from ["Run Functions Locally" docs](https://firebase.google.com/docs/functions/local-emulator))
2. Follow [deploy instructions](https://github.com/firebase/functions-samples/tree/master/stripe#deploy-and-test) except last two steps (deploying) and don't switch to Blaze plan.
3. `firebase serve`
4. Open http://localhost:5000 and sign in via Google.

### Debug output

![Screenshot](https://user-images.githubusercontent.com/1090811/30692859-a9e1623a-9ee6-11e7-9ecb-23e725a6f1f0.png)

### Expected behavior

Credit card input controls must appear.

### Actual behavior

I see ellipses and nothing happens.

# Update

This issue feels more like a Stackoverflow question, I should have posted there instead. I apologize if my issue isn't appropriate here.

**Comment by nicolasgarnier** [comment]
@jamesdaniels could you have a look?

**Comment by mattplu** [comment]
Did you ever figure this out?  I have the exact same issue right now.

**Comment by jhuleatt** [comment]
Stripe samples have been overhauled in #728
