### ISSUE TITLE
Error sending webhook to slack

### ISSUE THREAD

**Issue by aaronte** [firebase/functions-samples#24]
**Issue**

• Following the [Github to Slack](https://github.com/firebase/functions-samples/tree/master/github-to-slack) example
• I am trying to send my own webhook request like this:
```js
function postToSlack() {
  return rp({
        method: 'POST',
        uri: "https://hooks.slack.com/services/TEAM_ID/BOT_ID/API_KEY",
        body: { 
            channel: "#CHANNEL_NAME", 
            username: "webhookbot", 
            text: "MESSAGE"
        },
        json: true
    });
}
```
• I am getting this error
```js
{
  "name": "RequestError",
  "message": "Error: getaddrinfo ENOTFOUND hooks.slack.com hooks.slack.com:443",
  "cause": {
    "code": "ENOTFOUND",
    "errno": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "hooks.slack.com",
    "host": "hooks.slack.com",
    "port": 443
  },
  "error": {
    "code": "ENOTFOUND",
    "errno": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "hooks.slack.com",
    "host": "hooks.slack.com",
    "port": 443
  }
}
```
• I tried to run the same function I am deploying in a my local node server and it works just fine

**Comment by rockwotj** [comment]
Are you on the free plan? The free plan cannot make external network requests. See more details here: https://firebase.google.com/pricing/binder bullet point 3

**Comment by aaronte** [comment]
@rockwotj can't seem to open the link?

**Comment by rockwotj** [comment]
Typo, I fixed the link. Try again

**Comment by aaronte** [comment]
@rockwotj makes sense. Thanks!

**Comment by nicolasgarnier** [comment]
Jut added a note about that in the README for this sample. Thanks for pointing this out :)

**Comment by aaronte** [comment]
@nicolasgarnier no worries! that would save some people time debugging for sure!
