### ISSUE TITLE
Add memory limits to memory intensive samples

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/functions-samples#241]
For instance ImageMagick samples should use option `'-limit memory Xmb -limit map Ymb'` to set limits lower than the memory available in the GCF instance.

**Comment by nicolasgarnier** [comment]
Need to investigate using somthing like:
```
var os = require('os');
console.log(os.freemem())
```

to automatically set these limits with the right values.

**Comment by inlined** [comment]
Does `os.freemem()` actually expose the real limits of the GCF instance? We might need to come up with a plan to document/make available the GCF quotas inside the runtime.

**Comment by nicolasgarnier** [comment]
Not sure. I just tested on an instance with 2GB memory and I got his:

`2078740130274214000`

The docs says that this should be free memory in Bytes but then this would be 1935977610 GB free memory :D ...

**Comment by nicolasgarnier** [comment]
So there definitely seems to be an issue. Running `os.freemem()` on my laptop returns something in the expected range: `537182208` so the number printed on GCF is definitely off.

**Comment by inlined** [comment]
Just CCd you on an internal bug to track this as a feature request.

**Comment by samtstern** [comment]
This is being tracked internally as b/67049880
