### ISSUE TITLE
No matching version found for @google-cloud/firestore@^0.7.0

### ISSUE THREAD

**Issue by ajaybeniwal** [firebase/functions-samples#245]
### How to reproduce these conditions
NPM install is failing 
**Sample name or URL where you found the bug**
fulltext-search-firestore
**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**
npm install is giving above error

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by nicolasgarnier** [comment]
Just updated the packages.json to 0.8.1

Thanks for repporting this @ajaybeniwal !
