### ISSUE TITLE
Fake event for firestore

### ISSUE THREAD

**Issue by kpsrinivas** [firebase/functions-samples#250]
Is there any example for fake event for a firestore testing ?

**Comment by kpsrinivas** [comment]
This works. Used to path not defined error. Wondering if it can be better.
const chai = require('chai');
const assert = chai.assert;

const chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);

// Sinon is a library used for mocking or verifying function calls in JavaScript.
const sinon = require('sinon');


describe('Discussion triggers', () => {
  // [START stubConfig]
  var myFunctions, configStub, adminInitStub, functions, admin;

  before(() => {
  
    admin =  require('firebase-admin');
    adminInitStub = sinon.stub(admin, 'initializeApp');
    functions = require('firebase-functions');
    process.env.GCLOUD_PROJECT = 'not-a-project';
    configStub = sinon.stub(functions, 'config').returns({
      firebase: {
        databaseURL: 'https://not-a-project.firebaseio.com',
        storageBucket: 'not-a-project.appspot.com',
        authDomain: "not-a-project.firebaseapp.com",
        projectId: "not-a-project"
      }
    });
    
    myFunctions = require('../index.js');
    
  });

  after(() => {
    // Restoring our stubs to the original methods.
    configStub.restore();
    adminInitStub.restore();

    delete process.env.GCLOUD_PROJECT;
  });
  // [END stubConfig]

  describe('questionCreate', () => {
    it('should create activity ref', () => {
      
      const fakeEvent = {
        'data': {
          'oldValue': {d: {booleanValue: true}},
          'value': {d: {booleanValue: false}},
          'exists': true
        },
        params: {discussionId: 'test-slug'}
      };
      return assert.eventually.equal(myFunctions.questionCreate(fakeEvent), 'test-slug');
    })
  });
})

**Comment by kpsrinivas** [comment]
This configuration seems to be working. Let me know if there is a better way.

First we do npm install --save-dev @google-cloud/firestore

```
const chai = require('chai');
const assert = chai.assert;

const chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);

// Sinon is a library used for mocking or verifying function calls in JavaScript.
const sinon = require('sinon');


describe('Discussion triggers', () => {
  // [START stubConfig]
  var myFunctions, configStub, adminInitStub, functions, admin, Firestore, firestore;
  const reference = require('@google-cloud/firestore/src/reference')(Firestore);
  const DocumentReference = reference.DocumentReference;
  const DocumentSnapshot = require('@google-cloud/firestore/src/document')(DocumentReference)
    .DocumentSnapshot
  before(() => {
  
    admin =  require('firebase-admin');
    adminInitStub = sinon.stub(admin, 'initializeApp');
    functions = require('firebase-functions');
    process.env.GCLOUD_PROJECT = 'not-a-project';
    configStub = sinon.stub(functions, 'config').returns({
      firebase: {
        databaseURL: 'https://not-a-project.firebaseio.com',
        storageBucket: 'not-a-project.appspot.com'
      }
    });
    Firestore = require('@google-cloud/firestore');
    firestore = new Firestore();
    
    myFunctions = require('../index.js');
    
  });

  after(() => {
    // Restoring our stubs to the original methods.
    configStub.restore();
    adminInitStub.restore();

    delete process.env.GCLOUD_PROJECT;
  });
  // [END stubConfig]

  describe('questionCreate', () => {
    it('should create activity ref', () => {
      const snapshot = new DocumentSnapshot(firestore.doc('discussions/test-sluhg'));

      const fakeEvent = {
        data: snapshot
      };
      return assert.eventually.equal(myFunctions.questionCreate(fakeEvent), 'test-slug');
    })
  });
})
```

**Comment by ajaybeniwal** [comment]
We should ask questions on stackoverflow or google groups this place should be listed more for issues than questions

**Comment by abraham** [comment]
You can't ask for sample code on SO. Your question will get closed.

**Comment by nicolasgarnier** [comment]
Thanks for sharing @kpsrinivas
