### ISSUE TITLE
Is there option to send messages to a topic using cloud function real time database trigger?

### ISSUE THREAD

**Issue by jerinamathews** [firebase/functions-samples#255]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by katowulf** [comment]
No actual content in this issue. Feel free to resubmit with the data filled in : )
