### ISSUE TITLE
Firebase environment

### ISSUE THREAD

**Issue by alexanderkhitev** [firebase/functions-samples#259]
Hi Firebase team! We have two identical projects, one we use to develop the other as production. We use cloud functions. In one of the cloud functions, you need to use service-account-credentials.json to not switch between functions manually, I decided to load all the data from service-account-credentials.json into the firebase environment. Of course, for each soy project, the data. The problem is that when I init google cloud storage (thus), `const gcs = require ('@ google-cloud / storage') ({keyFilename: functions.config (). Serviceaccountcredentials});`
During the execution of the function produces an error **"Path must be a string. Received ".** Tell me how to fix this? Or what approach is better to use for this case?

**Comment by davvit** [comment]
not 100% sure on the error but I think you should be using environment config and switching dev/prod creds based on what you are doing.  https://firebase.google.com/docs/functions/config-env

i would set the right cred before deploying the function as follows using command line
`firebase functions:config:set Serviceaccountcredentials=yourCred`

Then in your  function file do the following before require gcs
```
admin.initializeApp(functions.config().firebase);
const serviceCred= functions.config().Serviceaccountcredentials;

```

**Option2** 
`firebase functions:config:set devSession=true`

and then in your web function
```
admin.initializeApp(functions.config().firebase);
const devS= functions.config().devSession;
```

```
let someOtherCred;
let serviceCred;

if(devS){
   serviceCred = yourdevCred
   someOtherCred ='credDev';
}else{
  serviceCred = yourLiveCred
  someOtherCred ='credLive';
}
```
now you have valid cred always as long as you set the config correctly for that particular firebase app

**OTHER**
If you are trying to make your app dynamically know which config it needs to be using -
everytime your app bootstraps you should make  a web request to a web function on firebase that returns you the config for THAT request url. so once you have the configs you can init firebase on your app using that info.
```
var configURL;
if(env.dev){
    configURL = '"https://us-central1-YOUR_TEST_APP.cloudfunctions.net/getFirebaseConfig";}
else{
    configURL = '"https://us-central1-YOUR_LIVE_APP.cloudfunctions.net/getFirebaseConfig";}
}

         request(configURL, (error: any, response: any, body: any) => {
                    if (error){
                        //do smtn
                        rej(true);
                    }
                    else {
                        //parse the body for config values so your application can use them
                        var config = parseJsonAndGetConfigs(body);
                        res(true);
                    }
                });
```
this is the function on firebase
```
exports.getFirebaseConfig = functions.https.onRequest((req: any, res:any) => {
    return firebaseConfigAPI.getConfig(req,res);
      cors(req, res, () => {
            return res.send(functions.config());
        });
});
```

remember you can set whatever config info you want on each firebase app instance using 
`firebase functions:config:set someKey=someVal`

hope this helps..code is not tested.
