### ISSUE TITLE
Firebase search by child value?

### ISSUE THREAD

**Issue by beratuslu** [firebase/functions-samples#265]
Hello guys,

I am trying to get "pushToken" value by searching child value called "deviceUid". Since my query returning null, I cant send notification to user..

Here is my db and I cant get push token value with following code;

Thank you..
```
  const deviceUID = event.params.deviceUID;
  console.log("deviceUID: ", deviceUID);
  //deviceUID: 1f2d34d

  const getpushTokenPromise = admin.database().ref('/users').child('pushToken').orderByChild('deviceUid').equalTo(deviceUID).once('value');

  getpushTokenPromise.then(pushTokenSnapshot => {
    const token = pushTokenSnapshot.val();
    console.log("token:" ,token);
    //token: null
  });
```
![image](https://user-images.githubusercontent.com/94031/32231580-a1612f4a-be5e-11e7-9299-ded2092b6838.png)

**Comment by davvit** [comment]
here is a quick sample
```
firebase().database().ref('/app-users/users/').orderByChild("email").equalTo('user4@gmail.com').on('value', function (snapshot) {
       //snapshot would have list of NODES that satisfies the condition
	console.log(snapshot.val())
        console.log('-----------');
 
       //go through each item found and print out the emails
       snapshot.forEach(function(childSnapshot) {

       var key = childSnapshot.key;
      var childData = childSnapshot.val();
    
        //this will be the actual email value found
         console.log(childData.email);
  });

});
```

in your case     
 _childData.email_ would be childData.pushToken    
_orderByChild("email")_ would be orderByChild("deviceUid")

![test](https://user-images.githubusercontent.com/4433698/32237549-39e82b96-be33-11e7-967e-a68aa3a09564.png)

**Comment by inlined** [comment]
It looks like @davvit solved your problem before we could get to it. To make sure your query is efficient, also add this to your firebase database rules:

```json
{
  "users": {
    "$userId": {
      ".indexOn": "deviceUid"
    }
  }
}
```

**Comment by alanscarpa** [comment]
Hi @inlined , I'm just wondering what the database rule that you listed does in this situation?

**Comment by inlined** [comment]
It allows you to (efficiently) use orderByChild('deviceUid'). When the Firebase Realtime Database loads your node, it will keep a view of that data in deviceUid order.

Also, if you need complex querying, consider using Cloud Firestore.
