### ISSUE TITLE
Typescript version in samples

### ISSUE THREAD

**Issue by coreywiley** [firebase/functions-samples#270]
Since Typescript is Firebase's suggested language for Functions it would be super helpful to have a Typescript version along side the vanilla JS samples to get the community jumpstarted in that direction.

**Comment by navarrorc** [comment]
Where is this documented? I'm curious. Thanks.

**Comment by coreywiley** [comment]
[Write Production Quality Cloud Functions (Firebase Dev Summit 2017)](https://youtu.be/tResEeK6P5I?t=13m27s)

**Comment by inlined** [comment]
Yesterday we integrated support for TypeScript in `firebase-tools`. Download the latest copy of `firebase-tools` with:

```bash
npm install -g firebase-tools
```

and you can initialize new projects with our recommended TSConfig and TSLint options. `firebase-tools` will also ensure that your code is compiled and free of linter errors (warnings are OK) before deploying. You can see more about TypeScript with Cloud Functions in our [docs](https://firebase.google.com/docs/functions/)
