### ISSUE TITLE
help

### ISSUE THREAD

**Issue by azlie1992** [firebase/functions-samples#284]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by inlined** [comment]
Unfortunately there is nothing in this issue report that we can use to help you. There's no details about what you're struggling with and the link for console logs doesn't even include a project. If this is a general request for help using Cloud Functions, we have a great team that's staffed around the clock to help with these. You can get started [here](https://firebase.google.com/support/contact/troubleshooting/)
