### ISSUE TITLE
There are no Fabric apps linked to this project[Firebase Crashlytics]

### ISSUE THREAD

**Issue by ajaybeniwal** [firebase/functions-samples#291]
### How to reproduce these conditions
Try to deploy Crashlytics cloud functions
**Sample name or URL where you found the bug**
Crashlytics sample
**Failing Function code used (including require/import commands at the top)**
exports.sendOnNewIssue = functions.crashlytics.issue().onNewDetected(event => {
  const data = event.data
  const issueId = data.issueId;
  const issueTitle = data.issueTitle;
  const appName = data.appInfo.appName;
  const appId = data.appInfo.appId;
  const appPlatform = data.appInfo.appPlatform;
  const latestAppVersion = data.appInfo.latestAppVersion;
  const createTime = data.createTime;
  const emailDetails = {
    to: "ajaybeniwal203@gmail.com",
    from: "ECPMobile@crashlytics.com",
    subject: `${appName} on ${appPlatform} has a new issue`,
    html: `<h2>${appName} on ${appPlatform} has a new issue!</h2>
        <p>App Name: ${appName}</p>
        <p>App Id: ${appId}</p>
        <p>Platform: ${appPlatform}</p>
        <p>Version: ${latestAppVersion}</p>
        <p>Issue Id: ${issueId}</p>
        <p>Issue Title: ${issueTitle}</p>
        <p>Creation Time: ${createTime}</p>`
  };

  return sendgridMail.send(emailDetails).then(() => {
    console.log('Successfully sent velocity alert email');
  }).catch(error => {
    console.error(error.toString());
  });
**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

### Expected behavior
I Have project linked in fabric and it is showing in firebase console as well but while deploying functions it is giving the error

**Comment by inlined** [comment]
If you're sure that you're deploying against the right project (you can see this in the output of `firebase use`) and this project does indeed have a Fabric app linked to it, we'll need to do a deeper investigation. Since this conversation would probably include things like your app and project IDs, it's best to use the proper forums for tech support. Can you [file a ticket](https://firebase.google.com/support/contact/troubleshooting/) with Firebase support?
