### ISSUE TITLE
child-count datastructure

### ISSUE THREAD

**Issue by lisztomania1** [firebase/functions-samples#292]
Hello, 
I use the child-count functions sample, its really working stable. But I wonder, if its possible to set the likes_counter into a different location in the JSON tree or copy it everytime it changes? 

Like in the picture below. This might be useful to keep data clean for a transformation to a table later on.
![screenshot from 2017-12-13 09-45-56](https://user-images.githubusercontent.com/34504909/33934021-ed651838-dff7-11e7-9839-4f5216976647.jpg)

Cheers, 
John

**Comment by puf** [comment]
Hey John,

You can keep the count wherever you like. Just update the reference on lines [25](https://github.com/firebase/functions-samples/blob/master/child-count/functions/index.js#L25) and [45](https://github.com/firebase/functions-samples/blob/master/child-count/functions/index.js#L45) to point where you want to keep the counter.

**Comment by lisztomania1** [comment]
Thank you for your help, 
now I have tried for two days to find the right syntax for the update of the reference and I gave up. I am just too stupid to find the syntax for a wildcard path:

exports.countlikechange = functions.database.ref('/Count_it_here/{cityid}/{nameid}/likes/{likeid}').onWrite(event => {
  const collectionRef = event.data.ref.parent;
  const countRef = collectionRef.parent.child('/C_Profiles/{cityid}/{nameid}/likedBy');

I know, I have to search on my own and learn basic knowledge to javascript... but it would be really nice, if you could help me one last time. 

Thanks, 
John

**Comment by puf** [comment]
The way you've now written `'/C_Profiles/{cityid}/{nameid}/likedBy'` it is just a regular string. The `{cityid}` and `{nameid}` in there only have a special meaning the the function declaration.

To create a reference to a path that includes those parameters, either build the path like this:

    const countRef = collectionRef.parent.child('C_Profiles').child(event.params.cityid).child(event.params.nameid).child('likedBy');


Or use the more modern string templates:

    const countRef = collectionRef.parent.child(`/C_Profiles/${event.params.cityid}/${event.params.nameid}/likedBy`);

Note the use of back quotes in there, instead of single quotes, which is how you tell modern JavaScript to expand those `${}` expressions.

**Comment by lisztomania1** [comment]
superb! thank you so much!
