### ISSUE TITLE
Emberfire Applicable Instructions? LinkedIn Auth, others

### ISSUE THREAD

**Issue by brendanoh** [firebase/functions-samples#30]
As a longtime Firebase developer using Emberfire I am beyond excited for Functions.

Are there going to be any Emberfire specific integration examples? @tstirrat @jamesdaniels 

Thanks to everyone involved. This is truly amazing stuff.

Brendan

**Comment by jamesdaniels** [comment]
Hey Brendan, the Functions launch is actually why I've not had a lot of time to dedicate to Emberfire lately, as I'm a DevRel on this project. Glad you're excited :)

I think third party auth w/Emberfire would be a good example, I'll tinker a bit later this week.

**Comment by brendanoh** [comment]
@jamesdaniels I am willing to write up a blog post / video walkthrough on implementing the following in an Ember App.

- [x] Emailing Users w/ Mailgun
- [ ] Create Thumbnails on Image Upload
- [ ] Update Child Count on HasMany updates
- [ ] LinkedIn Auth
- [ ] Instagram Auth 
- [ ] Stripe Processing

**Comment by jwngr** [comment]
Cross-post: https://groups.google.com/forum/#!msg/firebase-talk/s6GWGZTPI0I/CS6I0nxoAwAJ

**Comment by jamesdaniels** [comment]
Yeah child count would be a great ember integration point.

**Comment by jamesdaniels** [comment]
I'm going to close the issue for now but let's keep the conversation going here.
