### ISSUE TITLE
Add typeRoots to tsconfig.

### ISSUE THREAD

**Issue by eduDorus** [firebase/functions-samples#303]
We received errors with this tsconfig.json. In order to make it work as a subdirectory of our Angular app the typeRoots property was necessary.

"typeRoots": [
      "node_modules/@types"
 ],

**Comment by inlined** [comment]
What version of TypeScript are you using? Are you sure you're using the locally-installed version and not a(n outdated) global install of TypeScript? `node_modules/@types` has been supported as a default value for a long time and what you listed is actually _more_ restrictive than the default and could actually break some apps that are written fully in TypeScript.

See the [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) documentation for more info.

**Comment by cdock1029** [comment]
I'm having same issues with a typescript subdirectory inside another typescript repository. 

Compilation seems to attempt to target ancestor directories unrelated to the functions source. 

Adding 
```json
"typeRoots": [
"node_modules/@types"
],
```

fixes this. You can reproduce the error by embedding a cloud functions repo within a larger typescript app. Maybe there's a better way, but the default `tsconfig.json` is not adequate.
