### ISSUE TITLE
Adding cache parameters to images

### ISSUE THREAD

**Issue by nes123** [firebase/functions-samples#304]
how can I add the required fields for an image to be cache-able ? I am referring to the thumbnail generation example

**Comment by nicolasgarnier** [comment]
PS: I added a line you can simply un-comment:

https://github.com/firebase/functions-samples/blob/master/generate-thumbnail/functions/index.js#L70-L71

**Comment by darkylmnx** [comment]
@nicolasgarnier in this example you are adding the cache to the thumbnail but how can this be done only to the newly added image ? (object passed in param) ?

I can't find a way through this except by "re-uploading" the file with new metadas but this would call an infinite loop on this tirigger
