### ISSUE TITLE
Searching by child value in list?

### ISSUE THREAD

**Issue by beratuslu** [firebase/functions-samples#305]
Hello guys,
I am trying to find a child value in array of childs how can I write proper query for this?

Thank you...
![image](https://user-images.githubusercontent.com/94031/34383462-6182e658-eb26-11e7-8f2d-ad6f6f53f6a6.png)

![image](https://user-images.githubusercontent.com/94031/34383322-8f7e512e-eb25-11e7-9aab-fd01af2bed69.png)

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/q/47993534 and seems to be handled there.
