### ISSUE TITLE
Firebase how to know specific client is offline?

### ISSUE THREAD

**Issue by beratuslu** [firebase/functions-samples#311]
Hello,

I am developing a device/product using raspberry pi and Firebase...

System flows like this: user buys device on my website and she can use same credentials to login mobile app.

Currently, I am relying on an some how generated uniuqe id put by me in to device to interact to db from device and device to Firebase Realtime Database...

Now I need to know if device is online or offline. Answers should be on possibble two solutions. Because I want to notify user: "Your device is offline"...

**1- on current code(relying on unique id):** if it's possible, how can I achive this.

**2- changing system in to user based:** if I implement this how I must think system. Device will have no display input nor keyboard. For example what happens when user changed her password?

Thank you..

**Comment by puf** [comment]
Cross-posted on https://stackoverflow.com/questions/48303327/firebase-how-to-know-specific-client-is-offline

**Comment by beratuslu** [comment]
what are your suggestions @puf ?
