### ISSUE TITLE
is it possible to save data_url string image with cloud functions

### ISSUE THREAD

**Issue by BernardMarieOnzo** [firebase/functions-samples#314]
For SSR reasons I ended up using a Cloud Function to upload an Data_url String image into Firebase Storage.
I saved the image in Firebase Database as Data_url String as follows `/posts/mainPosts/{postKey}/images/dataUrl`

So I want to create a Cloud function who:
- Every time when create an `/posts/mainPosts/{postKey}/images/dataUrl` element, the function can recover that value to create an image in Firebase Storage

I tried this
```
exports.createStorage = functions.database.ref('/posts/mainPosts/{postKey}/images/dataUrl').onWrite(event => {
    const onfleck = event.data.val()
    gcs
      .bucket('my-app.appspot.com')
      .upload('postsStorage/-L0cy2Hr2me5xoPn8BoF/onfleck', onfleck)
      .then(() => {
        console.log("uploaded to")
      })
      .catch(err => {
        console.error('ERROR:', err)
      })
  })

```

I got nothing as an answer, not even an error.
I must do otherwise where it is not possible. help me please

**Comment by nicolasgarnier** [comment]
@BernardMarieOnzo Could you please post your issue on StackOverflow instead? We're trying to keep the issues for issues directly related to samples or code in this repo.

Cheers!

**Comment by BernardMarieOnzo** [comment]
OK I have done. It is [here](https://stackoverflow.com/questions/48325161/convert-data-url-string-and-save-as-image-in-firebase-storage-all-that-from-clou)
