### ISSUE TITLE
Google Sheets Sync - Deploy Fails: NPM Dependencies 

### ISSUE THREAD

**Issue by tomtom215** [firebase/functions-samples#318]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
- Google Sheets Sync Function

**Failing Function code used (including require/import commands at the top)**
`+-- UNMET PEER DEPENDENCY firebase-admin@4.2.1
-- firebase-functions@0.8.1'
'npm WARN firebase-functions@0.8.1 requires a peer of firebase-admin@~5.8.1 but none was installed.`

**Steps to set up and reproduce**
- Follow the steps in the guide/readme on Sheets Sync

- Clone the repo and NPM install

**Security rules used**
- Default

### Expected behavior

- run NPM install in the functions directory and then be able to deploy

### Actual behavior

`npm WARN firebase-functions@0.8.1 requires a peer of firebase-admin@~5.8.1 but none was installed.`

- I was able to attempt a deploy with the failed dependency but this is the console logs on the deploy fail 

`Error: Error occurred while parsing your function triggers. TypeError: OAuth2Client is not a constructor at Object`

**Comment by nicolasgarnier** [comment]
Thanks for the report @tomtom215 

We're going to fix all packages.json import version soon. In the mean time you can manually change the following lines in the `functions/package.json` file to make sure you are not getting the warning:

```json
    "firebase-admin": "~5.8.1",
    "firebase-functions": "^0.8.1",
```

**Comment by tomtom215** [comment]
Thanks for the update @nicolasgarnier 

I have cloned the most recent version of this function sample I was faced with some npm dependency versioning with this error - 

` Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.`

This was simple enough to do, but I am still facing this error on deployment - 

`Error: Error occurred while parsing your function triggers.
TypeError: OAuth2Client is not a constructor
    at Object.<anonymous> (C:\Users\***\GitHub\cloudfunctions\google-sheet-sync\functions\index.js:45:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:18:11
    at Object.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:38:3)`

I have only followed the steps in the readme - please advise if this is an error on my end

Thanks!
