### ISSUE TITLE
New sample request: Integrating sms gateway (Twilio) for instant sending SMS

### ISSUE THREAD

**Issue by 6vedant** [firebase/functions-samples#324]
Unable to integrate sms gateway for instant sending sms for order updates.

**Comment by 6vedant** [comment]
Please post a working example to make this happen. I want to use firebase cloud function for integrating sms gateway using node.js.

**Comment by nicolasgarnier** [comment]
Showing an integration with Twilio may be a good idea. I'll get to it when I find some time.

**Comment by jamesdaniels** [comment]
@nicolasgarnier I could take this on, I have a several working Twilio demo apps w/Cloud Functions I could update /  cleanup. Feel free to assign if that makes sense to you.

**Comment by nicolasgarnier** [comment]
Sounds good @jamesdaniels !

**Comment by 6vedant** [comment]
I figured it to integrate sms using twillio. We can do a database trigger and send twillio sms.
