### ISSUE TITLE
generate-thumbnail Google Cloud Storage triggers changed?

### ISSUE THREAD

**Issue by MatteoNY** [firebase/functions-samples#326]
Please provide updated example on new Cloud Storage triggers not clear on what needs to change when the examples have not changed.  Google Email received notified me of changes but not clear if this is only for Google Cloud Storage as well as Firebase storage.  It mentioned if I don't update the Cloud Function, it's beta forever.  The email mentions using " OBJECT_FINALIZE events--when a new file is created". Does this mean the code needs to change, for example, uploadTask.on(firebase.storage.TaskEvent.STATE_CHANGED,... It would be nice if there was a clear example on changing from: i.e, "functions.storage.object().onChange(...) " to new "OBJECT_FINALIZE".  I'm sure there will be tutorials and stuff coming up.  Many thanks.

**Comment by nicolasgarnier** [comment]
The new Cloud Storage object triggers are not yet supported on Cloud Functions for Firebase. Please keep on using the `onChange` trigger for now.

Please follow [the Firebase blog](https://firebase.googleblog.com/) to make sure that you are notified of major new releases.

**Comment by MatteoNY** [comment]
Many thanks!!
