### ISSUE TITLE
Auth Trigger Functions Too Slow To Spin Up / Sometimes Just Fail - onDelete() / onCreate()

### ISSUE THREAD

**Issue by boon4376** [firebase/functions-samples#332]
### How to reproduce these conditions
On less frequently used firebase functions, such as onDelete() (and to some extent, onCreate()), it takes so long for the function to respond, that it times out or creates a terrible user experience. This isn't consistent. Sometimes it takes 5 seconds to respond, sometimes 20, sometimes it fails. 

In my opinion the time it takes for these functions to spin up is an "issue" that should be looked into, because even the documentation example doesn't make sense if there's a relatively high probability of failure in these circumstances. https://firebase.google.com/docs/functions/auth-events

For example, with the onDelete() function, if I go into my Firebase console and delete a user, I get the following log messages:
```
10:15:09.015 AM | outlined_flag | processDeleteUser | Function execution started
10:15:13.843 AM | outlined_flag | processDeleteUser | Function execution took 4828 ms, finished with status: 'connection error'
```
But the next time I use it, if it's within a minute of the last time it was run, it works fine (and promptly).

If the onDelete() triggered function takes too long and fails, any cleanup I need to perform effectively can't run, but it's random and inconsistent...  And I'm left with a mess in my database that needs to be cleaned manually.

**Failing Function code used (including require/import commands at the top)**
```
var admin = require("firebase-admin");
const functions = require("firebase-functions");

const processDeleteUser = functions.auth.user().onDelete((event) => {
    // Get the uid of the deleted user.
    var uid = event.data.uid;

    // Update profile in firestore
    // Create an instance of our firestore
    var db = admin.firestore();

    // Create reference to our new user
    let deletedUserRef = db.collection('users').doc(uid);

    // Update the users profile to indicate that they were deleted
    return deletedUserRef.update({
        deleted: true,
        deletedDate: Date.now()
    })
    .then(() => {
        console.log("User profile updated to mark as deleted.");
        return;
    })
    .catch((err) => {
        console.log("Error updating profile to mark as deleted: ", err);
    })
});
```

When creating a new user, it can take over 30 seconds for the onCreate() function to respond, which in my case, sets up their new profile in firestore. This takes a significant amount of time for the first user after deployment, or for anyone that has created a new account when another has not been created in a few minutes.

I have had to work setTimeout() loops into my code that continue to try and see if these functions have run for up to a minute, waiting for them to respond, and sometimes they just time out. This can be troublesome if I'm walking the newly created user through a multi-step conditional application process that requires a profile to exist, or if the profile needs to exist before the app can function. 
```
const setupNewUser = functions.auth.user().onCreate((event) => {
    // code to setup a new user profile in firestore
});
```

**Security rules used**
None enabled yet, all open for testing

**Is my only solution to create a cron job that pings all of my functions to keep them awake?**

**Comment by prescottprue** [comment]
Not sure, but it could be cold starts getting you (as mentioned [here](https://stackoverflow.com/questions/43637519/why-is-cloud-functions-for-firebase-taking-25-seconds)) - [here are some tips on dropping cold start time](https://firebase.google.com/docs/functions/tips#performance).

**Comment by jamesdaniels** [comment]
Yes, this would be cold starts. The team is working to make these delays shorter in future iterations of the product.

Closing since this is out of scope for this project.
