### ISSUE TITLE
Link a LinkedIn Account

### ISSUE THREAD

**Issue by AntGul** [firebase/functions-samples#334]
Do you know how to link a linkedin account with other accounts?
So do something similar to 
https://firebase.google.com/docs/auth/web/account-linking
but with linkedin

**Comment by mono0926** [comment]
Issue title should be ‘LinkedIn’ instead of ‘Linkeind’.

**Comment by nicolasgarnier** [comment]
I've just discussed this on this thread: https://github.com/firebase/custom-auth-samples/issues/10 Let's use the other thread.
