### ISSUE TITLE
$RESOURCE_DIR ISSUE

### ISSUE THREAD

**Issue by MELAS007** [firebase/functions-samples#335]
I got this errors while running this firebase deploy and can't find any solutions for that .....
Could you tell me how to solve this?

PS D:\EDUMASR\mobile apps\DCM\adminPanel> firebase deploy --only functions

=== Deploying to 'dcmasr-44362'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "$RESOURCE_DIR" "run" "lint"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\EDUMASR\mobile apps\DCM\adminPanel\npm-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code4294963238
PS D:\EDUMASR\mobile apps\DCM\adminPanel> firebase use --add
? Which project do you want to add? dcmasr-44362
? What alias do you want to use for this project? (e.g. staging) dcmasr

Created alias dcmasr for dcmasr-44362.
Now using alias dcmasr (dcmasr-44362)
PS D:\EDUMASR\mobile apps\DCM\adminPanel> cd functions; npm install; cd -
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
cd : Cannot find path 'D:\EDUMASR\mobile apps\DCM\adminPanel\functions\-' because it does not exist.
At line:1 char:28
+ cd functions; npm install; cd -
+                            ~~~~
    + CategoryInfo          : ObjectNotFound: (D:\EDUMASR\mobi...nel\functions\-:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS D:\EDUMASR\mobile apps\DCM\adminPanel\functions> npm install
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
PS D:\EDUMASR\mobile apps\DCM\adminPanel\functions> firebase deploy

=== Deploying to 'dcmasr-44362'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "$RESOURCE_DIR" "run" "lint"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\EDUMASR\mobile apps\DCM\adminPanel\$RESOURCE_DIR\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\EDUMASR\mobile apps\DCM\adminPanel\npm-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code4294963238

**Comment by nicolasgarnier** [comment]
Hey @MELAS007 could you please post your bug in this repository instead please: https://github.com/firebase/firebase-tools ?
It looks like the $RESOURCE_DIR environment variable is not working on windows.

**Comment by CodingDoug** [comment]
This issue is known by the engineering team.  See this for a workaround:

https://stackoverflow.com/questions/48370690/cloud-functions-deploy-error-during-lint-on-windows-enoent-enoent-no-such-fil
