### ISSUE TITLE
Sample request: JAR execution (PDF processing)

### ISSUE THREAD

**Issue by khoinguyen** [firebase/functions-samples#338]
Thank you for the great cloud function!

NodeJS is the great language for serverless functions, I love it and use it for daily development.

However, there is some library that not available in NodeJS yet. 

One of it is PDF processing, my case study is I need to gray out some content in the PDF file, eg: contact information eg: phone, email, address,...

I was used iText PDF library to redact the required information using some sort of regular expression.

Now I want to move my PDF processor to Firebase functions, the simplest solution I can think off is adding Java support in the base image. 

OR a sample for help me on this also great!

**Comment by prescottprue** [comment]
@khoinguyen It may make sense to try to find some libraries for node that handle your use case.

We were able to get some PDF/Image conversion going using ghostscript installed through a git submodule. [Here is a short right up on medium that my coworker did](https://tech.residebrokerage.com/using-firebase-cloud-functions-with-ghostscript-for-pdf-to-image-conversion-f81b248d3b22) on how it was done.

**Comment by khoinguyen** [comment]
@prescottprue thank you for your advice. 

I try your coworker method, and use packr to bundle JRE, so I can have everything required for the JAR to run.

Then I test on the image `launcher.gcr.io/google/nodejs`, with the following Dockerfile
```FROM launcher.gcr.io/google/nodejs

# Copy application code.
COPY . /app/

RUN chmod +x dist/CVProcessor

RUN ./dist/CVProcessor ./original.pdf ./processed.pdf

ENTRYPOINT [ "npm", "start" ]```

But seem like iText required other .so file: 
```./dist/CVProcessor: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./dist/CVProcessor)```

Looks like the base image for cloud functions not have the libstdc++ also, this is OS library, looks like I can't bundle it just like what I did with the JRE.

Any ideas?

**Comment by jhuleatt** [comment]
Regarding other runtimes, [Cloud Run](https://cloud.google.com/run/) lets you deploy and autoscale any Docker container you'd like. It's worth taking a look at if the supported Functions runtimes don't suit your needs.
