### ISSUE TITLE
Stripe integrations error

### ISSUE THREAD

**Issue by iThinkersTeam** [firebase/functions-samples#34]
Hello, I added your stripe function and now try deploy it but I get follow error

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (/private/var/folders/_g/nztkqsvj5tz5_383vbskcrb00000gn/T/fbfn_5850OTn7CdlyTiUL/index.js:24:59)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

I think problem with 
const stripe = require('stripe')(functions.config().stripe.token),
      currency = functions.config().stripe.currency || 'USD';

How can I configure it?
Thanks

**Comment by jamesdaniels** [comment]
You will need to set your stripe token in the functions config. `firebase functions:config:set stripe.token="..."`

I'll be adding a Readme for this function today.

**Comment by kvnapavl** [comment]
Will you please provide more detail on where to place ```firebase functions:config:set stripe.token="..."```?  Can this be added via command line?

Is the functions config either firebase.json or functions/index.js?

**Comment by jamesdaniels** [comment]
Yes, add it through the CLI https://firebase.google.com/docs/functions/config-env

**Comment by kvnapavl** [comment]
Awesome.  Thank you!

**Comment by abramandis** [comment]
Hi, I am also having this issue even AFTER adding the proper code to the CLI, i.e. firebase functions:config:set stripe.token="..."

**Comment by jakeseltz** [comment]
I'm continuing to get functions.config().stripe.token saying token not a variable of undefined

-- could that be related to my node version (Node.js v8.2.1 but Google Cloud Functions only supports v6.11.1)

I can hardcode my Stripe API Secret key directly into the function 

`const stripe = require('stripe')('XXXXcorrectkey')`


If I look at my config, it looks fine - as my secret key is in there when I do the command:

firebase functions:config:get  gives me

{
  "stripe": {
    "token": "XXXXcorrectkey"
  }
}

I'm not sure what the issue is.. or if it really matters.. but I'd prefer the key be in config(). Any hints?

**Comment by inlined** [comment]
My best psychic debugging is that when you ran firebase functions:config:get it was on a test project and the error is coming from your production project (or vice versa).

Also make sure you are using the latest version of `firebase-tools`

**Comment by prakis** [comment]
I changed my nodejs version to old 6.11.5 and I started getting this error. I switched back to new Nodejs nodejs 8.9.1 the problem is fixed. It also works fine with nodejs 6.12.3.

**Comment by AndersonHappens** [comment]
Similar to prakis, I had the same issue but with node 10. Downgrading to node 8 (8.16.0) made it deploy just fine.
