### ISSUE TITLE
how to generate thumbnail from video using this pluggin

### ISSUE THREAD

**Issue by nidhivc** [firebase/functions-samples#352]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by nicolasgarnier** [comment]
To generate a thumbnail of a video on node you can use `ffmpeg` To install ffmpeg see: https://stackoverflow.com/questions/42773497/can-you-call-out-to-ffmpeg-in-a-firebase-cloud-function

To generate Thumbnails see: https://stackoverflow.com/questions/13079742/how-to-generate-video-thumbnail-in-node-js

**Comment by nidhivc** [comment]
Thanks.




 
 Nidhi Parikh
 
Developer
 
  
 Direct: +91-7940031384
 
US: +1-201-203-9313 (TOLL FREE)
 
Email: nidhi.parikh@viitorcloud.in
 
 
 
   
 
 
 
Visit our website : www.ViitorCloud.com
 

 Please consider the environment before printing this email
 
 







---- On Wed, 04 Apr 2018 15:08:15 +0530 Nicolas Garnier &lt;notifications@github.com&gt; wrote ----




Closed #352.
