### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'service-account-credentials.json' at Error (native)

### ISSUE THREAD

**Issue by digitalmkt** [firebase/functions-samples#355]
Hi, I'm new on Firebase and after deploying the generateThumbnail function successfully I uploaded an image to the Firebase Storage (root or in a folder) I got his error:

10:22:05.823 PM generateThumbnail | Function execution took 2545 ms, finished with status: 'error'
10:22:05.808 PM generateThumbnail | Error: ENOENT: no such file or directory, open 'service-account-credentials.json' at Error (native)
10:22:03.280 PM generateThumbnail | Function execution started

Does anyone have any idea on how can I solve this error?

Thanks a lot

Paulo

### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by digitalmkt** [comment]
I deleted and reinstall all npm and firebase functions SDKs and modules and err persists. Thanks.

**Comment by nicolasgarnier** [comment]
Hey @digitalmkt 

Have you added the **service-account-credentials.json** file into your project as instructed in the readme? :)

**Comment by digitalmkt** [comment]
Hi Nicolas, Thanks for your help.
I think so. See attached the screenshot. Maybe it's in wrong place?!?!?!

![screen shot 2018-04-05 at 7 48 55 am](https://user-images.githubusercontent.com/5419202/38364251-d4065e86-38a5-11e8-8ab1-00bce3e2d044.png)

**Comment by nicolasgarnier** [comment]
Yup :) Just rename the file to exactly: `service-account-credentials.json` that should fix it. Let me know!
