### ISSUE TITLE
[Stripe] ¿Not working functions.database?

### ISSUE THREAD

**Issue by albetoetecnia** [firebase/functions-samples#366]
The example is not working for me when deploying createStripeCustomer and cleanupUser are uploaded correctly only if I comment addPaymentSource, createStripeCharge.

Database rules:
```
{
  "rules": {
    "stripe_customers": {
      "$uid": {
        ".read": "$uid === auth.uid",
        "sources": {
          "$chargeId" : {
            ".write": "$uid === auth.uid",
            "token": { ".validate": "newData.isString()" },
            "$other": { ".validate": false }
          }
        },
        "charges": {
          "$sourceId" : {
            ".write": "$uid === auth.uid",
            "source": { ".validate": "newData.isString()" },
            "amount": { ".validate": "newData.isNumber()" },
            "$other": { ".validate": false }
          }
        }
      }
    }
  }
}
```

This is the error when uncomment the method with database reference:

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Unexpected token o in JSON at position 1

Having trouble? Try firebase deploy --help

Any solution for work with the database??

**Comment by albetoetecnia** [comment]
I try with the web example, for work with functions and real-time database, and I can't deploy the project when I add the new function  "makeUppercase". Seems a problem with functions.databasae, because, if I comment a set only the addMessage function all works great.

```
// Take the text parameter passed to this HTTP endpoint and insert it into the
// Realtime Database under the path /messages/:pushId/original
exports.addMessage = functions.https.onRequest((req, res) => {
    // Grab the text parameter.
    const original = req.query.text;
    // Push the new message into the Realtime Database using the Firebase Admin SDK.
    return admin.database().ref('/messages').push({original: original}).then((snapshot) => {
      // Redirect with 303 SEE OTHER to the URL of the pushed object in the Firebase console.
      return res.redirect(303, snapshot.ref);
    });
  });
exports.makeUppercase = functions.database.ref('/messages').onWrite((change, context) => {
  
    //const beforeData = change.before.val(); // data before the write
  //const afterData = change.after.val(); // data after the write
    // Grab the current value of what was written to the Realtime Database.
    const original = event.before.val();
    //console.log('Uppercasing', event.params.pushId, original);
   const uppercase = original.toUpperCase();
    // You must return a Promise when performing asynchronous tasks inside a Functions such as
    // writing to the Firebase Realtime Database.
    // Setting an "uppercase" sibling in the Realtime Database returns a Promise.
    return change.data.ref.parent.child('uppercase').set("uppercase");
  })  
```

**Comment by nicolasgarnier** [comment]
Are you sure you are using the latest version of the Firebase SDK? Tee SDK has changed in a non-backward compatible way with version 1.0.0

Can you try running: `npm install firebase-functions@1.0.0 firebase-admin@5.11.0`

**Comment by albetoetecnia** [comment]
Yes, I think it's a problem with Node installation. 
I have tested the same code with other computer and works fine.
Then I have removed all Node installations and reinstall manually from the web. 
Then I've created a new project and all works fine on my machine at work (iMac).
