### ISSUE TITLE
Function killed. Error: memory limit exceeded

### ISSUE THREAD

**Issue by markgoho** [firebase/functions-samples#37]
Using the Thumbnail quickstart, followed all directions, deployed, enabled billing, etc.

I get this error in the log:
`Function killed. Error: memory limit exceeded`

**Comment by CodingDoug** [comment]
I'm assuming this happened after the image was uploaded.  Could you provide the image that you uploaded that resulted in the error?

**Comment by markgoho** [comment]
Sure, thanks @CodingDoug 

https://drive.google.com/file/d/0B5_bzZljtNgnc3MzeFFkNUVxV1E/view

**Comment by CodingDoug** [comment]
That's a pretty big image!  It's 5472 × 3648, which means 20M pixels.  If that decodes fully to a color depth of 24bits per pixel, that's 60MB in memory.  I believe a function has a default budget of 256MB to work with, including temp disk space that you write to.  All that, plug ImageMagick probably bumps you over that limit.

https://cloud.google.com/functions/pricing

You could:
- Try a smaller image just to see it work
- Allocate more memory to your function via gcloud (https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy)
- Add some logic to ballpark the memory usage for an image so it won't go over

**Comment by markgoho** [comment]
Used a smaller image - worked perfectly! Thanks!

**Comment by markgoho** [comment]
Hey @CodingDoug just out of curiosity, why do we need to enable billing to run this one? Is ImageMagick considered an external API?

**Comment by inlined** [comment]
No. The limitation on "external APIs" is purely about networking. This is a
defense against Cloud Functions being used for malicious/abusive purposes.

**Comment by nicolasgarnier** [comment]
Actually that particular sample doesn't require billing I believe (it's not doing external request nor using billing-only APIs like the Cloud Vision API). We just forgot to remove that line in the instructions from some time during the private alpha where billing was still mandatory.

**Comment by nicolasgarnier** [comment]
Fixed instructions in 85da5df
