### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by albetoetecnia** [firebase/functions-samples#374]
Hi, I have the next problem when deploying the stripe example, I have tried some configuration but didn't work. I think it's a problem whit the iframe created by stripe
Any idea

> Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://rents-app.firebaseapp.com" from accessing a cross-origin frame.
>     at HTMLIFrameElement.<anonymous>

Thanks!

**Comment by jhuleatt** [comment]
Stripe sample has been overhauled in #728
