### ISSUE TITLE
Functions stripe and react

### ISSUE THREAD

**Issue by gilesgerman** [firebase/functions-samples#382]
I am really interested in putting a tract front end on this function stripe code or firestripe. Is this something that someone could halo with. 

### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by jhuleatt** [comment]
Since this repo is intended to demonstrate the Cloud Functions for Firebase side of things with minimal browser-side stuff, I'm going to close out this request. Stripe+React docs can be found [here](https://stripe.com/docs/recipes/elements-react)
