### ISSUE TITLE
Call Realtime Database Function From App

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#393]
Hi, 

How do you call Realtime Database Function in node.js from App like you do with HTTPS. 

https://firebase.google.com/docs/functions/callable.

If not, is there anyway to call your  Realtime Database Functions from your android App like 

https://stackoverflow.com/questions/42872743/calling-a-cloud-function-from-android-through-firebase

Or, what it is the way around it.

Thanks

**Comment by puntiz** [comment]
the way i have implemented it is by writing to a specific database node that the specific function you want to run listens to. When i need to trigger a node.js function i write a specific piece of data to that node and have the node function run bases data written. 

Not sure if its the best or the recommended way but it's worked for me fine

**Comment by fxo140130** [comment]
@puntiz, 

Can you give me an example of how you did it ?

Thanks

**Comment by samtstern** [comment]
This is a very old issue so going to close it.

In response to the original question: no, there is no way to make a realtime database function into a "Callable Function".

However as @puntiz said you can simulate this by:

  * Creating a node in your RTDB called `requests` or similar
  * Write to that node
  * The cloud function triggers, and puts the response a node called `responses` or similar
  * The client app waits for the write to `responses` and then continues

Hope that makes sense!
