### ISSUE TITLE
FirebaseAuthError : Error not handled for email address is already in use by another account

### ISSUE THREAD

**Issue by gowrav** [firebase/functions-samples#40]
2:55:24.027 pm
	warning 	
oAuth_linkedin_token
	
Error: The email address is already in use by another account. at FirebaseAuthError.Error (native) at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:25:28) at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:90:23) at Function.FirebaseAuthError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:114:16) at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:350:45 at process._tickDomainCallback (internal/process/next_tick.js:129:7)
	
2:55:24.024 pm
	warning 	
oAuth_linkedin_token
	
Unhandled rejection

**Comment by nicolasgarnier** [comment]
That's right, the sample is not meant to be used with multi-auth providers as we don't handle merging accounts which is kind of complicated in itself.

However we could do a better job of surfacing the error to the client page so that you can handle the flow from the client. I'll get t work on that.

**Comment by gowrav** [comment]
Cool.., thanks for the update.

**Comment by fearonf** [comment]
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=****** 400 () 

Should I get this posting failure before the message:  'The email address is already in use by another account.'    is returned? 
When the error is 'The email address is badly formatted.' , I just get the message itself.   Thanks,

**Comment by nicolasgarnier** [comment]
@fearonf could you please start  anew issue for this? With more details on how to reproduce etc...

**Comment by popchieh** [comment]
same problem here?
I can't use the same email to signup which is registered by facebook before.

iOS
`Error Domain=FIRAuthErrorDomain Code=17009 "The password is invalid or the user does not have a password." UserInfo={NSLocalizedDescription=The password is invalid or the user does not have a password., error_name=ERROR_WRONG_PASSWORD}`

Android
http://imgur.com/a/ZH0tj

**Comment by samtstern** [comment]
This is a very old issue and it looks like @nicolasgarnier has already partially addressed it as much as possible, so closing.

If anyone else wants to discuss this we can open a new issue.

**Comment by joaocamargo** [comment]
there is anything new on it? 

Trying to discover how to register a password for a user that has already logged in using Facebook or google...
