### ISSUE TITLE
Potential infinite loop in moderation example?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [firebase/functions-samples#406]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
https://github.com/firebase/functions-samples/tree/master/moderate-images and https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js

**Failing Function code used (including require/import commands at the top)**

See https://github.com/firebase/functions-samples/tree/master/moderate-images and https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js, specifically `blurImage`.  The issue is that if an image is uploaded, that triggers `onFinalize`, which might upload a new blurred image if safeSearchDetection detects an offensive image.  If that blurred image for whatever reason triggers a safesearch violation, then a blurred version of the blurred image would be upload, potentially meaning an infinite sequence of blurs of blurs of blurs being uploaded, thereby exhausting our function quota and potentially costing us infinite (or very large amounts of $$$).  How should we prevent this?

Granted, it's maybe not likely that a blurred image would also be flagged as offensive by safesearch, but it's not impossible, so ...

**Steps to set up and reproduce**

Read the code at https://github.com/firebase/functions-samples/tree/master/moderate-images and https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js.

**Sample data pasted or attached as JSON (not an image)**

See  https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

See https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js

**Screenshots**

See https://github.com/firebase/functions-samples/blob/master/moderate-images/functions/index.js

### Expected behavior

Google sample code should NOT allow potentially infinite loops of function calls that exhaust function quota and user budgets and cost us $$$.

### Actual behavior

Google sample code DOES allow potentially infinite loops of function calls that exhaust function quota and user budgets and cost us $$$.

**Comment by nicolasgarnier** [comment]
Normally a blurred image should not be detected as inappropriate but if it is then blurring it again would be an appropriate behavior, (it would blur it more :).  at least in practice it works, even though theoretically you need to trust both the blurring step and the inappropriate detection step.
