### ISSUE TITLE
Unable to deploy functions

### ISSUE THREAD

**Issue by clement89** [firebase/functions-samples#407]
My deployments of Google Cloud Functions have been failing with the error

[2018-05-22T18:18:28.504Z] <<< HTTP RESPONSE BODY {
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "status": "UNAVAILABLE"
  }
}

my node version - v8.9.3
npm version - 5.5.1
firebase-functions@1.0.3
firebase-tools@3.18.5

**Comment by nicolasgarnier** [comment]
It looks like there is an ongoing issue. Sorry about that! Please follow this for status: https://cloud-status.googleplex.com/firebase/incident/Functions/18028

**Comment by clement89** [comment]
I am not able to login to [ https://cloud-status.googleplex.com/firebase/incident/Functions/18028](url)

My old project is working fine, I can successfully deploy functions. the problem is with new one. there is no error in the function, here is my function 

`
const functions = require('firebase-functions');
exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});
`
and I'm getting this error ...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (38.68 KB) for uploading

Error: An unexpected error has occurred.

**Comment by clement89** [comment]
the issue is fixed now.

**Comment by nicolasgarnier** [comment]
Sorry about that @clement89 I posted an incorrect link. The correct one was: https://status.firebase.google.com/incident/Functions/18028 In general you can always check if there is an ongoing issue on https://status.firebase.google.com in case you run into any strange issues.

**Comment by clement89** [comment]
Thank you.
