### ISSUE TITLE
firebase functions:shell slow

### ISSUE THREAD

**Issue by g4laura** [firebase/functions-samples#408]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

firebase functions:shell is very slow since updating

**Steps to set up and reproduce**

since updating to the latest version of firebase-functions, firebase functions:shell has become very slow. I try to start the sheland then check back 10-20 minutes later and the shell is finally ready. I'm not sure why it slowed down, it used to be very quick.

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

### Expected behavior

Shell takes a minute to start running.

### Actual behavior

Shell taking over 10 minutes.

**Comment by prescottprue** [comment]
@g4laura I have also noticed this in recent versions. Some of my projects it is even worse, and it does not begin emulating functions for closer to 20 minutes.

**Comment by CodingDoug** [comment]
If you're seeing slowness, could you also include information about your computer?  OS, amount of memory, number and class of CPUs, type of disk storage.  Also, the version and distribution of node.  The more information the better.

**Comment by g4laura** [comment]
It actually started working quickly again so, I'll close this issue.

  Model Name:	MacBook Pro
  OS: macOS High Sierra Version 10.13.4
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB

Node version, the highest that firebase functions supports
