### ISSUE TITLE
Please help understand and solving this Error

### ISSUE THREAD

**Issue by HimadeepGuduru** [firebase/functions-samples#411]
TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (D:\Desktop\firebaseExample\functions\index.js:17:59)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\Himadeep\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:21:11
    at Object.<anonymous> (C:\Users\Himadeep\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:61:3)

My package.js

  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "@google-cloud/logging": "^1.2.0",
    "firebase-admin": "~5.12.1",
    "firebase-functions": "^1.0.3",
    "stripe": "^6.0.0"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0"
  },
  "private": true

### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by lllelll** [comment]
hi,
In your **Firebase console -> Functions -> Logs**
You may see such an error

> /user_code/node_modules/simple-oauth2/lib/client/auth-code.js:45
>   async function getToken(params) {
>         ^^^^^^^^
> 
> SyntaxError: Unexpected token function

This happens because

> Cloud Functions runs Node v6.14.0, so we recommend that you develop locally with this version.

[firebase.google.com/docs/functions/get-started](https://firebase.google.com/docs/functions/get-started?authuser=0#build_the_sample_in_your_firebase_project)

Node v6.14.0 doesnt support aync, await.

To resolve this problem, you can try to use babel
[The first example which i found](https://codeburst.io/es6-in-cloud-functions-for-firebase-959b35e31cb0)

**Comment by samtstern** [comment]
Thanks @lllelll for helping out.

Functions now supports Node 8 as a runtime, so this should be fixed either way.
