### ISSUE TITLE
Is Google Auth a requirement?

### ISSUE THREAD

**Issue by taykcrane** [firebase/functions-samples#415]
Hi - quick question. The instructions say "Enable Google sign on your Firebase project". It's very unclear whether you mean that specifically users must only be able to sign into my app with Google, or whether they must sign into my app using any of the Firebase Auth providers (Google, Facebook, Password, etc.)

I'm hoping the latter. It would be a shame if I cannot use Cloud Functions because my app allows users to sign up with a password.

**Comment by CodingDoug** [comment]
Which sample are you talking about?

**Comment by taykcrane** [comment]
@CodingDoug Sorry, forgot to specify. Stripe: https://github.com/firebase/functions-samples/tree/master/stripe

Take a look at the Deploy and Test section for the instructions I'm concerned about.

**Comment by CodingDoug** [comment]
The instructions there are just to get the sample up an running.  Look at the client script - it is just using Google Auth for simplicity.  You can use whatever auth you want in your own project.

**Comment by taykcrane** [comment]
OK appreciate the reply. Closing this.
