### ISSUE TITLE
How to generate thumbnails in its own directory

### ISSUE THREAD

**Issue by MurhafSousli** [firebase/functions-samples#417]
Hi, I tried to put the thumbnail in a sub directory called `thumbs`

[generate-thumbnail.js](https://github.com/firebase/functions-samples/blob/master/generate-thumbnail/functions/index.js)

```js
// Thumbnail directory.
const THUMB_DIR = 'thumbs';
// Thumbnail prefix added to file names.
const THUMB_PREFIX = 'thumb_';
.
.
.

exports.generateThumbnail = functions.storage.object().onFinalize((object) => {
  .
  .
  const thumbFilePath = path.normalize(path.join(fileDir, THUMB_DIR, `${THUMB_PREFIX}${fileName}`));
  .
}
```
### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

```
ChildProcessError: `convert /tmp/images/1528737216744_Background.jpg -thumbnail 80x80> /tmp/images/thumbs/thumb_1528737216744_Background.jpg` failed with code 1
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8130692/41246904-1735faec-6db5-11e8-8bdc-2ad8c3f1a3df.png)

### Expected behavior

To be able to put thumbnails in its own directory

### Actual behavior

Original images are mixed with their thumbnails

**Comment by saarthaksharma** [comment]
+1

**Comment by nicolasgarnier** [comment]
TO change the upload directory just change L.85:

```js
    return bucket.upload(tempLocalThumbFile, {destination: thumbFilePath, metadata: metadata});
```

You need to change `thumbFilePath` at this point.
Don't change this before L.84 Right now you're trying to write a file to the filesystem to a directory that does not exist and I think that may be what's failing.

**Comment by marciobera** [comment]
I was with a similar problem. I was able to solve it when I set the same `/tmp` directory to the thumb.
So, both paths was `/tmp/2312312312.jpg` and `/tmp/thumb_2312312312.jpg`.

**Comment by samtstern** [comment]
I think @nicolasgarnier and @marciobera have answered this issue, and it's been a while since another response.  Closing.
