### ISSUE TITLE
Cannot mock a DeltaSnapshot either.

### ISSUE THREAD

**Issue by s2young** [firebase/functions-samples#42]
I'm trying to write a unit test that calls a realtime db trigger.  No matter what I pass in as my 'data' in the fakeEvent object, I'm getting the following error:

TypeError: Cannot read property 'match' of undefined
    at resourceToPath (/Users/stuart/Development/apps/app-server/functions/node_modules/firebase-functions/lib/providers/database.js:109:25)
    at dataConstructor (/Users/stuart/Development/apps/app-server/functions/node_modules/firebase-functions/lib/providers/database.js:85:117)
    at /Users/stuart/Development/apps/app-server/functions/node_modules/firebase-functions/lib/cloud-functions.js:33:31
    at process._tickCallback (internal/process/next_tick.js:103:7)

My Code:

`
const fakeEvent = {data: new functions.database.DeltaSnapshot(null, null, myData, null, myPath)};
myFunctions.userChange(fakeEvent).....;

`

**Comment by s2young** [comment]
Tracing this through, it appears to fail here:
https://github.com/firebase/firebase-functions/blob/master/src/providers/database.ts#L112

Where nothing is passed into the 'resourceToPath' function.

**Comment by s2young** [comment]
And to be clear, I'm trying to mock a data removal.  I've tried passing many different strings into the 'path' parameter (though it's marked as optional in the function signature).

**Comment by laurenzlong** [comment]
Have you required lodash as a dependency for your functions? If so, what does your package.json look like?

Also, can you print out the result of these commands?

```js
fakeEvent.data instanceof functions.database.DeltaSnapshot
_.deepClone(fakeEvent).data instanceof functions.database.DeltaSnapshot
```

**Comment by s2young** [comment]
I added lodash, with no change in result.  The functions return true, true.

I REALLY appreciate your help!

**Comment by s2young** [comment]
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "async": "^2.1.4",
    "firebase": "^3.7.1",
    "firebase-admin": "^4.1.3",
    "firebase-functions": "^0.5.2",
    "lodash": "^4.17.4",
    "validator": "^7.0.0"
  },
  "private": true
}

**Comment by laurenzlong** [comment]
Everything appears to be right. That's really strange you're still getting that error. 

Did you call myFunctions.userChange anywhere else in your test code? Or do you call userChange anywhere else in index.js?

**Comment by laurenzlong** [comment]
Also, just to clarify, a lodash dependency is not actually needed. Since firebase-functions already depends on it so it gets automatically installed. I was just ensuring that you did not have a conflicting dependency on lodash that was another version. So you can now remove lodash from package.json if you'd like.

**Comment by s2young** [comment]
userChange is only called once in my test. And only once in userChange. Thanks

**Comment by laurenzlong** [comment]
"And only once in userChange. " - do you mean that your userChange function recursively calls itself?

**Comment by s2young** [comment]
No it's not recursive. I was probably half-asleep when typing that!

**Comment by laurenzlong** [comment]
Haha, no probs. Thanks for the clarification! Can you try updating your SDK to the newest version and see if the problem is still there? (v.0.5.4)
