### ISSUE TITLE
Emulator crashed. when try to run "firebase serve" on a function

### ISSUE THREAD

**Issue by KendoJaaa** [firebase/functions-samples#421]
### How to reproduce these conditions

this is my environment
- node version 6.11.1
- firebase-tools version 3.18.6
- firebase-functions ^1.0.4

to reproduce just run
firebase serve --only functions 

### Debug output

[debug] [2018-06-17T15:25:27.514Z] Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:650:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

### Expected behavior

can run the function locally

### Actual behavior

i  functions: Preparing to emulate functions.
Node.js v6.11.5 or greater is required to run the Emulator!
⚠  functions: Error from emulator. Error: Emulator crashed! Check the log file...

**Comment by abraham** [comment]
You are running Node `6.11.1` and the error does say that `6.11.5` or greater is required. Try updating the the latest v6.

**Comment by KendoJaaa** [comment]
oh my god.  this is so hilarious. I'm sure I saw the different suggestion. thx I'll try upgrading
