### ISSUE TITLE
Update FCM sample to use the new messaging API

### ISSUE THREAD

**Issue by hiranya911** [firebase/functions-samples#439]
The example in https://github.com/firebase/functions-samples/blob/master/fcm-notifications/functions/index.js is using the FCM legacy API in Admin SDK( `messaging.sendToDecide()`). This should be updated to use the new `messaging.send()` API.

**Comment by nicolasgarnier** [comment]
The new FCM API does not support multicast (i.e. sending to multiple tokens at the same time) so I've not been able to update it yet. I will when it's available :)
