### ISSUE TITLE
authorized-https-endpoint doesn't work out of the box locally on OSX

### ISSUE THREAD

**Issue by mastoj** [firebase/functions-samples#440]
I'm working on some fable bindings for firebase and sort of copied the authorized-https-endpoint project to test out authorization, and in that process I think I found a bug in this sample. It seems like the `helloUser` url as is set here: https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint/public/main.js#L28 doesn't seem to work locally on OSX, and I don't think it works in production either.

### How to reproduce these conditions

It should just be to run the sample locally and it should fail.

### Expected behavior

Expected to get a hello response back

### Actual behavior

On OSX the functions gets mapped to port 5001, and in my project on firebase the hosting and functions have completely different urls as default.

**Comment by nicolasgarnier** [comment]
@mastoj I remember there was some problem with this sample which I have fixed int he `Node8` branch. Can you look at that branch and see if there is still an issue? 

PS: I made the  Node8 branch the default branch since the master branch is a bit outdated now.

**Comment by mastoj** [comment]
Sure. I’ll have a look in due time.

**Comment by andermoran** [comment]
Still doesn't work locally. I have to deploy to firebase with `firebase deploy` for the application to work properly. I can't do `firebase serve`. If I run it locally, I get this message after authenticating
![error message](https://user-images.githubusercontent.com/15237301/69075902-f4642f80-09f7-11ea-9eec-cc9e7a267414.png)
