### ISSUE TITLE
google-sheet-sync can't deploy

### ISSUE THREAD

**Issue by christianjkarlsson** [firebase/functions-samples#458]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
https://github.com/firebase/functions-samples/tree/Node-8/google-sheet-sync

**Failing Function code used (including require/import commands at the top)**

// Sample trigger function that copies new Firebase data to a Google Sheet

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const {OAuth2Client} = require('google-auth-library');
const {google} = require('googleapis');

// TODO: Use firebase functions:config:set to configure your googleapi object:
// googleapi.client_id = Google API client ID,
// googleapi.client_secret = client secret, and
// googleapi.sheet_id = Google Sheet id (long string in middle of sheet URL)
const CONFIG_CLIENT_ID = functions.config().googleapi.client_id;
const CONFIG_CLIENT_SECRET = functions.config().googleapi.client_secret;
const CONFIG_SHEET_ID = functions.config().googleapi.sheet_id;

// TODO: Use firebase functions:config:set to configure your watchedpaths object:
// watchedpaths.data_path = Firebase path for data to be synced to Google Sheet
const CONFIG_DATA_PATH = functions.config().watchedpaths.data_path;

// setup for authGoogleAPI
const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];
const functionsOauthClient = new OAuth2Client(CONFIG_CLIENT_ID, CONFIG_CLIENT_SECRET,
  FUNCTIONS_REDIRECT);

// OAuth token cached locally.
let oauthTokens = null;

// visit the URL for this Function to request tokens
exports.authgoogleapi = functions.https.onRequest((req, res) => {
  res.set('Cache-Control', 'private, max-age=0, s-maxage=0');
  res.redirect(functionsOauthClient.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
    prompt: 'consent',
  }));
});

// setup for OauthCallback
const DB_TOKEN_PATH = '/api_tokens';

// after you grant access, you will be redirected to the URL for this Function
// this Function stores the tokens to your Firebase database
**(Error in Line 64 index.js) exports.oauthcallback = functions.https.onRequest(async (req, res) => {**
  res.set('Cache-Control', 'private, max-age=0, s-maxage=0');
  const code = req.query.code;
  try {
    const tokens = await functionsOauthClient.getToken(code);
    // Now tokens contains an access_token and an optional refresh_token. Save them.
    await admin.database().ref(DB_TOKEN_PATH).set(tokens);
    return res.status(200).send('App successfully configured with new Credentials. '
        + 'You can now close this page.');
  } catch (error) {
    return res.status(400).send(error);
  }
});

Error in console: C:\Users\user\src\functions-samples\google-sheet-sync\functions\index.js:64
exports.oauthcallback = functions.https.onRequest(async (req, res) => {
                                                        ^SyntaxError: Unexpected token (

**Steps to set up and reproduce**
Followed guide in readme.me
node v6.12.3
npm v5.5.1
firebase v4.2.1

**Sample data pasted or attached as JSON (not an image)**

firebase.json

{
  "functions": {
    "source": "functions"
  },
  "hosting": {
    "rewrites": [
      {
        "source": "/oauthcallback",
        "function": "oauthcallback"
      },
      {
        "source": "/authgoogleapi",
        "function": "authgoogleapi"
      },
      {
        "source": "/testsheetwrite",
        "function": "testsheetwrite"
      }
    ]
  }
}

**Security rules used**
{
  "rules": {
    ".read": true,
    ".write": true
  }
}

### Debug output

**Errors in the console logs, none**

**Screenshots**

### Expected behavior
Should be able to deploy project

### Actual behavior
Fails/crashes on firebase deploy/firebase deploy --only functions

**Comment by fredrikj83** [comment]
You are probably on the wrong branch. The pasted code seems to originate from branch "Node-8". And `async` isn't supported in node v6, which is by default running in Firebase as of today.

**Comment by nicolasgarnier** [comment]
The sample should deploy on a Node8 instance automatically since it is specified in the package.json file: https://github.com/firebase/functions-samples/blob/Node-8/google-sheet-sync/functions/package.json#L22-L24

@christianjkarlsson it simply looks like your issue is that you are running Node6 on your system. Please Switch to Node8.

If you prefer to stick to Node6 you can switch to the master branch, but please be aware that we're not going to maintain these samples anymore.
