### ISSUE TITLE
Preparing API for stripe 

### ISSUE THREAD

**Issue by muqbilk** [firebase/functions-samples#459]
What am I trying to do?
I want to use Apple pay with stripe firebase-cloud function to charge the users, while reading the stripe documentation but I noticed that you need to "Prepare your API" https://stripe.com/docs/mobile/ios/standard

What is my question?
In stripe documents it's mentioned that I need to " Prepare my API" (https://stripe.com/docs/mobile/ios/standard) , so if I'm using the firebase stripe cloud function am I still supposed to do this step? If yes how? 

Thank you

**Comment by jhuleatt** [comment]
I did a quick search in that doc for "Prepare" and "Preparing" but didn't find anything. Seems like things may have changes on the Strip docs. Is it all right if I close this?

**Comment by jhuleatt** [comment]
Closing this out
