### ISSUE TITLE
parse cloud pub sub 

### ISSUE THREAD

**Issue by itumeleng-Comfy** [firebase/functions-samples#482]
Please tell me how I can **simply** get to the base64 data if this below is the message I get? 

Message:  { eventId: '185692463976905',
  timestamp: '2018-09-22T14:06:13.608Z',
  eventType: 'providers/cloud.pubsub/eventTypes/topic.publish',
  resource: 'projects/test/topics/hubs',
  data: 
   Message {
     data: 'eyJ1aWQiOiJ1aWhzaWR1aHMiLCJkZXZpY2VJRCI6InRlc3QtZGV2aWNlIn0=',
     attributes: {},
     _json: undefined },
  params: {} }

**Comment by nicolasgarnier** [comment]
If your message above is in the object `message`, this should work:

```js
var data = message.data; // This is base64 encoded
var decodedData = new Buffer(data, 'base64').toString('ascii'); // This is now decoded Text. it is a JSON object: {"uid":"uihsiduhs","deviceID":"test-device"}
var objectData = JSON.parse(decodedData); // Now you have a JS Object and can access the properties
var uid = objectData.uid
var deviceId = objectData.deviceID
```

**Comment by itumeleng-Comfy** [comment]
`var data = message.data;`

gives you this, not the base64 data

Message {
  data: 'eyJ1aWQiOiJ1aWhzaWR1aHMiLCJkZXZpY2VJRCI6InRlc3QtZGV2aWNlIn0=',
  attributes: {},
  _json: undefined }

**Comment by nicolasgarnier** [comment]
Then replace `var data = message.data;` with `var data = message.data.data;`

**Comment by itumeleng-Comfy** [comment]
Was this by design?
