### ISSUE TITLE
Stripe firebase

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#49]
I was able to implement everything you provide in readme to integrate firebase with stripe. But, when I create a new user in firebase after i deploy the stripe from firebase cli, i cannot see the account in Stripe. I tried everything, deploy with test key, secret key, publishable key, I was unable to see my new account created in stripe sdk. 
Please help.

**Comment by katowulf** [comment]
We won't be much help here without a minimal repro of the problem and some error logs. Most likely, you'll also see some useful error output [in your console](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG).

**Comment by WikipediaBrown** [comment]
Also, this might help: https://github.com/WikipediaBrown/GCF-Stripe-Functions <https://github.com/WikipediaBrown/GCF-Stripe-Functions>

-Perris Davis(I’m that WikipediaBrown dude...)

**Comment by fxo140130** [comment]
@katowulf my log is empty. No error. In my firebase hosting folder, I can see the instances I deploy which mean, that a hosting was created with my Stripe secret key. But somehow , Stripe won't accept my created new user. Any advice ?
Below is the confirmation that the deploy was succesfull. 

![image](https://cloud.githubusercontent.com/assets/25092371/23965136/013e01fc-0985-11e7-98f5-8396bce55141.png)

**Comment by nicolasgarnier** [comment]
Looks like the same issue as #50: the functions are not actually deployed. You can check in the Functions section of the Firebase Console for instance if any functions was deployed on your Firebase project but from the logs above something went wrong. You should see something like this:

![image](https://cloud.githubusercontent.com/assets/3766663/23969952/8c2e6e8a-09c8-11e7-99f2-8f7e62d24ba5.png)

**Comment by nicolasgarnier** [comment]
Same questions as #50:

Can you check that `firebase version` returns `3.5.0`?
Did you just download a fresh version of the [stripe sample](https://github.com/firebase/functions-samples/tree/master/stripe)? Did you modify anything?

**Comment by fxo140130** [comment]
@nicolasgarnier after spending 8 hour on my computer I finally set things up.  But I am having error in my logs to reach stripe. Please help me.

![image](https://cloud.githubusercontent.com/assets/25092371/23972706/d045408a-09a0-11e7-8dc8-5baba28023f7.png)

**Comment by fxo140130** [comment]
@nicolasgarnier 
the log in detail 

![image](https://cloud.githubusercontent.com/assets/25092371/23972754/0dfed080-09a1-11e7-9d5e-c472a6b1e461.png)

**Comment by jamesdaniels** [comment]
Note the log item immediately below. External network requests are blocked on the free tier. You'll want to upgrade to the [Blaze (pay as you go) plan](https://firebase.google.com/pricing/) which includes a [free tier for Functions](https://firebase.google.com/pricing#fb-footnote).

**Comment by WikipediaBrown** [comment]
If you’re using the free tier, you can only make requests out to google owned services. Are you on the free plan?

-Perris Davis
