### ISSUE TITLE
Firebase: How to create an ID field with the same key?

### ISSUE THREAD

**Issue by dzucchi** [firebase/functions-samples#498]
Hello,

I would like to have a field called ID with the same value as the key, how could I do this?

![image](https://user-images.githubusercontent.com/44011810/47251311-92f31b00-d409-11e8-8878-a6e7b2fe9e1b.png)

my react-native code:
![image](https://user-images.githubusercontent.com/44011810/47251277-c1bcc180-d408-11e8-9c0f-3aa11d667e38.png)

**Comment by nicolasgarnier** [comment]
@dzucchi 

You can get the key of the pushed item before it is actually written using `.push()` (passing no object):

```
const snap = db.ref(`/users/${currentUser.uid}/series`).push();
const key = snap.key;
serie.id = key;
await snap.ref.set(serie);
```

**Comment by dzucchi** [comment]
> @dzucchi
> 
> You can get the key of the pushed item before it is actually written using `.push()` (passing no object):
> 
> ```
> const snap = db.ref(`/users/${currentUser.uid}/series`).push();
> const key = snap.key;
> serie.id = key;
> await snap.ref.set(serie);
> ```

Thankss.
