### ISSUE TITLE
Stripe deploy error

### ISSUE THREAD

**Issue by iThinkersTeam** [firebase/functions-samples#50]
Hello,

When I deployed I got error.
Error: Error parsing triggers: Cannot find module '@google-cloud/logging'

I used npm install --save @google-cloud/logging after that I made same with 
I used npm install --save stripe 
And deployed was success. 

When I checked log I get some erorrs
1:43:57.521 ПП
outlined_flag	
cleanupUser
Code in file index.js can't be loaded. Did you list all required modules in the package.json dependencies? Detailed stack trace: Error: Cannot find module '@google-cloud/logging' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/user_code/index.js:20:49) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3)
 Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@google-cloud/logging'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:20:49)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Do you have any suggestion?

**Comment by nicolasgarnier** [comment]
Didi you do `npm install --save @google-cloud/logging` from the functions directory? Basically you need a package.json file inside your functions directory and that should be it. IF that's what you did can you paste here the content of your package.json ?

**Comment by iThinkersTeam** [comment]
Thanks for answer

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "@google-cloud/logging": "^0.8.0",
    "firebase-admin": "^4.1.2",
    "firebase-functions": "^0.5",
    "google-cloud": "^0.48.0",
    "stripe": "^4.15.1"
  },
  "private": true
}

I checked @google-cloud/logging and it is

**Comment by iThinkersTeam** [comment]
{
  "_args": [
    [
      {
        "raw": "@google-cloud/logging",
        "scope": "@google-cloud",
        "escapedName": "@google-cloud%2flogging",
        "name": "@google-cloud/logging",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "/Users/alex/Desktop/Developer/Work/Covet/covet/functions"
    ]
  ],
  "_from": "@google-cloud/logging@latest",
  "_id": "@google-cloud/logging@0.8.0",
  "_inCache": true,
  "_location": "/@google-cloud/logging",
  "_nodeVersion": "7.6.0",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/logging-0.8.0.tgz_1489524423597_0.2694959039799869"
  },
this package @google-cloud/logging

**Comment by nicolasgarnier** [comment]
When did you get the error? When you did "firebase deploy" ? or when you tried to run your function after the deploy?

**Comment by iThinkersTeam** [comment]
when I deployed I haven't error. When I go to the firebase log I found this error.

**Comment by nicolasgarnier** [comment]
Very strange indeed, especially because we run your code locally when deploying the Functions.

Can you look at your deployed code? It is located in your staging bucket. Open this page to see your buckets: https://console.cloud.google.com/storage/browser?project=_

then look at the bucket named `staging.<project-id>.appspot.com` it contains a `firebase-functions-source` file which is a zip file. Download it and de-compress it, then hav a look inside it should have these files:

![image](https://cloud.githubusercontent.com/assets/3766663/23951168/ad148e30-098d-11e7-835a-5ebdba79660d.png)

Please check the `package.json` lookss OK and lists all the dependencies.

**Comment by iThinkersTeam** [comment]
thanks for your answers

{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "firebase-admin": "^4.1.2",
    "firebase-functions": "^0.5",
    "google-cloud": "^0.48.0"
  },
  "private": true
}

It is so strange. Or it is ok?

**Comment by nicolasgarnier** [comment]
Strange because it's not the same one as the one you provided in comment 3. It's missing a two dependencies. can you re-deploy and check again? :)

**Comment by iThinkersTeam** [comment]
so I tried to re-deploy but nothing changing. After than I delete folder staging.<project-id>.appspot.com, delete folder functions in my project. Using readme I tried to do all steps.
after deploy I get message 
=== Deploying to 'covet-aca4f'...

i  deploying database, functions, hosting
✔  database: rules ready to deploy.
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  hosting: preparing public directory for upload...
✔  hosting: public folder uploaded successfully
✔  hosting: 1 files uploaded successfully
i  starting release process (may take several minutes)...

✔  Deploy complete!

I go to project and check log but there no changing. When I opened https://console.cloud.google.com/storage/browser?project=_ the folder staging didn't created.

Do you have any idea why? Which is my next steps?

Thanks a lot

**Comment by nicolasgarnier** [comment]
In this last log it looks like there is no Functions being deployed. Can you check that `firebase version` returns `3.5.0`?

**Comment by nicolasgarnier** [comment]
Also did you just download a fresh version of the stripe sample? Or did you modify anything?

**Comment by iThinkersTeam** [comment]
thanks a lot I forget copy index.js file.

**Comment by badarshahzad** [comment]
Does someone would like to help me resolve this problem? I know the issue is closed but I did not find the solution this problem not in closed issue not on stackoverflow.
`firebase deploy`

```
`badar:firbase-funcitons$ firebase deploy functions

Error: Too many arguments. Run firebase help deploy for usage instructions
badar:firbase-funcitons$ sudo firebase deploy functions
[sudo] password for badar: 

Error: Too many arguments. Run firebase help deploy for usage instructions

Having trouble? Try firebase deploy --help
badar:firbase-funcitons$ sudo firebase deploy --only functions

=== Deploying to 'pcbs-25985'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'firebase-admin'

Try running "npm install" in your functions directory before deploying.

Having trouble? Try firebase deploy --help
badar:firbase-funcitons$ cd functions/
badar:functions$ ls
index.js  node_modules  package.json
badar:functions$ sudo npm install

> grpc@1.6.6 install /root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.6.6/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.6.6 and node@9.2.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/build'
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node" "--module_name=grpc_node" "--module_path=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64"
gyp ERR! cwd /root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node --module_name=grpc_node --module_path=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.4.0-104-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node --module_name=grpc_node --module_path=/root/AndroidStudioProjects/PCBS/firbase-funcitons/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.6.6 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/badar/.npm/_logs/2017-12-28T12_15_39_886Z-debug.log`
```


For more information about files I have attached the gist link.
https://gist.github.com/badarshahzad/f5260022edfea28527f882e61d20d672
