### ISSUE TITLE
Error: spawn convert ENOENT using the generateThumbnail example

### ISSUE THREAD

**Issue by ygomezfinale** [firebase/functions-samples#502]
Hello, I got an error when migrating my cloud functions from node 6 to node 8 runtime,
  I deploy your generateThumbnail example cloud function (https://github.com/firebase/functions-samples/tree/Node-8/generate-thumbnail) and when I upload an image
  from Storage I see the following error in the Firebase Console logs:

Error: spawn convert ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Thanks in advance!

**Comment by olegbondr** [comment]
Having same issue since last deploy. Function has worked for month and has not been updated... 

Error occures when calling ImageMagic:     await spawn('convert', [tempLocalFile, '-thumbnail', `${THUMB_MAX_WIDTH}x${THUMB_MAX_HEIGHT}>`, tempLocalThumbFile], {capture: ['stdout', 'stderr']});

Second day trying to fix this issue :(

**Comment by ygomezfinale** [comment]
Is there any way to know if the 'convert' cmd is present in the CloudFunctions Node 8 environment ?

**Comment by ygomezfinale** [comment]
Now its working !!!

**Comment by seppestaes** [comment]
@ygomezfinale : can you tell us what you changed... having the same issue here
`Unhandled error { Error: spawn convert ENOENT`

**Comment by seppestaes** [comment]
Local development
Replaced 'spawn' with 'exec', error become more clear i.e. command convert not found. 
`brew install imagemagick` did the trick
