### ISSUE TITLE
Cannot find module '@custom-modules/moduleName' when deploy using TypeScript

### ISSUE THREAD

**Issue by chen86860** [firebase/functions-samples#504]
Hey, guys~ I can't deploy when I assign a `paths` arguments in `tsconfig.json`, like this:

```
{
  "compilerOptions": {
    "lib": ["es6"],
    "module": "commonjs",
    "outDir": "lib",
    "rootDir": "src",
    "target": "es6",
    "sourceMap": true,
    "noImplicitReturns": true,
    "baseUrl": ".",
    // here, I assign a paths arguments
    "paths": {
      "@custom-modules/*": ["src/modules/*"],
    }
  },
  "compileOnSave": true,
  "include": ["src"]
}

```

The `paths` arguments usually using TypeScript and it work perfectly.  But firebase deploy throw that error:
```
Error: Error parsing triggers: Cannot find module '@custom-modules/moduleName'
```

This question has published in StackOverFlow before [How to use TS Path Mapping with Firebase Cloud Functions](https://stackoverflow.com/questions/51021694/how-to-use-ts-path-mapping-with-firebase-cloud-functions), and for now, Can anyone help me? Thanks~ 🤣

**Comment by voxelbusters** [comment]
@chen86860 Any reason why this issue is closed? Did you find a solution?

**Comment by chen86860** [comment]
@voxelbusters Actually, I haven't resolve this problem yet. Because `paths` and `baseUrl` arguments cannot let TS complier know how resolve path but understand the typings and location of modules. Those two properties do _not tell_ the compiler to _include_ those mapped paths into the compilation or change the import statements to work during compile time.

You can fix this by doing relative imports or build by other tools like **webpack**.
