### ISSUE TITLE
error Promise { <pending> }

### ISSUE THREAD

**Issue by svkrdj** [firebase/functions-samples#514]
https://github.com/firebase/functions-samples/blob/491bb868efcf9d8f9b6adc50ccde91ae0c7eac8c/fcm-notifications/functions/index.js#L39

Sorry I am noob in these.
Should we use await and insert a callback

**Comment by samtstern** [comment]
@svkrdj it's hard to understand what you're asking here without more information.  In general if you have questions about Node.js and promises it's better to ask on a discussion forum like the firebase-talk Google Group or StackOverflow.
