### ISSUE TITLE
TypeError: firebase.initializeApp is not a function [Getting error both at local and in deployed]

### ISSUE THREAD

**Issue by knsakib** [firebase/functions-samples#515]
TypeError: firebase.initializeApp is not a function
    at Object.<anonymous> (........../isomorphic-react-app/functions/build/server.bundle.js:40580:10)
    at __webpack_require__ (........./isomorphic-react-app/functions/build/server.bundle.js:21:30)
    at Object.module.exports.module.exports.status (........../isomorphic-react-app/functions/build/server.bundle.js:22825:76)
    at __webpack_require__ (........./isomorphic-react-app/functions/build/server.bundle.js:21:30)
    at Object.module.exports.exports.__esModule (......./isomorphic-react-app/functions/build/server.bundle.js:40944:63)
    at __webpack_require__ (......./isomorphic-react-app/functions/build/server.bundle.js:21:30)
    at ......./isomorphic-react-app/functions/build/server.bundle.js:67:18
    at Object.<anonymous> (......./isomorphic-react-app/functions/build/server.bundle.js:70:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

**Comment by vintagexav** [comment]
+1

**Comment by EdenSG** [comment]
This seems to happen for me on the default (`Node-8`) branch, but not on `master` — it seems using an older version of the `firebase` package does the trick: 4.x works, 5.x does not. 
Perhaps an automated process (@dpebot) upgraded things without testing?

**Comment by maximilianotopp** [comment]
This is still happening. Please provide a fix for this.

**Comment by tanbt** [comment]
I'm using Firebase 6.0.1, the ES import statement `import firebase from 'firebase/app';` works for me,
but the one in the [instruction](https://firebase.google.com/docs/web/setup) `import * as firebase from "firebase/app";` does not. Please update.

**Comment by deanc** [comment]
Just want to follow up on this as I'm having the exact same error in a gatsby app when using this with gatsby-plugin-layout. Following @tanbt 's solution fixes the issue, but gives plenty of warnings. I might look into this a bit later on.

**Comment by BibhushanKarki** [comment]
> I'm using Firebase 6.0.1, the ES import statement `import firebase from 'firebase/app';` works for me,
> but the one in the [instruction](https://firebase.google.com/docs/web/setup) `import * as firebase from "firebase/app";` does not. Please update.



> I'm using Firebase 6.0.1, the ES import statement `import firebase from 'firebase/app';` works for me,
> but the one in the [instruction](https://firebase.google.com/docs/web/setup) `import * as firebase from "firebase/app";` does not. Please update.

Thanks! I was also stuck at this error. importing firebase without * works xD

**Comment by sameerbiradar2001** [comment]
I have a problem anybody tell me what is wrong with this 
on android, it is still a blank app


Android Bundling complete 67ms

TypeError: _app.default.initalizeApp is not a function. (In '_app.default.initalizeApp(firebaseConfig)', '_app.default.initalizeApp' is undefined)
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:null in guardedLoadModule
at http://192.168.101.6:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue

Invariant Violation: Failed to call into JavaScript module method AppRegistry.unmountApplicationComponentAtRootTag(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:null in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:null in handleError
at node_modules\expo\build\errors\ExpoErrorManager.js:null in errorHandler
at node_modules\expo\build\errors\ExpoErrorManager.js:null in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:null in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue
