### ISSUE TITLE
Unique and safe uid with-custom-token

### ISSUE THREAD

**Issue by shlighter** [firebase/functions-samples#516]
I use custom auth function on my app (in order to login anonymous users) -by saving a unique permanent custom token on their device.

The functions work fine both on app side and admin side but I need to provide a unique UID on the admin side- in order to save the user on Firebase. Here's my code on Admin (index.js):

`exports.createToken = functions.https.onCall((data, context) => { `
`const uid = "?????"; //  how to create some unique uid here?`
`return admin.auth()`
`            .createCustomToken(uid)`
`            .then(customToken => {`
`                return {status: 'success', customToken: customToken};`
`            })`
`});`

-How should we create a unique uid (that isn't on my Authentication users table already).
It should also be "safe" (that two users won't get it at the same time).
I couldn't find anything about it on documentation

**Comment by puf** [comment]
Also posted on https://stackoverflow.com/questions/53252881/how-to-create-unique-and-safe-uid-on-admin-custom-token-firebase, where this is more on topic.
