### ISSUE TITLE
Return data from function

### ISSUE THREAD

**Issue by dovahkiin98** [firebase/functions-samples#517]
Is there any way I can return data from a Cloud Function or something similar? For example, I have a long list of items and I want to search the items remotely and return the result from the Cloud.

I'm not sure if this is achievable by using a link on my server, but I'm using a serverless project.

**Comment by samtstern** [comment]
@dovahkiin98 what you want is a "callable" function:
https://firebase.google.com/docs/functions/callable

These functions act like remote procedure calls from your app.  You can pass data in and get data out.
