### ISSUE TITLE
Update examples that use admin.firestore() to exclude deprecated features

### ISSUE THREAD

**Issue by gabrielsz** [firebase/functions-samples#534]
Many examples using `admin.firestore()` will throw an error message if used as-is, because by default it is using deprecated features. An example and workaround are provided below, along with how to search for all occurrences.

### Repro steps
* Copy and deploy `presence-firestore/functions/index.js`

Example:
```const firestore = admin.firestore();```

### Workaround/fix
* Include the following configuration before using firestore:
```
const firestore = admin.firestore();
const settings = {timestampsInSnapshots: true};
firestore.settings(settings);
```

### How to search for occurrences
https://github.com/firebase/functions-samples/search?q=admin.firestore&unscoped_q=admin.firestore

**Comment by jamesdaniels** [comment]
No longer an issue, as the behavior changed in 5.8
