### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#54]
@nicolasgarnier 

Sir, do you have any idea how I can do the reverse charge, meaning, I can pay my user. 
Thanks to your advice, I was able to create my fiebase users charges, but I have no idea about how to pay my users. Stripe recommend the connect stripe api, but their documentation is true mess.

**Comment by MarkHoath** [comment]
If you want to REVERSE a charge this is called a REFUND and you need to use the REFUND object, pass the original CHARGE ID and the amount of the Refund. (You can only refund up to the charge amount)

If you want to PAY someone (like a supplier), then you need to use CONNECT ACCOUNTS to get the people you are paying to supply Bank Account details, then you can do a TRANSFER to send money between your account and their account.  

Alternatively you can bill users on behalf of connect accounts and you just take a commission. The difference is that any disputes are handled directly by the connect account.

**Comment by fxo140130** [comment]
I never talk about reverse charge, @nicolasgarnier help me implemented stripe with Firebase. My question was to do the reverse process, meaning send money to my supplier with connect stripe. If you read my post I already talked about Connect account.  My question was how to implement Connect Account with Firebase. 
I will be glad if you can help me.

**Comment by MarkHoath** [comment]
You should read your own comments.... "Sir, do you have any idea how I can do the reverse charge".

Each of your users will need to authenticate you for a Connect Account. Then you will get their stripe_account which you can save to Firebase.

When you call the "Charge/Capture" call to bull the end user on behalf of the Connect Account, you need to pass the Firebase Connect Account to the charge request.

Below is my PHP Code (I'm in the process of converting). If you remove the array(stripe_account) then you would bill the customer. If you supply the stripe account details, then you collect the fee and the amounts (less fee and stripe fee) are charged to the customer and deposited to the connect account.

$charge = \Stripe\Charge::create(array(
    "amount" => $amount,
    "currency" => $currency, 
    "source" => $token,
    "description" => $description,
    "application_fee" => $fee,
    "capture" => $capture),
    array('stripe_account' => $clientID)
    );

**Comment by MarkHoath** [comment]
stripe npm has the following example

// Retrieve the balance for a connected account:
stripe.balance.retrieve({
  stripe_account: "acct_foo"
}).then(function(balance) {
  // The balance object for the connected account
}).catch(function(err) {
  // Error
});

**Comment by fxo140130** [comment]
Thanks @MarkHoath  , Does my users have to have a stripe connect account ?

**Comment by MarkHoath** [comment]
lets say you are uber.. the drivers need a connect account, the passengers are just customers... If the driver also wants to use the uber app as a passenger, then they need to be both a connect account and a customer.

drivers need to authenticate their connect account with you (OAUTH) and you record the stripe_account in firebase. The passengers create a customer record and save their card for processing.

When you do the charge between the driver and the passenger, you pass the drivers stripe_account and the passengers source (card id) and you would get whatever you put in the application_fee field (see above example in php).

**Comment by jamesdaniels** [comment]
Feel free to continue to discuss, just closing the issue as it's not strictly related to the example up now. I'll consider putting together a Stripe Connect example.

**Comment by Huddie** [comment]
@jamesdaniels did you ever out together that stripe connect example?? would be super useful

**Comment by joeynelson42** [comment]
@jamesdaniels just wanted to second @Huddie's request, that would be very cool!

**Comment by MarkHoath** [comment]
I’m about to do a Series of You tube tutorials on stripe....

Swift Almanac is my channel.

**Comment by joeynelson42** [comment]
thanks @MarkHoath! Looking forward to it.

**Comment by copypasteearth** [comment]
Was wondering if there is a stripe connect firebase example out there yet

**Comment by MarkHoath** [comment]
I haven’t done one yet
