### ISSUE TITLE
firebase functions:config:set myproject.myvar="Hello Message!@My Server"

### ISSUE THREAD

**Issue by aelhadi** [firebase/functions-samples#545]
Hello,

i'm trying de set myproject.myvar  as below : 

firebase functions:config:set myproject.myvar="Hello Message!@My Server"

but i'm getting error : 

bash: !@My Server : event not found

it seems like it don't accept  the "!" caractere

Any help ?

**Comment by jamesdaniels** [comment]
The exclamation mark is used for history expansion in bash, you'll need to escape it with a backslash: `firebase functions:config:set myproject.myvar="Hello Message\!@my Server"`
