### ISSUE TITLE
HOW CAN I SEND AN EMAIL NOTIFICATION??

### ISSUE THREAD

**Issue by jesuspisa** [firebase/functions-samples#547]
Hi, 

I want to create a function trigerred by Pub/Sub. 
I upload messages at pub/sub with JSON format suh as: {temperature: 22, humidity: 20}.
That data is received from sensor temperature from a microcontroller.

The idea is to check the temperature message and if it is higher than a value, like 23.
Send an email-notification.

¿How can I do that?

¡Thank you very much!

**Comment by jamesdaniels** [comment]
Check out something like our crashlytics example https://github.com/firebase/functions-samples/tree/Node-8/crashlytics-integration/email-notifier
