### ISSUE TITLE
Create a front end for the Stripe example, so users can see it in action

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#55]
@nicolasgarnier 

Why I can't see /users/{userId}/""charges""/{id} in my database directory upon account creation ? 

Thanks

![image](https://cloud.githubusercontent.com/assets/25092371/23980090/8701915a-09cb-11e7-9c2c-71c7a2660694.png)

**Comment by MarkHoath** [comment]
charges is double quotes, you probably have an error in your firebase reference

**Comment by fxo140130** [comment]
@MarkHoath 

This is the code I got from the repository. 

![image](https://cloud.githubusercontent.com/assets/25092371/23987583/44548006-09f8-11e7-8587-6b5faeca0eb3.png)

Do you think, there is a mistake in it ?

**Comment by nicolasgarnier** [comment]
Maybe you got that reversed but how the sample works is that, to trigger a charge you must write to the DB under the path `/users/{userId}/charges/{id}` with an amount. The write to `/users/{userId}/charges/{id}` will trigger the Firebase Function called `createStripeCharge` and use the Stripe API to charge the user.

**Comment by fxo140130** [comment]
@nicolasgarnier ,

As you can see. There is no "charge directory" in my user tree. I tried everything but /charges/{id} is not present in the user profile. Please help.

**Comment by nicolasgarnier** [comment]
It's not present because you have to create it. Every new entry under `.../charge/{id}` will be a new charge that you invoke on the customer. You need to create a new entry under `.../charge/` and this will start a Stripe charge. You can see #56 on how to write to the DB at that path.

@jamesdaniels I guess we could document this a little bit better in the README :)

**Comment by fxo140130** [comment]
Thanks @nicolasgarnier . You are the best.

**Comment by jamesdaniels** [comment]
I'll put up a web front end for the Stripe example today, that way people can see it in action without knowing how to use the database console. I'll leave this Issue open for this purpose.

**Comment by fxo140130** [comment]
@jamesdaniels 

The front end for the Stripe example is located in the index.js file ?

**Comment by jamesdaniels** [comment]
Not yet, I have a Vue.js front end I've made which will use Firebase Hosting. I'll have it up soon. Just need to clean it up + write instructions.

**Comment by fxo140130** [comment]
@jamesdaniels  You are great Sir. I will be around to check if you can put stripe connect together to pay users. That will awesomely great. 

Thanks Sir :)

**Comment by iThinkersTeam** [comment]
Hello,

@jamesdaniels  thanks for you work. Have you estimate for write in instruction?

Thanks

**Comment by fxo140130** [comment]
@jamesdaniels Hi Sir, 
Do you already did web front end with Stripe ? Thanks
