### ISSUE TITLE
generate-thumbnail Add the URLs to the Firestore not RTDB

### ISSUE THREAD

**Issue by ibnuzaini** [firebase/functions-samples#550]
From this readme (https://github.com/firebase/functions-samples/tree/Node-8/generate-thumbnail),

I can't pass on these two steps:

1. **Go to your project's Cloud Console > IAM & admin > IAM, Find the App Engine default service account and add the Service Account Token Creator role to that member. This will allow your app to create signed public URLs to the images.**

I still can't understand on those step and I skipped.. Please give more clear instruction for this step..

I also got an error in firebase functions log (Is this error relate to those step that i skipped?):

SigningError: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. Permission iam.serviceAccounts.signBlob is required to perform this operation on service account projects/xxx/serviceAccounts/xxx@appspot.gserviceaccount.com.
    at authClient.sign.then.catch.err (/srv/node_modules/@google-cloud/storage/build/src/file.js:1855:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

2. **Go to the Firebase Console Database tab and see that a child of images has been created containing the Signed URLs for both images.** 

I can not find those data in the Database. What's wrong? And how if I need store the thumbnail URL to Firestore not in RTDB, please advice.

Thanks

**Comment by ibnuzaini** [comment]
I already got the answer..

**Comment by Abdul-Aziz-Kamboh** [comment]
i have same issue help!!!

**Comment by alxvallejo** [comment]
> I already got the answer..

You are the bane of my existence
