### ISSUE TITLE
Moderate Image Issue: Blurred image is downloaded with prefix of the folder name

### ISSUE THREAD

**Issue by r3dwc** [firebase/functions-samples#556]
Hi, everyone!
I'm using the Cloud Function API for making inappropriate images blurred and save on firebase. Everything is good, but the file is downloaded with prefix of the folder name. For example, the image name on firebase is 'unBsdUHUb0aBxegJMaVr6LKXSLL2', but its name gets 'profile_images_unBsdUHUb0aBxegJMaVr6LKXSLL2' when it's downloaded.
No issue with normal images. Only happened in blurred images.
I hope to remove the prefix so that the image is downloaded with its origin name.
What would be the problem?
Code is here. https://github.com/mydream19/firebase_moderate_image
Thank you.

**Comment by jhuleatt** [comment]
The behavior of the [sample source](https://github.com/firebase/functions-samples/tree/master/moderate-images#automatically-moderate-images) recently changed (in #599) to write the blurred images into a different folder, but it doesn't change the file names.
