### ISSUE TITLE
Firestore Cloud function subcollection

### ISSUE THREAD

**Issue by Noddy20** [firebase/functions-samples#558]
I have my Firestore collection and sub collection like this
MainCollection -> UniqeID Document -> SubCollection -> Document
 I want to write onCreate trigger cloud function for documents in SunCollection
So i wrote it like this -

`exports.onAskLocalCreate = functions.firestore
.document('MainCollection/{}/{SubCollection}/{docId}')
.onCreate((snap, context) => {..........`

but when i try to deploy it, it gives error
functions: failed to update function onAskLocalCreate
HTTP Error: 400, The request has errors

How can achive this.
Thank you.

**Comment by lohanidamodar** [comment]
@Noddy20 did you solve this?
