### ISSUE TITLE
Stripe charges

### ISSUE THREAD

**Issue by iThinkersTeam** [firebase/functions-samples#56]
Hello,

I deployed stripe, registered new user which created in "stripe_customer".

How can I use this - /users/{userId}/charges/{id}. 
userId is like "cus_AIUNyLkyv8mUUQ"

what is "id"?
How can I add amount to this request?

Thanks

**Comment by fxo140130** [comment]
@iThinkersTeam  I am having the same issue too. There is no  /users/{userId}/charges/{id} directory.

**Comment by nicolasgarnier** [comment]
From your server you would need to push a node to the `/users/{userId}/charges` path.

For instance:

```js
admin.database().ref('/users/' + userId + '/charges').push({amount: 100}); // This will charge 100 USD
```

**Comment by iThinkersTeam** [comment]
I try configure for ios app.

I wrote 
 class func pay(amount: Int) {
        let amount: [String: Any] = ["amount": amount]
        if let curentUser = FIRAuth.auth()?.currentUser {
            userRef.child(curentUser.uid).child("charges").setValue(amount)
        }
    }

I check logo in stripe and found error 
<img width="739" alt="2017-03-16 13 16 35" src="https://cloud.githubusercontent.com/assets/20794151/23994784/30257d22-0a4f-11e7-9527-dd82c6f65986.png">

I added test card manually for this user.

Also in the morning I have success request
<img width="804" alt="2017-03-16 13 50 56" src="https://cloud.githubusercontent.com/assets/20794151/23994893/aeac2d44-0a4f-11e7-90d9-d1abd7f17b0c.png">
But I checked my panel and I don't see this payment.

Have you any idea?
Thanks a lot for your help

**Comment by jamesdaniels** [comment]
I've repurposed #55 to create a front end to see the example in action + the expected DB schema. I'll close in favor of that.

It looks like in your code you're not **push**ing also from that example, the user needs a payment method. I'll make this more clear in the front end I'm putting together.
