### ISSUE TITLE
Firebase functions in Go or Python

### ISSUE THREAD

**Issue by Trane9991** [firebase/functions-samples#561]
Hey, I don't really understand is it possible to write Firebase functions in Go or Python (since Google Cloud Functions supports them). Would like to see some examples!

**Comment by CodingDoug** [comment]
There's one detail that's important to understand.  There is just one product called Google Cloud Functions (there is not actually a product called "Firebase Functions").  Firebase provides tools and libraries to use on top of GCF.  GCF supports multiple language runtimes, but Firebase only provides  tools and SDKs for node JavaScript on node right now.

You are free to use either the Google Cloud tools (gcloud) or the Firebase tools (the Firebase CLI) for deploying functions.  If you want to target python or go, you will have to use gcloud, which is described as part of Cloud documentation.  If you want to use the Firebase tools, you are limited to JavaScript on node.  Either way, the underlying GCF product works exactly the same.

You can read more about what's different between Firebase and Google Cloud with respect to the Cloud Functions product in [this blog](https://medium.com/google-developers/firebase-google-cloud-whats-different-with-cloud-functions-612d9e1e89cb).

**Comment by LockedThread** [comment]
This should be re-opened and considered for future development. Using Golang is becoming a widely preferred language over JavaScript because of the performance increases, along with that I don't see that making a Golang library for handling Firebase Functions would be difficult because you already have the underlying Google Cloud Function support for Golang.

**Comment by softmarshmallow** [comment]
Seconded

**Comment by betoop** [comment]
thirded

**Comment by nitaigao** [comment]
fourthed!

**Comment by luca-venir** [comment]
fifthed! at the end of the day firebase should give more than just a node sdk imo.

**Comment by yhfy2006** [comment]
fifthed!

**Comment by vctqs1** [comment]
sixthed!

**Comment by RahulBhalley** [comment]
seventhed and staled!

**Comment by tommyzat** [comment]
Eighted

**Comment by kaustavsarkar** [comment]
Nineth

**Comment by hwkim1127** [comment]
Tenth!

**Comment by Raraku** [comment]
Eleventh

**Comment by RahulBhalley** [comment]
And boom is available!!
