### ISSUE TITLE
The 'thumbnails' example uses outdated GCS Node APIs

### ISSUE THREAD

**Issue by samtstern** [firebase/functions-samples#563]
Initially reported here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-cloud-firestore-discuss/Xye0Xorh8pw/B9D6SFbeBgAJ

It seems that the GCS API has changed, but it's not even clear what version we depend on since it's not listed in package.json:
https://github.com/firebase/functions-samples/blob/6c284a689c484ac4395fde1a8e8d6c2731705b55/quickstarts/thumbnails/functions/package.json

Maybe it's a transitive dependency?

**Comment by jhuleatt** [comment]
Looks like we use the Admin SDK instead now: https://github.com/firebase/functions-samples/commit/c8472ce6d8b2a09b0940636b8354e91720f27069#diff-3fd2ed3601e057cda27b6cddb92d91a9L54

So I guess the docs just need to be updated

**Comment by samtstern** [comment]
@jhuleatt good catch, I just republished the docs.
