### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by NYESIGANABOTH** [firebase/functions-samples#575]
<!--i dont know how to use this site. I need some help

**Comment by NYESIGANABOTH** [comment]
i need some help because i do not know how to use this site

**Comment by ashish-pise** [comment]
what help do you want ? means which type of tutorial ?

**Comment by NYESIGANABOTH** [comment]
how best can i use github to earn a living
*nabothwise*

**Comment by jhuleatt** [comment]
Closing this since it doesn't have to do with firebase-tools. Check out github's getting started guide: https://guides.github.com/activities/hello-world/

**Comment by NYESIGANABOTH** [comment]
The Global Education Conference Network: 
--------------------

Join this It is good and educational

Click the link below to Join:
https://www.globaleducationconference.org/?xgi=1SRM9b54hT6Ioa&xg_source=msg_invite_net

If your email program doesn't recognize the web address above as an active link,
please copy and paste it into your web browser

--------------------

Members already on The Global Education Conference Network
Latishia Sparks, Cathy Leogrande, Adam C Holden, Larisa K. Schelkin, Jennifer Manise

--------------------

About The Global Education Conference Network
Welcome to our online community focused on globally connected teaching and learning. Contribute ideas, resources, and inspiration!

27749 members
709 videos
4541 discussions
1304 blog posts

--------------------

To control which emails you receive on The Global Education Conference Network, or to opt-out, go to:
https://www.globaleducationconference.org/?xgo=eP/PnuONgYAUyx3VUh6zOQDLfQ3WoWT6wzV9ts8YmiHFDYkOTgIyHbXYkAMhUMo0ucjC9zgcpztIY99umrtoGL/EcP8vMASLCrIk4Mv/3AKDb3UHVH1FnA&xg_source=msg_invite_net
