### ISSUE TITLE
storage list

### ISSUE THREAD

**Issue by hooloom** [firebase/functions-samples#577]
It's 2019 - we're using firebase and angular together.  I find it crazy that there is no well documented way to get a complete list of documents inside Firebase Storage.  Every other major platform including Azure, and AWS has such functionality.  Please provide this functionality or documentation on how to do this.  I really appreciate all the work - but if I'm paying for something - one would expect it to work in compare to its competitors.

**Comment by jhuleatt** [comment]
This is now available in the JS SDK: https://firebase.google.com/docs/storage/web/list-files

We're still working on the docs for other platforms, but they should be out soon!
