### ISSUE TITLE
I have created this in my app but IOS is not working with payout

### ISSUE THREAD

**Issue by devhopes-ca** [firebase/functions-samples#578]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by devhopes-ca** [comment]
I have created PayPal with firebase functions in my app.  It works with Android but not so much in IOS, I am thinking it has to do with the payoutRequest:

func payoutRequest() {

    print("payoutRequest")

    // Progress View
    self.progress.progress = value
    self.perform(#selector(updateProgressView), with: nil, afterDelay: 1.0)

    let email = txtPayoutEmail.text!

    let url = "https://us-central1-myapp.cloudfunctions.net/payout"

    let params : Parameters = [
        "uid": self.uid! as String,
        "email": email
    ]

    let headers : HTTPHeaders = [
        "Content-Type": "application/json",
        "Authorization": "Your Token",
        "cache-control": "no-cache"
    ]

    let myData = try? JSONSerialization.data(withJSONObject: params, options: [])
    print("data: \(String(describing: myData))")

   Alamofire.request(url, method: .post, parameters: params, encoding: JSONEncoding.default, headers: headers)
        .validate(statusCode: 200..<300)
        .validate(contentType: ["application/json"])
        .responseData(completionHandler: { (response) in

        //print("Request: \(String(describing: response.request))")   // original url request
        //print("Response: \(String(describing: response.response))") // http url response
        print("Result: \(response.result)")                         // response serialization result

        switch response.result {
        case .success:
            print("Validation Successful")
            let parsedObject = try! JSONSerialization.jsonObject(with: myData!, options: .allowFragments)
            print("parsed: \(parsedObject)")

        case .failure(let error):
            print(error)
        }
    })
}

Please help.

**Comment by jhuleatt** [comment]
It doesn't look like the `payout` function (that you're calling via `https://us-central1-myapp.cloudfunctions.net/payout`) exists in the [Paypal sample](https://github.com/firebase/functions-samples/blob/master/paypal/functions/index.js). 

I'm going to close this since it seems like it is out of scope for this repo. If you can post error logs in this issue, and anything else asked for in the initial template, we can reopen this and try to help.
