### ISSUE TITLE
fulltext-search doesn't work with Spark (FREE) plan

### ISSUE THREAD

**Issue by peterzagoranski** [firebase/functions-samples#58]
Outbound networking is not allowed with [Spark plan](https://firebase.google.com/pricing), so it would be nice if Google could remove this limitation as they have for other products inside firebase ...

Error: AlgoliaSearchNetworkError: getaddrinfo ENOTFOUND *.algolianet.com

**Comment by abehaskins** [comment]
This is correct, Cloud Functions for Firebase do not have access to outgoing network access if you are not on a paid plan. This limitation isn't likely to change, perhaps we should add a message on any samples which rely on the paid plans.

**Comment by jamesdaniels** [comment]
If you upgrade to the [Blaze (pay as you go) plan](https://firebase.google.com/pricing/) you'll be able to make external API requests and [you'll be subject to the free tier](https://cloud.google.com/functions/pricing#free_tier).

**Comment by jamesdaniels** [comment]
The main concern is prevention of DDOS or other malicious activities, which could disrupt service + get the IP addresses blacklisted.
