### ISSUE TITLE
cloned typescript-getting-started fails to build

### ISSUE THREAD

**Issue by CollinGraf314** [firebase/functions-samples#582]
### How to reproduce these conditions

clone this repository and follow the Project Setup instructions here: https://github.com/firebase/functions-samples/tree/master/typescript-getting-started

run `npm run deply` and watch it fail

**Sample data pasted or attached as JSON (not an image)**

```
Error: An unexpected error has occurred.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ deploy: `firebase deploy --only functions`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
```

npm version: 6.10.0
nodejs version: v10.15.3

### Expected behavior

Not to fail

### Actual behavior

Fails

#### EDIT: May be an issue with npm 6.10.0
https://stackoverflow.com/questions/56875994/typeerror-cannot-read-property-wanted-of-undefined

**Comment by jhuleatt** [comment]
@CollinGraf314 this does sound like the same issue. Here's the official github issue: https://github.com/firebase/firebase-tools/issues/1469. [Downgrading to npm 6.9.2](https://github.com/firebase/firebase-tools/issues/1469#issuecomment-508821710) should fix the issue. If that doesn't solve it, can you please post the full debug output here? `firebase deploy --only functions --debug`

**Comment by jhuleatt** [comment]
[Version 7.1.0](https://github.com/firebase/firebase-tools/releases/tag/v7.1.0) of the firebase CLI fixes the deploy issue.
