### ISSUE TITLE
Cloud Functions for Flutter

### ISSUE THREAD

**Issue by FilipeOS** [firebase/functions-samples#583]
Hi guys,

So basically I'm making a chat app and I need to get user online/offline status in Firestore using CloudFunctions + Realtime Database but I'm struggling with it..

Can someone advise?

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

const firestore = functions.firestore;

exports.onUserStatusChange = functions.database
	.ref('/status/{userId}')
	.onUpdate(event => {
		
		var db = admin.firestore();		
		
		const usersRef = db.collection("u");
		var snapShot = event.data;
		
		return event.data.ref.once('value')
			.then(statusSnap => snapShot.val())
			.then(status => {
				if (status === 'offline'){
					usersRef
						.doc(event.params.userId)
						.set({
							online: false,
							last_active: Date.now()
						}, {merge: true});
				}
				return;
			})
	});
```

I'm still trying to figure out the difference between this example and the one on this repository since both should work? But I'm not getting user status at all :(

**Comment by jhuleatt** [comment]
Hi @FilipeOS, [this sample](https://github.com/firebase/functions-samples/tree/master/presence-firestore) only shows the backend implementation for a presence system. You also need to use the `'.info/connected'` ref on the client to write to the `'/status/{userId}'` path that the Cloud Function is listening to. A more thorough explanation can be found in [the docs](https://firebase.google.com/docs/firestore/solutions/presence).

I'll update the readme for this sample to make it more clear that client side changes are also required.

**Comment by FilipeOS** [comment]
Hi @jhuleatt that sample applies to Flutter too? Or I need to change that index.js code to match Flutter needs AND change my Flutter app? (I tried everything on my app to check the .info/connected but I'm so lost and don't work with StreamBuilder nor InitState listen user)

I would appreciate so much an advise please

**Comment by jhuleatt** [comment]
The samples in this repository are for Cloud Functions for Firebase, which runs JavaScript in Google datacenters via NodeJS. The docs link I sent shows the client side implementation for presence in the browser, but you can use the concepts introduced there to figure out how to do it for Flutter.

For code samples of using the Realtime Database with flutter, check out [these examples](https://github.com/flutter/plugins/tree/master/packages/firebase_database/example).

**Comment by horgag1** [comment]
@jhuleatt the link to the examples is broken

**Comment by jhuleatt** [comment]
Here's the realtime database package: https://pub.dev/packages/firebase_database#-readme-tab-

This codelab uses Firestore, but can give you an idea of what it looks like to use Firebase with Flutter: https://codelabs.developers.google.com/codelabs/flutter-firebase/#8

**Comment by bhaskar-nair2** [comment]
Why is that we can't listen to the '.info/connected' value on a cloud function and just update our firestore accordingly?
