### ISSUE TITLE
Spotify auth: pop up window opens, but only ever says "please wait" error *Updates below - still unresolved*

### ISSUE THREAD

**Issue by marcz2007** [firebase/functions-samples#589]
### How to reproduce these conditions
I followed the steps here: https://github.com/firebase/functions-samples/tree/master/spotify-auth 
The only one which is different is that it could not find the ./service-account.json file so I just included it as a const instead. Everything else I did the same as per the instructions. 
**Failing Function code used (including require/import commands at the top)**
```js

'use strict';

const functions = require('firebase-functions');
const admin = require('firebase-admin');
// const serviceAccount = require('./service-account.json');
const serviceAccount = {/* SERVICE ACCOUNT CONFIG */}

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${process.env.GCLOUD_PROJECT}.firebaseio.com`,
});
const {WebhookClient} = require('dialogflow-fulfillment');
const cookieParser = require('cookie-parser');
const crypto = require('crypto');


// Spotify OAuth 2 setup
// TODO: Configure the `spotify.client_id` and `spotify.client_secret` Google Cloud environment variables.
const SpotifyWebApi = require('spotify-web-api-node');
const Spotify = new SpotifyWebApi({
  clientId: functions.config().spotify.client_id,
  clientSecret: functions.config().spotify.client_secret,
  redirectUri: `https://${process.env.GCLOUD_PROJECT}.firebaseapp.com/popup.html`,
});


// Scopes to request.
const OAUTH_SCOPES = ['user-read-email'];

/**
 * Redirects the User to the Spotify authentication consent screen. Also the 'state' cookie is set for later state
 * verification.
 */
exports.redirect = functions.https.onRequest((req, res) => {
  cookieParser()(req, res, () => {
    const state = req.cookies.state || crypto.randomBytes(20).toString('hex');
    console.log('Setting verification state:', state);
    res.cookie('state', state.toString(), {maxAge: 3600000, secure: true, httpOnly: true});
    const authorizeURL = Spotify.createAuthorizeURL(OAUTH_SCOPES, state.toString());
    res.redirect(authorizeURL);
  });
});

/**
 * Exchanges a given Spotify auth code passed in the 'code' URL query parameter for a Firebase auth token.
 * The request also needs to specify a 'state' query parameter which will be checked against the 'state' cookie.
 * The Firebase custom auth token is sent back in a JSONP callback function with function name defined by the
 * 'callback' query parameter.
 */
exports.token = functions.https.onRequest((req, res) => {
  try {
    cookieParser()(req, res, () => {
      console.log('Received verification state:', req.cookies.state);
      console.log('Received state:', req.query.state);
      if (!req.cookies.state) {
        throw new Error('State cookie not set or expired. Maybe you took too long to authorize. Please try again.');
      } else if (req.cookies.state !== req.query.state) {
        throw new Error('State validation failed');
      }
      console.log('Received auth code:', req.query.code);
      Spotify.authorizationCodeGrant(req.query.code, (error, data) => {
        if (error) {
          throw error;
        }
        console.log('Received Access Token:', data.body['access_token']);
        Spotify.setAccessToken(data.body['access_token']);

        Spotify.getMe(async (error, userResults) => {
          if (error) {
            throw error;
          }
          console.log('Auth code exchange result received:', userResults);
          // We have a Spotify access token and the user identity now.
          const accessToken = data.body['access_token'];
          const spotifyUserID = userResults.body['id'];
          const profilePic = userResults.body['images'][0]['url'];
          const userName = userResults.body['display_name'];
          const email = userResults.body['email'];

          // Create a Firebase account and get the Custom Auth Token.
          const firebaseToken = await createFirebaseAccount(spotifyUserID, userName, profilePic, email, accessToken);
          // Serve an HTML page that signs the user in and updates the user profile.
          res.jsonp({token: firebaseToken});
        });
      });
    });
  } catch (error) {
    return res.jsonp({error: error.toString});
  }
  return null;
});

/**
 * Creates a Firebase account with the given user profile and returns a custom auth token allowing
 * signing-in this account.
 * Also saves the accessToken to the datastore at /spotifyAccessToken/$uid
 *
 * @returns {Promise<string>} The Firebase custom auth token in a promise.
 */
async function createFirebaseAccount(spotifyID, displayName, photoURL, email, accessToken) {
  // The UID we'll assign to the user.
  const uid = `spotify:${spotifyID}`;

  // Save the access token to the Firebase Realtime Database.
  const databaseTask = admin.database().ref(`/spotifyAccessToken/${uid}`).set(accessToken);

  // Create or update the user account.
  const userCreationTask = admin.auth().updateUser(uid, {
    displayName: displayName,
    photoURL: photoURL,
    email: email,
    emailVerified: true,
  }).catch((error) => {
    // If user does not exists we create it.
    if (error.code === 'auth/user-not-found') {
      return admin.auth().createUser({
        uid: uid,
        displayName: displayName,
        photoURL: photoURL,
        email: email,
        emailVerified: true,
      });
    }
    throw error;
  });

  // Wait for all async tasks to complete, then generate and return a custom auth token.
  await Promise.all([userCreationTask, databaseTask]);
  // Create a Firebase custom auth token.
  const token = await admin.auth().createCustomToken(uid);
  console.log('Created Custom token for UID "', uid, '" Token:', token);
  return token;
}
// Bellow is the code for the rest of my app and can be ignored
exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
  const agent = new WebhookClient({ request, response });	

  
  //53 to 64
  function playSadSong (agent) {
    // Get the database collection 'dialogflow' and document 'agent'
    var randomNumber = Math.floor(Math.random() * (64-53 + 1)) + 53; 
  
   	return admin.database().ref((`${randomNumber}`) ).once('value').then((snapshot)  => {
      const song = snapshot.child('song').val();
      const artist = snapshot.child('artist').val();
      
     
        agent.add(`I will play ${song} by ${artist}`);
        const request = require('request');

        app.get('/login', function(req, res) {
          var scopes = 'user-read-private user-read-email';
          res.redirect('https://accounts.spotify.com/authorize' +
            '?response_type=code' +
            '&client_id=' + my_client_id +
            (scopes ? '&scope=' + encodeURIComponent(scopes) : '') +
            '&redirect_uri=' + encodeURIComponent(redirect_uri));
          });

        exports.helloWorld = function helloWorld(req, res) {
          // Example input: {"message": "Hello!"}
          if (req.body.message === undefined) {
            // This is an error case, as "message" is required.
            res.status(400).send('No message defined!');
          } else {
            // Everything is okay.
            console.log(req.body.message);
        
            request.get('https://api.spotify.com/v1/me/player/play', function (error, response, body) {
              console.log('error:', error); // Print the error if one occurred 
              console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received 
              console.log('body:', body); //Prints the response of the request. 
            });
            res.status(200).send("Success");
          }
        };
       

//         app.post('/', function (req, res) {
//   res.send('POST request to the homepage')
// })
      
//         router.post('/', function(req, res, next) {
//   // let city = req.body.queryResult.parameters['geo-city'];
//   // let url = `http://api.openweathermap.org/data/2.5/weather?q=${city},us&APPID=0ed0839d26e395af50e382032d65017c`;

//   // axios
//   //   .get(url)
//   //   .then((aRes) => {
//   //     let conditions = aRes.data.weather[0].main;
//   //     let temp = aRes.data.main.temp;

//   //     let textResponse = `I will play ${song}, by ${artist}`;
//   //     res.send(createTextResponse(textResponse));
//   //   })
//   //   .catch((err) => {
//   //     console.log(err);
//   //   });
// });

   
   });
  }
  //22 to 53
  function playHappySong (agent) {
    // Get the database collection 'dialogflow' and document 'agent'
    var randomNumber = Math.floor(Math.random() * (53-22 + 1)) + 22; 
  
   	return admin.database().ref((`${randomNumber}`) ).once('value').then((snapshot)  => {
      const song = snapshot.child('song').val();
      const artist = snapshot.child('artist').val();
      
     
        agent.add(`I will play ${song} by ${artist}`);
      
   
   });
  }
  
  //4
    function playAngrySong (agent) {
    // Get the database collection 'dialogflow' and document 'agent'
    var randomNumber = Math.floor(Math.random() * (3-3 + 1)) + 3; 
  
   	return admin.database().ref((`${randomNumber}`) ).once('value').then((snapshot)  => {
      const song = snapshot.child('song').val();
      const artist = snapshot.child('artist').val();
      
     
        agent.add(`I will play ${song} by ${artist}`);
      
   
   });
  }
    
  //5 to 15
    function playConfidentSong (agent) {
    // Get the database collection 'dialogflow' and document 'agent'
    var randomNumber = Math.floor(Math.random() * (15-5 + 1)) + 5; 
  
   	return admin.database().ref((`${randomNumber}`) ).once('value').then((snapshot)  => {
      const song = snapshot.child('song').val();
      const artist = snapshot.child('artist').val();
      
     
        agent.add(`I will play ${song} by ${artist}`);
      
   
   });
  }
    

  // Map from Dialogflow intent names to functions to be run when the intent is matched
  let intentMap = new Map();
  intentMap.set('-Sad - yes', playSadSong);
  intentMap.set('-Happy - yes', playHappySong);
  intentMap.set('-Angry - yes', playAngrySong);
    intentMap.set('-Confident - yes', playConfidentSong);
  
  agent.handleRequest(intentMap);
});
```

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**
![Screenshot 2019-07-25 at 15 11 38](https://user-images.githubusercontent.com/42185902/61881561-b5f9b080-aeee-11e9-9623-e6710989c03c.png)

### Expected behavior
To give me the access token

### Actual behavior
It just eternally says 'please wait'

**Comment by marcz2007** [comment]
UPDATE: It moves from 'please wait' to 'INVALID_CLIENT: Invalid redirect URI' whenever the 'https://mood-magic-four-ptwvjb.firebaseapp.com/popup.html' is entered after clicking 'sign in with spotify'. This is taken from the complete request for 'https://accounts.spotify.com/authorize?client_id=744a1316f9374a27b7ec9bc7eabb0f92&response_type=code&redirect_uri=https://mood-magic-four-ptwvjb.firebaseapp.com/popup.html&scope=user-read-email&state=b09b292d06dc746b17ef1ca123d0ad7fc6c96814'.

Why is https://mood-magic-four-ptwvjb.firebaseapp.com/popup.html causing this to happen? I have tried using this as the redirect url in the Spotify app and that just causes it to stay as 'please wait'. (I assume because it keeps eternally redirecting it to itself). But then if I have https://mood-magic-four-ptwvjb.firebaseapp.com/ or https://mood-magic-four-ptwvjb.firebaseapp.com/index.html as the redirect URL on Spotify then it just returns 'invalid'.

Anyone know what my Spotify redirect URL should be in this example??

**Comment by jhuleatt** [comment]
I edited the initial comment to remove service account config. Please keep that private!

**Comment by marcz2007** [comment]
Ah thanks Jeff, I must have missed that in my original post! I have now managed to get the service-account.json to work as a require relative path now so that is fixed. Which means I am now following the guide exactly - any ideas about my invalid redirect URI predicament?

**Comment by jhuleatt** [comment]
That "Please Wait..." text is from [`popup.html`](https://github.com/firebase/functions-samples/blob/91ddb52c069056edf8fdfc31beed53824fbd6b04/spotify-auth/public/popup.html#L24), which makes me think something in that page is failing silently, so I think that's the first place to look.

Can you please open Chrome devtools in the popup and see if there are any errors in the console? You can configure devtools to auto-open for pop-ups by going to [devtools settings](https://developers.google.com/web/tools/chrome-devtools/customize/#settings) and checking the box next to *"Auto-open DevTools for popups"*

**Comment by marcz2007** [comment]
Failed to load resource: the server responded with a status of 500 ()
That's the error message for the popup screen

**Comment by marcz2007** [comment]
I'm not sure why this screen would be getting an internal service error when none of the others do... any ideas?

**Comment by jhuleatt** [comment]
What endpoint is giving the 500? Can you post the full error or a screenshot from the network tab of devtools?

**Comment by marcz2007** [comment]
<img width="1550" alt="Screenshot 2019-07-26 at 00 53 24" src="https://user-images.githubusercontent.com/42185902/61916287-d736bd00-af3f-11e9-8e9b-e296c91196b6.png">

**Comment by jhuleatt** [comment]
Thanks, looks like your `token` function is returning a 500 error. To diagnose that, take a look at your [functions logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)

**Comment by marcz2007** [comment]
Ok thank you, my logs are below. Unfortunately since it's so late I can only understand the error about the lack of blaze plan (which I upgraded to earlier in the night). Could you advise me where I should start with these so I can get straight to it in the morning? 

Many thanks for your help it's much appreciated :) 

12:52:53.053 am
token
Received auth code: AQAbt2-JLHSED4wsWVb3IDZwuzybZiAGU7A54eQ1uRcGvnkA_XUtDz-rSUqLrZU41iYliVRU7PNDB3iczuX5XE5sZUXMDnyU9D1Mjb_W4nzabbBte2c1GoCzU8ejmgwiSOWjHVG5weSn71W6biAgrWGbwB4kfFfJwZY6rXgrfHmBst0HWYZ98D5tddHDiout_1jzc83fBO_WV_qbU989QMsXr6ZH8YSbsQC8j3el29NMukWCJ_Yy8hJQPNGlHs_7MvM
12:52:53.053 am
token
Received state: e1bf502b17fa35aab89c6550eea924cb4c415f0a
12:52:53.051 am
token
Received verification state: e1bf502b17fa35aab89c6550eea924cb4c415f0a
12:52:51.573 am
token
Function execution started
12:52:30.895 am
token
Function execution took 2149 ms, finished with status: 'crash'
12:52:30.889 am
token
Error: The email address is already in use by another account. at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:146:16) at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:185:16) at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1139:49 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
12:52:30.889 am
token
Unhandled rejection
12:52:29.960 am
token
Auth code exchange result received: { body: { display_name: 'Marcus Watts', email: 'marc.jwatts@gmail.com', external_urls: { spotify: 'https://open.spotify.com/user/marcz2007' }, followers: { href: null, total: 10 }, href: 'https://api.spotify.com/v1/users/marcz2007', id: 'marcz2007', images: [ [Object] ], type: 'user', uri: 'spotify:user:marcz2007' }, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, max-age=0', vary: 'Authorization', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', date: 'Thu, 25 Jul 2019 23:52:29 GMT', via: '1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 200 }
12:52:29.907 am
token
Received Access Token: BQCyrOUkDrmlI06fu9HLE6-oSKin9IPUcg4ZE1zadh5MJLYqR7vc2CwnbP_EHsfb7sBnCktfzc30MpRqlrdCABU2X0fjmZr_QySem3sgAS4s-g7Ez-1O2S_ic33KwPw1ByQ5C4pMc7HnpMHukCP4ek85
12:52:29.820 am
token
Received auth code: AQAbt2-JLHSED4wsWVb3IDZwuzybZiAGU7A54eQ1uRcGvnkA_XUtDz-rSUqLrZU41iYliVRU7PNDB3iczuX5XE5sZUXMDnyU9D1Mjb_W4nzabbBte2c1GoCzU8ejmgwiSOWjHVG5weSn71W6biAgrWGbwB4kfFfJwZY6rXgrfHmBst0HWYZ98D5tddHDiout_1jzc83fBO_WV_qbU989QMsXr6ZH8YSbsQC8j3el29NMukWCJ_Yy8hJQPNGlHs_7MvM
12:52:29.820 am
token
Received state: e1bf502b17fa35aab89c6550eea924cb4c415f0a
12:52:29.816 am
token
Received verification state: e1bf502b17fa35aab89c6550eea924cb4c415f0a
12:52:28.746 am
token
Function execution started
25 Jul 2019
11:51:59.239 pm
token
Function execution took 5804 ms, finished with status: 'crash'
11:51:59.180 pm
token
Error: The email address is already in use by another account. at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:146:16) at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:185:16) at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1139:49 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
11:51:59.180 pm
token
Unhandled rejection
11:51:57.871 pm
token
Auth code exchange result received: { body: { display_name: 'Marcus Watts', email: 'marc.jwatts@gmail.com', external_urls: { spotify: 'https://open.spotify.com/user/marcz2007' }, followers: { href: null, total: 10 }, href: 'https://api.spotify.com/v1/users/marcz2007', id: 'marcz2007', images: [ [Object] ], type: 'user', uri: 'spotify:user:marcz2007' }, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, max-age=0', vary: 'Authorization', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', date: 'Thu, 25 Jul 2019 22:51:57 GMT', via: '1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 200 }
11:51:57.801 pm
token
Received Access Token: BQCp0rsjalnxmsT-xc6cgA3ojMSVVHDzZy6DY3ejYDTmE50s_AoOzP3fi5HQFOO9-6t95pPN-qXR_07VEL0HGGBzwB5KvY2-i8X4l49SIZhQ5YH_WSmh9wSBOxyAzkEUNpUHwMBNaiJGt5WRQGAxHHNR
11:51:57.554 pm
token
Received auth code: AQBAGvseaO67lGrzzTs4DwF1wUqF5WPQnd5swNbsJAmzw223cOeuHmUgYh3HbhSVA6PKjRiVgHbivD4cZXmm1cpgCb2sXnVCZaoWHxxupuAQNuAO1y7RL5ezbTqOw27C8CgrNydjBsim4n0J-2UL9PPJ39_EZByQSd8LwxodPeFDSfVZH4ToZYgT42JWX7r7cufLUe2rWyCLA_8SGBaQmrQERrk_OlkYy6DBKyaoGC8MwKUSW1qaAI7HsnknKOw0YYE
11:51:57.554 pm
token
Received state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
11:51:57.547 pm
token
Received verification state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
11:51:53.436 pm
token
Function execution started
11:48:11.185 pm
token
Function execution took 5962 ms, finished with status: 'crash'
11:48:11.149 pm
token
Error: The email address is already in use by another account. at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:146:16) at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:185:16) at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1139:49 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
11:48:11.148 pm
token
Unhandled rejection
11:48:09.601 pm
token
Auth code exchange result received: { body: { display_name: 'Marcus Watts', email: 'marc.jwatts@gmail.com', external_urls: { spotify: 'https://open.spotify.com/user/marcz2007' }, followers: { href: null, total: 10 }, href: 'https://api.spotify.com/v1/users/marcz2007', id: 'marcz2007', images: [ [Object] ], type: 'user', uri: 'spotify:user:marcz2007' }, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, max-age=0', vary: 'Authorization', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', date: 'Thu, 25 Jul 2019 22:48:09 GMT', via: '1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 200 }
11:48:09.522 pm
token
Received Access Token: BQAyjBjXSReudh2dDva1iJIVAz1C5iozUoKAcnJk7vDFzuMAmeyiftZV7KJsfJO9CGq30kCYjj9GaDj6u-WLuiYcoLwf2BbOs1mR0zu_PPoiPadFNkvyP2LEH0VgpHIKZ9pgyWG8Bof15js25sEuEzfn
11:48:09.197 pm
token
Received auth code: AQCk-9Fxc0IcuNxPVvSSEuBh8mrs2WaHMYEVJAMqiv-VV-cjj2eyvrDL8sQC-7C94TIa7Ssri-05MFiwNXp2S2g29EUVbYFZAP8CMbe6kDKu2uCqA4O-qqsmxs9lzqpBGpH6RkfbV6jdQgL8Rp4peixkEgutZV1upzLMG0pwrj47W4ikImH31mU3HPVRHOv9m0FOncOYCQUeYtbOvwlPng6ZgUO3ykffewZ-US6kxXMyTtE9oyBZVUAsFmzepgaJ0gw
11:48:09.197 pm
token
Received state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
11:48:09.188 pm
token
Received verification state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
11:48:05.223 pm
token
Function execution started
10:54:47.733 pm
token
Function execution took 2172 ms, finished with status: 'crash'
10:54:47.719 pm
token
Error: The email address is already in use by another account. at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:146:16) at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:185:16) at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1139:49 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
10:54:47.718 pm
token
Unhandled rejection
10:54:46.943 pm
token
Auth code exchange result received: { body: { display_name: 'Marcus Watts', email: 'marc.jwatts@gmail.com', external_urls: { spotify: 'https://open.spotify.com/user/marcz2007' }, followers: { href: null, total: 10 }, href: 'https://api.spotify.com/v1/users/marcz2007', id: 'marcz2007', images: [ [Object] ], type: 'user', uri: 'spotify:user:marcz2007' }, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, max-age=0', vary: 'Authorization', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', date: 'Thu, 25 Jul 2019 21:54:46 GMT', via: '1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 200 }
10:54:46.887 pm
token
Received Access Token: BQBD6NEOeaYljFonsXqsn1jnNa3bG6FwAXpQ9Z0D0o9jUk1dFEBlNvNQ_QhWEGeHaf-4QKxQiRig5UqaljhriqvnQrVI4SSuLQ0VkcdRkQp0ciIWR8CltxJj0t7_2_8LfJMW6h_lu0bGwZFMjMT3ogmP
10:54:46.782 pm
token
Received auth code: AQCqT7w_gMgOvS7eghurdXhZ_zHwC3wLtqP1eNE7s5Q928inzjO1iP84lPWKtV2J_WAoNRmjz8zoylsvnqpciRtOp9KFIbkmQCm3O-CuuNXoz9TYTSCcHPdDqMM2SZIDvp48ooVrBf1Mfp_--2rUWmW6tVnOpsZyhAlvmRM-KbXHfsaImc8ALdfw7R8UVI2YU9ExOx1XcA4k4a4LAb_z7L0T3NXojjWLepNY2hFLbdh9Zu0P2kD057dLvLmA5rsLGDs
10:54:46.782 pm
token
Received state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
10:54:46.780 pm
token
Received verification state: b09b292d06dc746b17ef1ca123d0ad7fc6c96814
10:54:45.561 pm
token
Function execution started
10:51:57.635 pm
token
Function execution took 2171 ms, finished with status: 'crash'
10:51:57.627 pm
token
Error: The email address is already in use by another account. at FirebaseAuthError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseAuthError (/srv/node_modules/firebase-admin/lib/utils/error.js:146:16) at Function.FirebaseAuthError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:185:16) at /srv/node_modules/firebase-admin/lib/auth/auth-api-request.js:1139:49 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
10:51:57.624 pm
token
Unhandled rejection
10:51:56.918 pm
token
Auth code exchange result received: { body: { display_name: 'Marcus Watts', email: 'marc.jwatts@gmail.com', external_urls: { spotify: 'https://open.spotify.com/user/marcz2007' }, followers: { href: null, total: 10 }, href: 'https://api.spotify.com/v1/users/marcz2007', id: 'marcz2007', images: [ [Object] ], type: 'user', uri: 'spotify:user:marcz2007' }, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, max-age=0', vary: 'Authorization', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', date: 'Thu, 25 Jul 2019 21:51:56 GMT', via: '1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 200 }
10:51:56.853 pm
token
Received Access Token: BQBeVrZYtGj2ZgR5S3OVuwRTo__Po43OI79_gXYKYPDyt9B3juysWsyKgAUxvaeva_pA5CuebQxM-72BKk1Q3SrW7MkoDYNvCyaOGEyJLqBuHrRUX38qf6sXT2Sw42rUvJUQo3LQAn_HQNdP1phE6U8Y
10:51:56.760 pm
token
Received auth code: AQAqO2xeUtMs_sbZDhUGkgWkaXf6NdCZYZnZrReUHV3M6uapZX5e_7x93louhYoIIPKNSG5gn9fU8Ij4MJZOrkyazYYBIGIy1ZpblUeSUzqIVNrY8jN65C1bVUbxnsfjIPiQhUWWRS0TfRkM8xZ3lQnQUB-GHymxqd-WCnauOox1XwKIa6W1kZe91GHaOiKO0t5W9tfhfSuLof5cTZNQ3KW6lQZX1SHTJkr5V80zgFcNXn1KyHhlbrWqx3RaTQlqSc8
10:51:56.760 pm

**Comment by marcz2007** [comment]
So I'm getting the access token in these logs which I have just checked and it works when doing a curl command. However I need to be storing the access token in a const in the actual code itself since they expire after one hour. I also need to be able to refresh tokens automatically (since I am writing a voice only Google Assistant app) so I only need to click the sign in with spotify link once. 

Both of which require this page to load properly I presume - can you see from my debug logs any reason why its not?

**Comment by marcz2007** [comment]
*bump*
still facing this error - popup html file is the same as that in the function sample. Any ideas anybody?

**Comment by marcz2007** [comment]
![Screenshot 2019-07-30 at 15 15 39](https://user-images.githubusercontent.com/42185902/62136909-f1282500-b2dc-11e9-9aac-d609a3e1ae7b.png)
I have just entered this request into Postman where it seems to work with 200 response (although I cannot see what the token received is)
<img width="1248" alt="Screenshot 2019-07-30 at 15 16 44" src="https://user-images.githubusercontent.com/42185902/62136976-12891100-b2dd-11e9-84c0-9eedcb003b5f.png">

**Comment by marcz2007** [comment]
I started from scratch and for some reason, the popup screen worked.
