### ISSUE TITLE
Error: The email address is already in use by another account.at FirebaseAuthError.FirebaseError [as constructor] 

### ISSUE THREAD

**Issue by marcz2007** [firebase/functions-samples#591]
### How to reproduce these conditions

Using the sample, I click sign in with spotify and the page just eternally says 'please wait'. The logs appear to say that I have already signed in on another account using the same email address - how do I sign out of this other account so that I can sign in here?

**Sample name or URL where you found the bug**
https://github.com/firebase/functions-samples/tree/master/spotify-auth/functions

**Failing Function code used (including require/import commands at the top)**

`'use strict';
/*
--------------------------- Google/Dialogflow/Firebase Setup ---------------------------
*/

// 	Modules being used
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { WebhookClient } = require('dialogflow-fulfillment');

// File containing service credentials
const serviceAccount = require('./serviceAccountKey.json');

// Initialises the app with the credentials of the firebase account and the database associated with it
admin.initializeApp({
	credential: admin.credential.cert(serviceAccount),
	databaseURL: `https://${process.env.GCLOUD_PROJECT}.firebaseio.com`
});

/*
--------------------------- Spotify Authorisation Request  ----------------------------------------------------------------------------------------
Below is the authorisation code for Spotify including the functions for getting a refresh token and :
*/
var request = require('request');
var express = require('express');
const cookieParser = require('cookie-parser');
const crypto = require('crypto');

// Load the spotify web api node
var SpotifyWebApi = require('spotify-web-api-node');

/**
 * Redirects the User to the Spotify authentication consent screen. Also the 'state' cookie is set for later state
 * verification.
 */
var Spotify = new SpotifyWebApi({
	clientId: '744a1316f9374a27b7ec9bc7eabb0f92',
	clientSecret: '--mysecret--',
	redirectUri: 'https%3A%2F%2Fmood-magic-four-ptwvjb.firebaseapp.com%2Flp.html'
});

// Scopes to request.
const OAUTH_SCOPES = [ 'user-read-email' ];

/**
 * Redirects the User to the Spotify authentication consent screen. Also the 'state' cookie is set for later state
 * verification.
 */
exports.redirect = functions.https.onRequest((req, res) => {
	cookieParser()(req, res, () => {
		const state = req.cookies.state || crypto.randomBytes(20).toString('hex');
		console.log('Setting verification state:', state);
		res.cookie('state', state.toString(), { maxAge: 3600000, secure: true, httpOnly: true });
		const authorizeURL = Spotify.createAuthorizeURL(OAUTH_SCOPES, state.toString());

		res.redirect(authorizeURL);
	});
});

/**
 * Exchanges a given Spotify auth code passed in the 'code' URL query parameter for a Firebase auth token.
 * The request also needs to specify a 'state' query parameter which will be checked against the 'state' cookie.
 * The Firebase custom auth token is sent back in a JSONP callback function with function name defined by the
 * 'callback' query parameter.
 */
exports.token = functions.https.onRequest((req, res) => {
	try {
		cookieParser()(req, res, () => {
			console.log('Received verification state:', req.cookies.state);
			console.log('Received state:', req.query.state);
			if (!req.cookies.state) {
				throw new Error(
					'State cookie not set or expired. Maybe you took too long to authorize. Please try again.'
				);
			} else if (req.cookies.state !== req.query.state) {
				throw new Error('State validation failed');
			}
			console.log('Received auth code:', req.query.code);
			Spotify.authorizationCodeGrant(req.query.code, (error, data) => {
				if (error) {
					throw error;
				}
				console.log('Received Access Token:', data.body['access_token']);
				Spotify.setAccessToken(data.body['access_token']);

				Spotify.getMe(async (error, userResults) => {
					if (error) {
						throw error;
					}
					console.log('Auth code exchange result received:', userResults);
					// We have a Spotify access token and the user identity now.
					const accessToken = data.body['access_token'];
					const spotifyUserID = userResults.body['id'];
					const profilePic = userResults.body['images'][0]['url'];
					const userName = userResults.body['display_name'];
					const email = userResults.body['email'];

					// Create a Firebase account and get the Custom Auth Token.
					const firebaseToken = await createFirebaseAccount(
						spotifyUserID,
						userName,
						profilePic,
						email,
						accessToken
					);
					// Serve an HTML page that signs the user in and updates the user profile.
					res.jsonp({ token: firebaseToken });
				});
			});
		});
	} catch (error) {
		return res.jsonp({ error: error.toString });
	}
	return null;
});

/**
 * Creates a Firebase account with the given user profile and returns a custom auth token allowing
 * signing-in this account.
 * Also saves the accessToken to the datastore at /spotifyAccessToken/$uid
 *
 * @returns {Promise<string>} The Firebase custom auth token in a promise.
 */
async function createFirebaseAccount(spotifyID, displayName, photoURL, email, accessToken) {
	// The UID we'll assign to the user.
	const uid = `spotify:${spotifyID}`;

	// Save the access token to the Firebase Realtime Database.
	const databaseTask = admin.database().ref(`/spotifyAccessToken/${uid}`).set(accessToken);

	// Create or update the user account.
	const userCreationTask = admin
		.auth()
		.updateUser(uid, {
			displayName: displayName,
			photoURL: photoURL,
			email: email,
			emailVerified: true
		})
		.catch((error) => {
			// If user does not exists we create it.
			if (error.code === 'auth/user-not-found') {
				return admin.auth().createUser({
					uid: uid,
					displayName: displayName,
					photoURL: photoURL,
					email: email,
					emailVerified: true
				});
			}
			throw error;
		});

	// Wait for all async tasks to complete, then generate and return a custom auth token.
	await Promise.all([ userCreationTask, databaseTask ]);
	// Create a Firebase custom auth token.
	const token = await admin.auth().createCustomToken(uid);
	console.log('Created Custom token for UID "', uid, '" Token:', token);
	return token;
}
`

**Steps to set up and reproduce**
I have all of the same code from the sample (https://github.com/firebase/functions-samples/tree/master/spotify-auth/functions) plus some of my own functions for dialogflow fulfilment (shown below, albeit I don't think it is important for the errors I am facing):

`
/*
---------------------------Google Assistant Fulfillment----------------------------------------------------------------------------------------
Below is the dialogflow firebase fulfillment code which controls what happens when various intents happen:
*/
exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
	const agent = new WebhookClient({ request, response });

	//53 to 64
	function playSadSong(agent) {
		// Get the database collection 'dialogflow' and document 'agent'
		var randomNumber = Math.floor(Math.random() * (64 - 53 + 1)) + 53;

		return admin.database().ref(`${randomNumber}`).once('value').then((snapshot) => {
			const song = snapshot.child('song').val();
			const artist = snapshot.child('artist').val();

			agent.add(`I will play ${song} by ${artist}`);
		});
	}
	//22 to 53
	function playHappySong(agent) {
		// Get the database collection 'dialogflow' and document 'agent'
		var randomNumber = Math.floor(Math.random() * (53 - 22 + 1)) + 22;

		return admin.database().ref(`${randomNumber}`).once('value').then((snapshot) => {
			const song = snapshot.child('song').val();
			const artist = snapshot.child('artist').val();

			agent.add(`I will play ${song} by ${artist}`);
		});
	}

	//4
	function playAngrySong(agent) {
		// Get the database collection 'dialogflow' and document 'agent'
		var randomNumber = Math.floor(Math.random() * (3 - 3 + 1)) + 3;

		return admin.database().ref(`${randomNumber}`).once('value').then((snapshot) => {
			const song = snapshot.child('song').val();
			const artist = snapshot.child('artist').val();

			agent.add(`I reccomend ${song} by ${artist}`);

			admin.database().ref(`spotifyAccessToken`).once('value').then((snapshot) => {
				const databaseAccessToken = snapshot.child('spotify:marcz2007').val();
				console.log(databaseAccessToken);
				// get Authorization Code

				var request = require('request');

				console.log(Spotify.getAccessToken);
				Spotify.setAccessToken(createFirebaseAccount);
				Spotify.getAudioAnalysisForTrack('4AKUOaCRcoKTFnVI9LtsrN').then(
					function(data) {
						var analysis = console.log('Analyser Version', data.body.meta.analyzer_version);
						var temp = console.log('Track tempo', data.body.track.tempo);
						var tempo = data.body.track.tempo;
						agent.add(
							`The track's tempo is, ${tempo}, does this sound good or would you prefer something else?`
						);
						var textResponse = `The track's tempo is, ${tempo}, does this sound good or would you prefer something else?`;
						agent.add(textResponse);
						agent.add(`Here is the song's tempo: ${tempo}`);
					},
					function(err) {
						console.error(err);
					}
				);
				// agent.add(`${agentSays}`);
				// agent.add(`Here is the audio analysis for a song: ${audioAnalysis}`);
			});
		});

		function createTextResponse(textResponse) {
			let response = {
				fulfillmentText: 'This is a text response',
				fulfillmentMessages: [
					{
						text: {
							text: [ textResponse ]
						}
					}
				],
				source: 'example.com',
				payload: {
					google: {
						expectUserResponse: true,
						richResponse: {
							items: [
								{
									simpleResponse: {
										textToSpeech: 'this is a simple response'
									}
								}
							]
						}
					},
					facebook: {
						text: 'Hello, Facebook!'
					},
					slack: {
						text: 'This is a text response for Slack.'
					}
				}
			};
			return response;
		}
	}

	//5 to 15
	function playConfidentSong(agent) {
		// Get the database collection 'dialogflow' and document 'agent'
		var randomNumber = Math.floor(Math.random() * (15 - 5 + 1)) + 5;

		return admin.database().ref(`${randomNumber}`).once('value').then((snapshot) => {
			const song = snapshot.child('song').val();
			const artist = snapshot.child('artist').val();

			agent.add(`I will play ${song} by ${artist}`);
		});
	}

	// Map from Dialogflow intent names to functions to be run when the intent is matched
	let intentMap = new Map();
	intentMap.set('-Sad - yes', playSadSong);
	intentMap.set('-Happy - yes', playHappySong);
	intentMap.set('-Angry - yes', playAngrySong);
	intentMap.set('-Confident - yes', playConfidentSong);

	agent.handleRequest(intentMap);
});
`

**Sample data pasted or attached as JSON (not an image)**

<img width="1440" alt="Screenshot 2019-07-30 at 11 12 35" src="https://user-images.githubusercontent.com/42185902/62121167-f6747800-b2ba-11e9-9fb8-6a8ba66742b2.png">

These are the logs - as you can see, only the redirect function is used. 

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

### Expected behavior

The expected behaviour is to click 'sign in with spotify' and be taken to the popup screen which, after signing in, reveals my id, email, access token etc. This is then updated automatically by the app using the refresh token so that I can always use the Spotiy web api node. 

### Actual behavior

I get a blank 'please wait' screen. And an error "Error: The email address is already in use by another account.
    at FirebaseAuthError.FirebaseError [as constructor] "

@jhuleatt - this follows from my last post where it was stuck eternally loading the screen. Now it loads it but it never takes me to the second stage of the spotify sign in. 
Please help!

**Comment by marcz2007** [comment]
*update*
After changing the redirect URI back to the popup screen, I am now having the same problems as I was with the previous issue I posted in the thread (https://github.com/firebase/functions-samples/issues/589). If anyone can tell me how to fix the below popup screen code's url I would be extremely grateful!

` /**
   * This callback is called by the JSONP callback of the 'token' Firebase Function with the Firebase auth token.
   */
  function tokenReceived(data) {
    if (data.token) {
      firebase.auth().signInWithCustomToken(data.token).then(function() {
        window.close();
      });
    } else {
      console.error(data);
      document.body.innerText = 'Error in the token Function: ' + data.error;
    }
  }
  var code = getURLParameter('code');
  var state = getURLParameter('state');
  var error = getURLParameter('error');
  if (error) {
    document.body.innerText = 'Error back from the Spotify auth page: ' + error;
  } else if(!code) {
    // Start the auth flow.
    window.location.href  = 'https://us-central1-' + getFirebaseProjectId() + '.cloudfunctions.net/redirect';
  } else {
    // Use JSONP to load the 'token' Firebase Function to exchange the auth code against a Firebase custom token.
    const script = document.createElement('script');
    script.type = 'text/javascript';
    // This is the URL to the HTTP triggered 'token' Firebase Function.
    // See https://firebase.google.com/docs/functions.
    var tokenFunctionURL = 'https://us-central1-' + getFirebaseProjectId() + '.cloudfunctions.net/token';
    script.src = tokenFunctionURL +
        '?code=' + encodeURIComponent(code) +
        '&state=' + encodeURIComponent(state) +
        '&callback=' + tokenReceived.name;
    document.head.appendChild(script);
  }`

**Comment by marcz2007** [comment]
After starting from scratch, this time it works. Not sure what the issue was

**Comment by vaibhavkumar049** [comment]
@marcz2007 I am trying to make a chat app using dialogflow in flutter, I wanted to know how to send uid of the user to firebase function so that we can save the data for each unique user
