### ISSUE TITLE
npm ERR! code EBADF npm ERR! errno -4083 npm ERR! syscall close npm ERR! EBADF: bad file descriptor, close

### ISSUE THREAD

**Issue by Hamza-Rafique** [firebase/functions-samples#604]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by jhuleatt** [comment]
Hey @Hamza-Rafique, looks like you didn't fill out any fields in the issue template. Please do that so I can help.

**Comment by Hamza-Rafique** [comment]
i'm new on github so i forgit ....thank u so much

**Comment by Hamza-Rafique** [comment]
i am new on github i forgit this sorry and this for help
