### ISSUE TITLE
Firebase Upload

### ISSUE THREAD

**Issue by Atlas789** [firebase/functions-samples#615]
How can I upload text, image and pdf file at the same time under one root?

**Comment by puf** [comment]
Crossposted from https://stackoverflow.com/questions/57863115/how-to-upload-image-file-and-text-at-the-same-time-using-async-task-in-the-fire

**Comment by krharsh17** [comment]
Can you describe a real-time situation where this can be implemented?

**Comment by Atlas789** [comment]
for mobile library in which it shows image of the book and when you click it will be downloaded can be viewed.

**Comment by krharsh17** [comment]
For that, I think that the best solution would be to create a common ID for all of the related files(text, image, pdf), create a folder with the name same as that ID, upload the three files into that folder with their names as the same ID, and only varying the extension ie. .pdf for PDF, .jpeg for image etc

**Comment by Atlas789** [comment]
The problem is in the coding.

**Comment by allanpaul506** [comment]
Anyone with good firebase link shorter

**Comment by Atlas789** [comment]
I fixed my problem
