### ISSUE TITLE
Analytics event trigger response time

### ISSUE THREAD

**Issue by zhuhw** [firebase/functions-samples#62]
I have a question regarding the analytics event trigger.

I am able to create a webhook that sends message to slack using `functions.https` trigger, and it happens almost instantly.
How long does it take between the moment that the event is fired and the execution of the function? Is it in real-time?

**Comment by nicolasgarnier** [comment]
Hey @zhuhw as mentioned in [the docs](https://firebase.google.com/docs/functions/analytics-events) there might be a delay of up to 2 hours after the **first deployment** of a function for a particular event:

![image](https://cloud.githubusercontent.com/assets/3766663/24198238/5881c7e8-0f05-11e7-9c84-777962cc72d6.png)

After that there should be no delays. If this still does not help please reach out for further help via our [support/community channels](https://firebase.google.com/support/).
