### ISSUE TITLE
Missing correct termination in scheduled example

### ISSUE THREAD

**Issue by murilolobato** [firebase/functions-samples#620]
Hello,

I've just noticed that the [scheduled function example](https://github.com/firebase/functions-samples/blob/master/delete-unused-accounts-cron/functions/index.js), doesn't have a return value. I think that maybe `promisePool.start();` could be returned because it is a promise.

I noticed this while reading the docs at: https://firebase.google.com/docs/functions/terminate-functions

Let me know if what I related is correct, that being I can make a PR to improve the example :)

**Comment by jhuleatt** [comment]
Because the function `accountcleanup` uses `async`/`await` syntax, it automatically returns a promise.
