### ISSUE TITLE
Real-world scenario guide with cutting edge tech

### ISSUE THREAD

**Issue by IlCallo** [firebase/functions-samples#627]
I made up a guide to setup Firebase services into a real-world scenario with cutting-edge technologies. I think you could get some insights on DX of your services and how they are used out in the wild (or add it to this examples repository).
Tech used: Quasar (Vue), TypeScript, Jest (unit testing), Firebase Firestore, Cloud Functions, RxFire.

Inside the guide there are some helpers and code management tips which can make dev life easier and could be integrated into some of your products.
Feel free to take copy-paste-change them and use them to enhance your documentation.
Suggestions and comments are welcome too.

https://github.com/quasarframework/app-extension-firebase/issues/4

Cheers!

**Comment by jhuleatt** [comment]
Hi @IlCallo, if you're interested, you're welcome to create a PR to add a link to your repository to our community page: https://github.com/firebase/functions-samples/blob/master/community.md
