### ISSUE TITLE
Update Sample "Next.js with Firebase Hosting Rewrites" to use Next.js serverless deployment

### ISSUE THREAD

**Issue by ryanberckmans** [firebase/functions-samples#633]
Please consider updating https://github.com/firebase/functions-samples/tree/master/nextjs-with-firebase-hosting to use https://nextjs.org/docs#serverless-deployment.

In particular I have found the [existing caveat](https://github.com/firebase/functions-samples/tree/master/nextjs-with-firebase-hosting#important--caveats) _Any npm modules dependencies used in the Next.js app (app/ folder) must also be installed as dependencies for the Cloud Functions project (functions folder)_ to be troublesome and am wondering if use of Next.js's serverless deployment may alleviate this.

**Comment by jhuleatt** [comment]
Cool! Thanks for bringing this up, @ryanberckmans. I'll look into it, but this might take me a while to get to. Definitely open to PRs if someone else wants to give it a try!

**Comment by robertcasanova** [comment]
I'm working on something like this with two functions one for next Api Routes and another for SSR but i'm not sure is what you are looking for. Just let me know.. thx  https://github.com/robertcasanova/next-firebase-demo

**Comment by jhuleatt** [comment]
We've decided to remove this sample from the repo since it was difficult to maintain (#804)

@robertcasanova would you be interested in creating a PR to add a link to your repo to https://github.com/firebase/functions-samples/blob/master/community.md ?
