### ISSUE TITLE
firebase function deploy error

### ISSUE THREAD

**Issue by minemos** [firebase/functions-samples#645]
### There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

**Setting for Project**
Node.js -> 10
NVM -> 8.16.2
NPM -> 6.13.4
Firebase-Tools -> 7.9.0

### Debug output

**Errors in console**

Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

**Errors in log**
[debug] [2019-12-13T13:21:06.790Z] ----------------------------------------------------------------------
[debug] [2019-12-13T13:21:06.791Z] Command:       /Users/minemos/.nvm/versions/node/v8.16.2/bin/node /usr/local/bin/firebase deploy --only functions
[debug] [2019-12-13T13:21:06.792Z] CLI Version:   7.9.0
[debug] [2019-12-13T13:21:06.792Z] Platform:      darwin
[debug] [2019-12-13T13:21:06.792Z] Node Version:  v8.16.2
[debug] [2019-12-13T13:21:06.792Z] Time:          Fri Dec 13 2019 22:21:06 GMT+0900 (KST)
[debug] [2019-12-13T13:21:06.792Z] ----------------------------------------------------------------------
[debug] [2019-12-13T13:21:06.792Z] 
[debug] [2019-12-13T13:21:06.798Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-12-13T13:21:06.799Z] > authorizing via signed-in user
[debug] [2019-12-13T13:21:06.799Z] [iam] checking project togetherc-we for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2019-12-13T13:21:06.800Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/togetherc-we:testIamPermissions  

[debug] [2019-12-13T13:21:07.745Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'togetherc-we'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2019-12-13T13:21:14.448Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "algoliasearch": "^3.35.1",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "file-type": "^12.2.0",
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.2.0",
    "fs-extra": "^8.1.0",
    "mailgun-js": "^0.22.0",
    "multer": "^1.4.2",
    "sharp": "^0.22.1",
    "video-thumbnail-generator": "^1.1.3"
  },
  "devDependencies": {
    "@types/algoliasearch": "^3.30.14",
    "@types/cors": "^2.8.6",
    "@types/file-type": "^10.9.1",
    "@types/fs-extra": "^8.0.0",
    "@types/mailgun-js": "^0.22.2",
    "@types/multer": "^1.3.7",
    "@types/node": "^12.12.5",
    "@types/sharp": "^0.22.2",
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2019-12-13T13:21:14.449Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/togetherc-we/services/cloudfunctions.googleapis.com  
 
[debug] [2019-12-13T13:21:14.449Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/togetherc-we/services/runtimeconfig.googleapis.com  
 
[debug] [2019-12-13T13:21:15.671Z] <<< HTTP RESPONSE 200
[debug] [2019-12-13T13:21:15.712Z] <<< HTTP RESPONSE 200
[info] ✔  functions: all necessary APIs are enabled
[debug] [2019-12-13T13:21:15.713Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/togetherc-we/adminSdkConfig  
 
[debug] [2019-12-13T13:21:16.649Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2019-12-13T13:21:16.651Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/togetherc-we/configs  
 
[debug] [2019-12-13T13:21:17.263Z] <<< HTTP RESPONSE 200
[debug] [2019-12-13T13:21:17.264Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/togetherc-we/configs/algolia/variables  
 
[debug] [2019-12-13T13:21:17.646Z] <<< HTTP RESPONSE 200
[debug] [2019-12-13T13:21:17.648Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/togetherc-we/configs/algolia/variables/admin/key  
 
[debug] [2019-12-13T13:21:17.648Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/togetherc-we/configs/algolia/variables/app  
 
[debug] [2019-12-13T13:21:18.082Z] <<< HTTP RESPONSE 200
[debug] [2019-12-13T13:21:18.084Z] <<< HTTP RESPONSE 200
[error] 
[error] Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

### Expected behavior

Like other project... this have to deploy in firebase but not

### Actual behavior

![Screen Shot 2019-12-13 at 10 25 45 PM](https://user-images.githubusercontent.com/24834933/70803475-8264e780-1df7-11ea-8c3a-78f531280f9a.png)

**Comment by jhuleatt** [comment]
@minemos can you deploy if you change your functions code to a really simple "hello world" function? Something like:

```js
const functions = require('firebase-functions');

exports.helloWorld = functions.https.onRequest((request, response) => {
  response.send("Hello from Firebase!");
});
```

If you can't deploy even that, please [reach out to support](https://firebase.google.com/support/troubleshooter/functions/deploy/) with your debug log.
