### ISSUE TITLE
firebase push notification with php

### ISSUE THREAD

**Issue by spike99** [firebase/functions-samples#653]
0

I want to store firebase token in mysql table, because I want to send push notification

how can i get this token also in php?

`  <div id="token"></div>
    <div id="msg"></div>
    <div id="notis"></div>
    <div id="err"></div>
    <script src="https://www.gstatic.com/firebasejs/7.2.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.2.1/firebase-messaging.js"></script>
    
    <script src="https://www.gstatic.com/firebasejs/7.2.1/firebase-analytics.js"></script>
    <script>
        MsgElem = document.getElementById("msg");
        TokenElem = document.getElementById("token");
        NotisElem = document.getElementById("notis");
        ErrElem = document.getElementById("err");
        // Initialize Firebase
        // TODO: Replace with your project's customized code snippet
        var config = {
    apiKey: "xxx",
    authDomain: "xxx.firebaseapp.com",
    databaseURL: "https://api-xxx.firebaseio.com",
    projectId: "api-xxx",
    storageBucket: "api-xxx.appspot.com",
    messagingSenderId: "xxx",
    appId: "xxx"
        };
        firebase.initializeApp(config);

        const messaging = firebase.messaging();
        messaging
            .requestPermission()
            .then(function () {
                MsgElem.innerHTML = "Notification permission granted." 
                console.log("Notification permission granted.");

                // get the token in the form of promise
                return messaging.getToken()
            })
            .then(function(token) {
                TokenElem.innerHTML = "token is : " + token
            })
            .catch(function (err) {
                ErrElem.innerHTML =  ErrElem.innerHTML + "; " + err
                console.log("Unable to get permission to notify.", err);
            });

    </script>`

**Comment by samtstern** [comment]
@spike99 sorry for the slow response here.  This issue tracker is only for questions about the code in this repo.  For questions about PHP or anything else please try a general programming forum like StackOverflow.
