### ISSUE TITLE
sending auth token in Dialogflow fullfillment 

### ISSUE THREAD

**Issue by vaibhavkumar049** [firebase/functions-samples#658]
I am trying to create a chat app in flutter using dialogflow , for the fulfillment I am using firebase function. My problem is I am trying to save some data from chat for each unique user. For that, I am trying to get  uid of each user , what are the option that I have here? and how to achieve that.
I am trying a not so good approach like by pressing the send button I am sending uid to another firebase function and then using that uid to dialog flow fulfillment function, but that doesn't seem to work. In dialogflow req headers I am not getting anything . How to achieve this

**Comment by samtstern** [comment]
@vaibhavkumar049 sorry for the slow response here.  This issue tracker is only for issues about the sample code in this repo.  For general questions please try a forum like StackOverflow.
