### ISSUE TITLE
Firebase Deploy error - There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater

### ISSUE THREAD

**Issue by eliaweiss** [firebase/functions-samples#659]
I'm getting `There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater`

when trying to do `firebase deploy --only functions`

I tried with `node -v v10.10.0` `node -v v8.11.1` `node -v v10.15.3`

Background: this is a project that I develop 6 month ago, it worked with no issue, but today I tried to re-deploy (no changes in the code) and I get this error.

I have no idea how to work from here, would appreciate any idea.

here is the full log:

    firebase deploy --only functions

    === Deploying to 'invoice-manager-251609'...

    i  deploying functions
    Running command: npm --prefix "$RESOURCE_DIR" run lint

    > functions@ lint D:\work\ocr\receiptWeb\functions
    > eslint .

    D:\work\ocr\receiptWeb\functions\index.js
      127:25  warning  Avoid nesting promises              promise/no-nesting
      127:25  warning  Avoid nesting promises              promise/no-nesting
      128:35  warning  Don't make functions within a loop  no-loop-func
      132:40  warning  Avoid nesting promises              promise/no-nesting
      132:40  warning  Avoid nesting promises              promise/no-nesting
      134:44  warning  Avoid nesting promises              promise/no-nesting
      146:38  warning  Don't make functions within a loop  no-loop-func
      424:28  warning  Avoid nesting promises              promise/no-nesting
      424:28  warning  Avoid nesting promises              promise/no-nesting
      465:28  warning  Avoid nesting promises              promise/no-nesting
      465:28  warning  Avoid nesting promises              promise/no-nesting

    D:\work\ocr\receiptWeb\functions\ReceiptGv.js
      368:43  warning  Don't make functions within a loop  no-loop-func

    ✖ 12 problems (0 errors, 12 warnings)

    +  functions: Finished running predeploy script.
    i  functions: ensuring necessary APIs are enabled...
    +  functions: all necessary APIs are enabled
    i  functions: preparing functions directory for uploading...

    Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.

NOTE: the warnings are not new, and I could deploy the project with them in the past.

sometimes it gives this addiation line `Having trouble? Try again or contact support with contents of firebase-debug.log`

but I couldn't find any info about `firebase-debug.log` in google.

**Comment by samtstern** [comment]
@eliaweiss sorry about the slow response here!  Make sure you're using the latest version of the Firebase CLI.  If you're still experiencing this issue please write in to Firebase Support (firebase.google.com/support) since they can help you troubleshoot.
