### ISSUE TITLE
Convert Images GCS Bucket error

### ISSUE THREAD

**Issue by amitava82** [firebase/functions-samples#66]
Hi, I'm trying out the image resizing demo. Deployment throwing error:
```
 Deploy Error: Failed to configure trigger GCS Bucket: product_images
```
My images are inside `product_images` folder and my code looks like this:
```

exports.generateThumbnail = functions.storage.object().onChange(event => {
  const object = event.data;
  const fileBucket = object.bucket;
  const filePath = object.name;
  const contentType = object.contentType;
  const resourceState = object.resourceState;

  if(!filePath.match(/product_images/)) {
    console.log('not product_images bucket');
    return;
  }

  if (!contentType.startsWith('image/')) {
    console.log('This is not an image.');
    return;
  }

  const fileName = filePath.split('/').pop();
  // Exit if the image is already a thumbnail.
  if (fileName.startsWith('thumb_')) {
    console.log('Already a Thumbnail.');
    return;
  }

  if (resourceState === 'not_exists') {
    console.log('This is a deletion event.');
    return;
  }

  const bucket = gcs.bucket(fileBucket);
  const tempFilePath = `/tmp/${fileName}`;

  return bucket.file(filePath).download({
    destination: tempFilePath
  }).then(() => {
    console.log('Image downloaded locally to', tempFilePath);
    // Generate a thumbnail using ImageMagick.
    return spawn('convert', [tempFilePath, '-thumbnail', '64x64>', tempFilePath]).then(() => {
      console.log('Thumbnail created at', tempFilePath);
      // We add a 'thumb_' prefix to thumbnails file name. That's where we'll upload the thumbnail.
      const thumbFilePath = filePath.replace(/(\/)?([^\/]*)$/, `$1thumb_$2`);
      // Uploading the thumbnail.
      return bucket.upload(tempFilePath, {
        destination: thumbFilePath
      });
    });
  });
});
```
Not sure what it means.

**Comment by nicolasgarnier** [comment]
Can you tell us a bit more about when the deploy error happens? Is that when you are running the CLI `firebase deploy`? Can you copy paste the full output off the CLI?

**Comment by amitava82** [comment]
Exactly, during deployment process. I've searching more about this, and it seems we need to have billing enabled and firebase store and google cloud store are two different products. My understanding was that the image resizing function works on firebase store which apparently is not correct. My use case is, when someone uploads file to firebase store (using firebase client) I want to resize image using cloud function. Could you please clarify if that's possible? 

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (2.63 KB) for uploading
✔  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: updating function addTag...
i  functions: updating function adjustments...
i  functions: updating function generateThumbnail...
⚠  functions[generateThumbnail]: Deploy Error: Failed to configure trigger GCS Bucket: product_images
✔  functions[addTag]: Successful update operation.
✔  functions[adjustments]: Successful update operation.
✔  functions: 2 function(s) deployed successfully.
```

**Comment by nicolasgarnier** [comment]
Can you change:

`exports.generateThumbnail = functions.storage.bucket().object().onChange(event => {`

to:

`exports.generateThumbnail = functions.storage.object().onChange(event => {`

?

It looks like Functions thinks you want a trigger on the bucket named `product_images` which would happened if your code was:

`exports.generateThumbnail = functions.storage.bucket('product_images').object().onChange(event => {`

Even if that works, could you paste what you have in your code above so we can investigate?

**Comment by amitava82** [comment]
This is what I have, same as you suggested.
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const gcs = require('@google-cloud/storage')();
const spawn = require('child-process-promise').spawn;

exports.generateThumbnail = functions.storage.object().onChange(event => {
  const object = event.data;
  const fileBucket = object.bucket;
  const filePath = object.name;
  const contentType = object.contentType;
  const resourceState = object.resourceState;

  if(!filePath.match(/product_images/)) {
    console.log('not product_images bucket');
    return;
  }

  if (!contentType.startsWith('image/')) {
    console.log('This is not an image.');
    return;
  }

  const fileName = filePath.split('/').pop();
  // Exit if the image is already a thumbnail.
  if (fileName.startsWith('thumb_')) {
    console.log('Already a Thumbnail.');
    return;
  }

  if (resourceState === 'not_exists') {
    console.log('This is a deletion event.');
    return;
  }

  const bucket = gcs.bucket(fileBucket);
  const tempFilePath = `/tmp/${fileName}`;

  return bucket.file(filePath).download({
    destination: tempFilePath
  }).then(() => {
    console.log('Image downloaded locally to', tempFilePath);
    // Generate a thumbnail using ImageMagick.
    return spawn('convert', [tempFilePath, '-thumbnail', '64x64>', tempFilePath]).then(() => {
      console.log('Thumbnail created at', tempFilePath);
      // We add a 'thumb_' prefix to thumbnails file name. That's where we'll upload the thumbnail.
      const thumbFilePath = filePath.replace(/(\/)?([^\/]*)$/, `$1thumb_$2`);
      // Uploading the thumbnail.
      return bucket.upload(tempFilePath, {
        destination: thumbFilePath
      });
    });
  });
});
```

**Comment by inlined** [comment]
This looks like it's a backend issue. I can investigate; do we have permission to view logs related to your account?

**Comment by amitava82** [comment]
@inlined Sure! Let me know if anything is required.

**Comment by inlined** [comment]
I found a stack trace in our backend; since this conversation includes details about your personal app I'm going to reach out to you at the email address listed on your GitHub profile.

**Comment by inlined** [comment]
For posterity: Cloud Functions requires editor permission on your project.

**Comment by nicolasgarnier** [comment]
FYI this issue is somewhat widespread because we used to have a bug (as of 1-2 month ago) where lots of Cloud Storage Buckets were created with the wrong permissions. New projects don't have this issue but if you have an old Firebase project which is impacted by this the manual fix for your permissions is described here:

https://github.com/firebase/friendlychat/issues/184#issuecomment-290914672

**Comment by amitava82** [comment]
Yes @inlined mailed me with details. I'm guessing the particular project I was working on was affected by the bug. It worked fine with a new project.

**Comment by nicolasgarnier** [comment]
Glak you got it sorted @amitava82 !

I'm changing the title and added the comment above so that it's easier to find for other developers that might be infected.

**Comment by carllippert** [comment]
Just had this happen with a Realtime Database trigger for firebase. Should I report as bug? Trigger has not been edited and has worked previously.

**Comment by inlined** [comment]
Please contact support directly. GitHub bugs are for bugs with the SDK.

**Comment by shadow1349** [comment]
I am still getting this issue with a project I created a few weeks ago. I have all the correct permissions as well as setting the storage rules to be completely open to read/write. I want to set a trigger on a specific bucket only like 

```
export const imageUploaded = functions.storage
.bucket("mybucket").object().onChange(  event => {
    //code
});
```
any idea how to fix this?

**Comment by shadow1349** [comment]
@inlined I am getting this exact same issue. Would you mind having a look for me?

https://stackoverflow.com/questions/48901888/firebase-storage-trigger-not-working

**Comment by PierBover** [comment]
I'm having the same issue.

I'm deploying a function and getting `Failed to configure trigger GCS Bucket`.

I'm declaring the function as required per [the docs](https://firebase.google.com/docs/functions/gcp-storage-events):
```
functions.storage.object().onFinalize((object) => {...})
```

This exact same function deploys ok on another project.

**Comment by aldoromo88** [comment]
I was having the same problem.
Apparently it is caused by missing permission on service account executing cloud function.

I just added `Storage Object Admin` role to default to default service account and everything start to work as expected.  
![image](https://user-images.githubusercontent.com/2552738/39852899-ddae4f20-53e4-11e8-87eb-bf552a1c4deb.png)

**Comment by clement89** [comment]
I have added permission but still not working for me

**Comment by peterwarbo** [comment]
I started receiving these messages as well with a newly created firebase project. It was working previously with my old project.

**Comment by mparpaillon** [comment]
Same for me. I've tried everything I could find online (changing IAM, adding roles, updating permissions...) but the deploy won't work. Even with a new project. My other project (created a year ago) works fine though...

**Comment by mparpaillon** [comment]
@peterwarbo I haven't changed a thing and now it works for me. Could you try again ?

**Comment by peterwarbo** [comment]
@mparpaillon ah, will try again. Maybe it was a temporary outage with storage 😊
