### ISSUE TITLE
404 error when following exact instructions for this example

### ISSUE THREAD

**Issue by grantbrewster** [firebase/functions-samples#663]
### How to reproduce these conditions

Use the exact code from the example, which imports the ui at 4.4.0

**Failing Function code used (including require/import commands at the top)**
the code fails at line 8 

```html
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/4.4.0/firebaseui.css" />
```
and line 110
```html
    <script src="https://cdn.firebase.com/libs/firebaseui/4.4.0/firebaseui.js"></script>
```

Works fine with */firebaseui/4.3.0/firebaseui.js

**Screenshots**

### Expected behavior

It should look like the firestripe payforallthings example, but instead doesn't correctly allow for google auth.

### Actual behavior

<img width="997" alt="Screen Shot 2020-01-17 at 12 49 59 PM" src="https://user-images.githubusercontent.com/44684825/72578684-e022ad00-392a-11ea-8376-44555893cc3a.png">

**Comment by grantbrewster** [comment]
Update: reverting to 4.3.0 is no longer working. I don't know what the issue is here.

**Comment by Noobulater** [comment]
+1

**Comment by j0nimost** [comment]
Currently I'm facing the same issue

**Comment by jhuleatt** [comment]
@grantbrewster thanks for filing! 

the fix is to use https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth.js and https://www.gstatic.com/firebasejs/ui/4.3.0/firebase-ui-auth.css instead.

@wti806 do you know why cdn.firebase.com stopped working for firebaseui-web?
