### ISSUE TITLE
Not deleting original audio file in bucket cloud storage

### ISSUE THREAD

**Issue by abhishekwebcode** [firebase/functions-samples#674]
https://github.com/firebase/functions-samples/blob/0ba49374ed7b8cfe1a96b74b0ed9826d12fe1a7d/ffmpeg-convert-audio/functions/index.js#L81

Hereafter doing all the work,

we have 4 references to files

1. The original audio file which was uploaded currently residing in the bucket (such as .mp3 on cloud storage which originally triggered this function)
2. The temporary copy of (1)
3. The converted local copy of (2)
4. The converted copy of (3) on the cloud storage bucket

Here we are deleting 2 and 3, 4 is our needed output but I am confused as to why we are not deleting the file (1)
Since the conversion is successful, we should be deleting the (1) file from the bucket to avoid storage leaks

If I am not aligned to the original intention of this cloud functions example, kindly let me know

Thanks

**Comment by jhuleatt** [comment]
Hey @abhishekwebcode it would be fine to delete the original file. Depending on your use case, it may be helpful to keep the original (for example, if the user expects their original file to exist somewhere, or if you might want to process it multiple ways). But definitely fine to delete the original file if it fits your use case.
