### ISSUE TITLE
SigningError: Could not get credentials without a JSON, pem, or p12 keyfile.

### ISSUE THREAD

**Issue by tsaarikivi** [firebase/functions-samples#68]
Here is the error
>error getting thumbnail url { SigningError: Could not get credentials without a JSON, pem, or p12 keyfile.
    at /user_code/node_modules/@google-cloud/storage/src/file.js:1463:16
    at /user_code/node_modules/@google-cloud/storage/node_modules/google-auto-auth/index.js:112:7
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  message: 'Could not get credentials without a JSON, pem, or p12 keyfile.' }

Here is the code
>const file = fb.bucket.file(thumbFilePath)
                file.getSignedUrl({
                  action: 'read',
                  expires: '03-17-2025'
                })

**Comment by katowulf** [comment]
Hello Tero, I don't see `fb.bucket.file(thumbFilePath)` in any of the sample apps. Are you sure this is a question about functions-samples and not better suited for our [community/support channels](https://firebase.google.com/support/)?

**Comment by tsaarikivi** [comment]
Yes it is! Thanks!
