### ISSUE TITLE
Missing documentation about Security Rules - timestamp

### ISSUE THREAD

**Issue by geeksilva97** [firebase/functions-samples#688]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
https://firebase.google.com/docs/reference/rules/rules.timestamp

**Failing Function code used (including require/import commands at the top)**
I tried to learn more about timestamps in security rules but the link is crashed.

**Steps to set up and reproduce**
Access the link at https://firebase.google.com/docs/reference/rules/rules.timestamp

**Screenshots**

### Expected behavior
Documentation about it

### Actual behavior
NOT FOUND 404

**Comment by geeksilva97** [comment]
This is not a bug. In fact, I didn't know where to open a problem like that. Sorry if I was wrong to put it here.

**Comment by jhuleatt** [comment]
Hi @geeksilva97, I'm going to close this since it isn't related to the functions-samples repo. For now, you can access that page directly with [this link](https://firebase.google.com/docs/reference/rules/rules.Timestamp), but I've reported the problem to Firebase tech writers and we'll get it fixed soon.

**Comment by geeksilva97** [comment]
> Hi @geeksilva97, I'm going to close this since it isn't related to the functions-samples repo. For now, you can access that page directly with [this link](https://firebase.google.com/docs/reference/rules/rules.Timestamp), but I've reported the problem to Firebase tech writers and we'll get it fixed soon.

Thanks @jhuleatt 
I'm on Slack now too. Very thankful.
