### ISSUE TITLE
functions predeploy error: Command terminated with non-zero exit code2

### ISSUE THREAD

**Issue by Vijay1126** [firebase/functions-samples#709]
Hey everyone, I just started with the first tutorial "Getting Started with Cloud Functions for Firebase using TypeScript - Firecasts" on YouTube. 
While trying to deploy the code, I get the error shown below.

Device: Macbook Pro 
Node version: v12.16.3
Typescript version: version 3.8.3

### Expected behavior

Deploy successfully

### Actual behavior

```
vijayraja@Vijays-MBP functions % firebase deploy

=== Deploying to 'pleasework-770e8'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/vijayraja/newfire/functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /Users/vijayraja/newfire/functions
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value is never read.

1 import * as functions from 'firebase-functions';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vijayraja/.npm/_logs/2020-04-29T06_39_58_655Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code2
```

I have attached the all the screenshots below:

Error:
![image](https://user-images.githubusercontent.com/63943580/80567540-64bda680-89c3-11ea-98cf-114a1f49cb72.png)

My index.ts file : 
![image](https://user-images.githubusercontent.com/63943580/80568195-908d5c00-89c4-11ea-8aa9-99a403c76508.png)

Firebase.json file:
![image](https://user-images.githubusercontent.com/63943580/80568213-9be08780-89c4-11ea-82f1-3a7fb2ac6911.png)

tsconfig.json file:
![image](https://user-images.githubusercontent.com/63943580/80568233-a569ef80-89c4-11ea-905c-96439d4afa01.png)

package.json file:
![image](https://user-images.githubusercontent.com/63943580/80568247-adc22a80-89c4-11ea-9047-0b7cc4fcaf4f.png)

I'm aware there are other threads with the same issue, but I tried all of them, none of them worked. 
What I tried doing:
1. Place the "typeRoots" key inside "compilerOptions" (https://github.com/firebase/firebase-tools/issues/749)
2. npm run build and restart VSCode (https://github.com/firebase/firebase-tools/issues/749)

Please help.

**Comment by Vijay1126** [comment]
@morganchen12

**Comment by jhuleatt** [comment]
@Vijay1126 did you save your index.ts file before trying to deploy? That's a linter error that's saying the `functions` variable defined in line 1 of index.ts isn't used. You use it in line 6, so I think it's just a matter of saving that file and trying again 😄

**Comment by Vijay1126** [comment]
THANK YOU!
