### ISSUE TITLE
Signed URLs for images not generated in Firebase database?

### ISSUE THREAD

**Issue by Abdul-Aziz-Kamboh** [firebase/functions-samples#711]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by jhuleatt** [comment]
Closing for not following the issue template. @Abdul-Aziz-Kamboh please open a new issue with more context if you'd still like help.
