### ISSUE TITLE
firestore x-algolia-application-id

### ISSUE THREAD

**Issue by ckhzb** [firebase/functions-samples#716]
I leaning algolia and following [fulltext-search-firestore](https://github.com/firebase/functions-samples/tree/master/fulltext-search-firestore).
When I save data to algolia, firebase functions show this message:

> Error: "value" required in setHeader("x-algolia-application-id", value)
>     at validateHeader (_http_outgoing.js:489:11)
>     at ClientRequest.setHeader (_http_outgoing.js:498:3)
>     at new ClientRequest (_http_client.js:183:14)
>     at Object.request (http.js:39:10)
>     at Object.request (https.js:245:15)
>     at resolve (/srv/node_modules/@algolia/requester-node-http/dist/requester-node-http.cjs.js:27:72)
>     at new Promise (<anonymous>)
>     at Object.send (/srv/node_modules/@algolia/requester-node-http/dist/requester-node-http.cjs.js:16:20)
>     at retry (/srv/node_modules/@algolia/transporter/dist/transporter.cjs.js:215:38)
>     at createRetryableOptions.then.options (/srv/node_modules/@algolia/transporter/dist/transporter.cjs.js:228:16) 

I have no idea how to fix it.

>Firebase is Blaze mode

> package.json
> "engines": {
>     "node": "8"
>   },
>   "dependencies": {
>     "algoliasearch": "^4.2.0",
>     "firebase-admin": "^8.12.1",
>     "firebase-functions": "^3.6.1",
>   },

**Comment by jhuleatt** [comment]
Hi @ckhzb , that sample uses `functions.config` to store Algolia API keys: https://github.com/firebase/functions-samples/blob/dd1fd430d9e2603694a0fe234ac8831a164b22bb/fulltext-search-firestore/functions/index.js#L20-L29

You'll need to [set those values](https://firebase.google.com/docs/functions/config-env#set_environment_configuration_for_your_project) for the function to work.

**Comment by ckhzb** [comment]
@jhuleatt thank you
