### ISSUE TITLE
quickstarts/big-ben didn't work when following the listed instructions

### ISSUE THREAD

**Issue by instance-id** [firebase/functions-samples#720]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
https://github.com/firebase/functions-samples/tree/master/quickstarts/big-ben

**Failing Function code used (including require/import commands at the top)**
I didn't change any code, it is exactly what was included in the example.

After following the steps, I went to run : ```firebase serve --only hosting,functions``` as directed on line 41 of the [README.md](https://github.com/firebase/functions-samples/blob/master/quickstarts/big-ben/README.md#L41) but received the error of:

```sh
❯ firebase serve --only hosting,functions                   

=== Serving from 'E:\GitHub\functions-samples\quickstarts\big-ben'...
Error: Cannot understand what targets to deploy. Check that you specified valid targets if you used the --only or --except flag. Otherwise, check your firebase.json to ensure that your project is initialized for the desired features.
```
After finding a post on StackOverflow, I saw someone was using an emulator, so I attempted to do the same by enabling emulators under the firebase init setup, which then changed my firebase.json to the below:
```json
{
  "hosting": {
    "public": "public",
    "rewrites": [
      {
        "source": "**",
        "function": "app"
      }
    ]
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "hosting": {
      "port": 5000
    }
  }
}

```
I then tried to do simply  ```firebase serve``` but was told I needed to then run ```npm install``` inside the functions folder. Doing so then let me back out and run firebase serve again, then the sample worked.

I am brand new to Firebase in general (I created a flutter app over the last few weeks that uses it for authentication and database) but this is my first attempt at touching Firebase functions, so I am guessing I must have done something incorrectly, as getting it to work seemed way outside of what the instructions say is needed to get it to work. 

I am not sure if the instructions are not up to date with the current Firebase CLI, or if they are perhaps missing a step or additional information as trying to run it after the fact of it working this way while trying to use the listed instructions still ended up giving the same error.

Thanks,
-id

**Comment by instance-id** [comment]
Also, the Webhooks one, it instructs you to use a website that no longer exists and doesn't have all of the necessary files for it to work out of the box either. I was able to get it working eventually though using http://pipedream.net

**Comment by jhuleatt** [comment]
Hi @instance-id, I'm not able to reproduce the `Cannot understand what targets to deploy` error, but I created #725 to address your `npm install` feedback.

I'm thinking this might be a case of not being on the latest version of the firebase CLI. Can you please run `npm i -g firebase-tools` and try again?

If that doesn't fix it, please run `firebase serve --debug` and paste the output in here.

-------------

Please file a separate issue for the Webhooks sample so that we can keep this focused on big-ben
