### ISSUE TITLE
'Firestripe' sample is not live

### ISSUE THREAD

**Issue by Elijer** [firebase/functions-samples#724]
In this helpful article in the docs it refers a couple times to a [live version of the Firestripe example here
]( https://firebase.google.com/docs/use-cases/payments)

This would be really helpful to see for comparison, as stated in the article. [However, here is the link](
https://payforallthethings.firebaseapp.com/).

It displays a "site not found message". This is a bummer! I want to see it. Why is it not deployed?

**Comment by jhuleatt** [comment]
Thanks for reporting @Elijer.

I've filed a bug internally to see what happened and if we can redeploy to that URL. For any Googlers looking at this, it is issue 157479752

**Comment by Elijer** [comment]
That's great! I appreciate the quick response. Looking forward to testing
the demo!

**Comment by 20chix** [comment]
> 479
Wow, is that 157 millions issues within firebase? 

Sorry that's out of the scope of this issue

**Comment by jhuleatt** [comment]
We've modernized this sample and redeployed to a new URL. It is now https://cloud-functions-stripe-sample.web.app

**Comment by Elijer** [comment]
Wooh! Looks great. Thank you.
