### ISSUE TITLE
Thumbnail generation has wrong orientation

### ISSUE THREAD

**Issue by alxvallejo** [firebase/functions-samples#726]
I'm not sure why the example isn't using sharp() since so many other example recommend using the library for image manipulation, but no image orientation fixes (rotate, crop) are being used in the sample. Can anyone explain why?

https://github.com/firebase/functions-samples/tree/master/generate-thumbnail

**Comment by jhuleatt** [comment]
Hi @alxvallejo, that's meant to be a really minimal sample that uses the image manipulation tool built in to Cloud Functions for Firebase (ImageMagick).

We have a sharp sample here: https://github.com/firebase/functions-samples/tree/master/image-sharp

If you'd like to see a more productionized version that does account for rotation, you can take a look at the source for the `storage-resize-images` extension: https://github.com/firebase/extensions/blob/d79a44522d1a889ce33ae5902eb6c1eeb28f87f0/storage-resize-images/functions/src/index.ts#L155-L158

**Comment by alxvallejo** [comment]
The sharp sample is outdated. The max() method has been deprecated.

What would really be helpful is to combine both simple approaches:
- Use sharp for thumbnail generation
- Use admin SDK to save the new path to the RTDB

Right now, i'm unsure of how to do that given the example, since sharp seems to rely on streams with a promise that doesn't return the images for saving.

**Comment by billymahmood** [comment]
Hi @alxvallejo 

Did you find a solution to this issue?

Thank you

**Comment by alxvallejo** [comment]
@billymahmood Yes, actually made a PR, but haven't had time to format it -> https://github.com/firebase/functions-samples/pull/730
