### ISSUE TITLE
Updating cloud functions settings on cloud console asking for source code deployment everytime!!!

### ISSUE THREAD

**Issue by manwithsteelnerves** [firebase/functions-samples#750]
### Expected behavior
Once after changing any settings for cloud functions with edit option, it should deploy with the changes automatically on clicking save without the need for re-deploying the source again.

### Current behavior
Its asking to redeploy the source even If I add an environment variable which is pretty bad. It used to be fine earlier but now it is not by passing the source upload screen.
![Screenshot 2020-07-28 at 11 21 10 AM](https://user-images.githubusercontent.com/5437614/88624412-8ca4cf00-d0c4-11ea-8c3e-c81744db035a.png)

**Comment by jhuleatt** [comment]
@manwithsteelnerves can you please file this feature request with [support](https://firebase.google.com/support#firebase-troubleshooter:~:text=Pick%20a%20category)?

This functions-samples repository is specifically for sample code. Filing your request with support will ensure the engineering team hears your request.
