### ISSUE TITLE
Firebase function suggestions

### ISSUE THREAD

**Issue by chinu999** [firebase/functions-samples#754]
Actually I am trying to build a app I know how to get posts from followers but I didn't get any help or ideas From anywhere. how to get suggested posts for new user if he is not following anyone.

**Comment by jhuleatt** [comment]
Hi @chinu999, check out the [Cloud Functions for Firebase](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#0) codelab to learn more about Cloud Functions for Firebase. To get advice, try chatting in the [Firebase Slack](https://firebase.community/).
