### ISSUE TITLE
'Function killed. Error: function crashed out of request scope' when resizing

### ISSUE THREAD

**Issue by ValentinTaleb** [firebase/functions-samples#77]
I'd like to resize an image stored in Firebase Storage with Firebase Functions.

Based on this example : https://github.com/firebase/functions-samples/blob/master/quickstarts/thumbnails/functions/index.js I tried to write a function triggered by a Database event.

Here is the most interesting part of the code :

```
...
    const fileName = originalPictureUrl.split('/').pop();
    const bucket = gcs.bucket('...');
    const tempFilePath = `/tmp/${fileName}`;

    return bucket
        .file(originalPictureUrl)
        .download({
            destination: tempFilePath
        })
        .then(() => {
            // Generate a thumbnail using ImageMagick.
            return spawn('convert', [tempFilePath, '-thumbnail', '200x200>', tempFilePath])
                .then(() => {

                    // We add a 'thumb_' prefix to thumbnails file name. That's where we'll upload the thumbnail.
                    const thumbFilePath = filePath.replace(/(\/)?([^\/]*)$/, `$1thumb_$2`);

                    // Uploading the thumbnail.
                    return bucket.upload(tempFilePath, {
                        destination: thumbFilePath
                    });
                });
        });
...
```
Everything looks fine to me. However I get this error :

`Function killed. Error: function crashed out of request scope`

Does somebody know what could be the error?

**Comment by varungupta85** [comment]
@ValentinTaleb Were you able to figure what does `Function killed. Error: function crashed out of request scope` mean? I am observing this error in one of my cloud functions. Thanks!

**Comment by ValentinTaleb** [comment]
Hi @varungupta85,
The answer from nicolasgarnier there : https://github.com/firebase/functions-samples/issues/78 should interest you :)

**Comment by varungupta85** [comment]
Thanks for the response @ValentinTaleb
