### ISSUE TITLE
bug in audio conversion example

### ISSUE THREAD

**Issue by pietrop** [firebase/functions-samples#777]
Bug in audio conversion example, when running it as a cloud function
```
Error: Error occurred while parsing your function triggers.

TypeError: require(...) is not a function
```

This [firebase/functions-samples/ffmpeg-convert-audio/functions/index.js#L19
](https://github.com/firebase/functions-samples/blob/master/ffmpeg-convert-audio/functions/index.js#L19) should be change to

```diff
- const gcs = require('@google-cloud/storage')();
+ const { Storage } = require('@google-cloud/storage');
+ const gcs = Storage;
```

more details here https://github.com/googleapis/nodejs-storage/issues/456

**Comment by jhuleatt** [comment]
Thanks @pietrop! Fixed in https://github.com/firebase/functions-samples/pull/795
