### ISSUE TITLE
Error: Invalid login: 534-5.7.14

### ISSUE THREAD

**Issue by dave-k** [firebase/functions-samples#780]
I have already enabled both 
// 1. https://www.google.com/settings/security/lesssecureapps
// 2. https://accounts.google.com/DisplayUnlockCaptcha
and everything works just fine but after a few hours I start getting an error: "Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvz" then I have to enable 
 https://accounts.google.com/DisplayUnlockCaptcha again. Is there any way to prevent doing this manually every few hours.

_Originally posted by @carlosdelamora in https://github.com/firebase/functions-samples/issue_comments/412968986_

**Comment by dave-k** [comment]
@carlosdelamora 
Did you resolve the issue with enabling [https://accounts.google.com/DisplayUnlockCaptcha](url) again?

I have also enabled both 1. & 2. 
After trying later, there is the error: "Error: Invalid login: 534-5.7.14" 
After Enabling 2. again, gmail login is successful.

It seems that Enabling 2. again is required after firebase deploy 
````
firebase deploy --only functions
````

**Comment by dosstx** [comment]
Same here...

**Comment by jhuleatt** [comment]
For any higher usage of the `email-confirmation` sample (I assume that's the sample referenced here), you'll need to use an email provider that supports higher volume sending. To see a sample that uses that, take a look at https://github.com/firebase/functions-samples/tree/5614dd71cddbe27512b41d662cc51d8d25f2a562/survey-app-update#functions-code
