### ISSUE TITLE
Demonstrate addition of payment methods in the Stripe example

### ISSUE THREAD

**Issue by iThinkersTeam** [firebase/functions-samples#79]
Hello,

Could I save cards for customer through cloud function?

Thanks

**Comment by jamesdaniels** [comment]
We have a pull request in progress #59 I'll be looking at it again today.

**Comment by ryanmargheriti** [comment]
@jamesdaniels Looks like the PR was closed and not merged. What does that mean for this issue?

**Comment by ryanmargheriti** [comment]
That commit doesn't address this issue at all. For anybody finding this wanting an actual answer, I created an HTTP endpoint function that does what OP is requesting: https://gist.github.com/ryanmargheriti/5c9d43e920e2fcc8c197d76c436274e9

Feedback welcome.

**Comment by fxo140130** [comment]
@ryanmargheriti , so this function is incorrect ?

exports.addPaymentSource = functions.database 
![image](https://user-images.githubusercontent.com/25092371/39502265-e03082c4-4d84-11e8-9a7f-f6cdac27ab1c.png)

i tried everything to save my credit to user account but no success.
