### ISSUE TITLE
I think there should be code deleting 'payments' subcollection in 'cleanupUser' function

### ISSUE THREAD

**Issue by HYJ29** [firebase/functions-samples#792]
Thank you for these really nice samples. 
I just found a tiny omission in the code 

I think there should be code deleting 'payments' subcollection in 'cleanupUser' function 
just like this 
```
 const paymentsSnapshot = await dbRef.doc(user.uid).collection('payments').get()
    paymentsSnapshot.forEach((snap)=> snap.ref.delete())
```

Please let me know if there was an intention on it. 

https://github.com/firebase/functions-samples/blob/561d73b0357f4b03f4952242ee9513d57708f068/stripe/functions/index.js#L144-L148

**Comment by jhuleatt** [comment]
@HYJ29 great question! One thought might be that, for record keeping, a seller would want to preserve a history of payments even after a customer deletes their account. However, given that the comment says:

> Delete the customers **payments** & payment methods in firestore.

This seems like it was unintentionally left out. Would you be interesting in opening a PR to update this?

**Comment by HYJ29** [comment]
@jhuleatt Oh yes, I understood. So just fixing the comment would fix this confusion.  It would be my pleasure to have a contribution to these samples even it is so tiny 😄 
I'll check out the contribution guide and do it soon. Thank you.

**Comment by HYJ29** [comment]
I just changed the code to delete both! Not fixing the comment.
