### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by comerc** [firebase/functions-samples#817]
![Снимок экрана от 2021-01-08 21-34-27](https://user-images.githubusercontent.com/1025241/104051665-88dfb180-51f9-11eb-8754-167ca055437e.png)

https://console.firebase.google.com/project/MY_PROJECT/functions/logs

**Comment by samtstern** [comment]
@comerc if you're reporting a bug in the Firebase console please do it here:
https://firebase.google.com/support/troubleshooter/report/bugs

**Comment by comerc** [comment]
😂
