### ISSUE TITLE
Cloud Storage example should demonstrate writing a URL back to the database

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/functions-samples#82]
We're getting asked this a bunch.

**Comment by katowulf** [comment]
For a short term workaround, I think this is [in the web codelab](https://codelabs.developers.google.com/codelabs/firebase-web/#8). Not much brainwork to get from there to Functions, but valid that we don't have a sample showing this.

**Comment by markgoho** [comment]
I'm guessing this is waiting for Storage functionality to be added to the Admin SDK.

We need this to solve the really common issue of doing some processing on an image with a Cloud Function and then writing its downloadURL back to the database to be accessed later.

**Comment by jahglow** [comment]
Any progress on this? Because it's a real pain getting that URL! Actually I haven't figured out how to do that  in a cloud function, any hints on that?

**Comment by jenperson** [comment]
The [generateThumbnail sample](https://github.com/firebase/functions-samples/tree/master/generate-thumbnail) now shows you how to get the Signed URL, as demonstrated in[ this video.](https://github.com/firebase/functions-samples/tree/master/generate-thumbnail)

**Comment by ihojmanb** [comment]
@jenperson Hi Jen, I wonder why your video is not in the firecasts playlist anymore but [here](https://www.youtube.com/watch?v=MiRNqj5z0yA), I found it quite useful to not be founded in its proper place.

**Comment by dody87** [comment]
Why I signed a URL to expires in 2100, but after one week it doesn't work?

**Comment by ihojmanb** [comment]
> Why I signed a URL to expires in 2100, but after one week it doesn't work?

You have to provide a Service Account Key to get the expired date to work. You can have more  details [here](https://stackoverflow.com/a/55092974/6066954)
