### ISSUE TITLE
[BUG] in sample: 

### ISSUE THREAD

**Issue by HiddenBehindTheKeyBoard** [firebase/functions-samples#820]
The FIREBASE FUNCTIONS API - https://us-central1-{project}.cloudfunctions.net/

Not have permission for used in FIREBASE HOSTING =|

**Comment by samtstern** [comment]
@HiddenBehindTheKeyBoard please use the issue template when filing an issue. There's nothing here to explain what's wrong with this sample, what you've tried, or what you expected to happen.
