### ISSUE TITLE
[BUG] in crashlytics/*: Crashlytics functions are deprecated and need to be removed

### ISSUE THREAD

**Issue by mbleigh** [firebase/functions-samples#833]
Crashlytics functions are no longer available, we should remove the samples that reference them.

**Comment by samtstern** [comment]
Calling @jhuleatt the Great Deleter of Samples

**Comment by yhkaplan** [comment]
@mbleigh 

> Crashlytics functions are no longer available

My company relied on this trigger. Was this announced somewhere in advance? Also, will there be any new ways of getting alerts, or is it limited to the current options?
