### ISSUE TITLE
bigquery

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#86]
Hi @nicolasgarnier 

I am having the following error while deploying the Bigquery. Please note that the npm is already install and the dependancy is added in my package jsom. Thanks

![image](https://cloud.githubusercontent.com/assets/25092371/24313592/797fcb46-10ab-11e7-853c-93434b3a9511.png)

**Comment by inlined** [comment]
It's not enough to just install npm, you also need to run the command `npm install`. You need to install the dependency locally because the Firebase CLI actually runs your code to know what to deploy.

**Comment by fxo140130** [comment]
@inlined , 


I deployed firebase stripe and payment using the CLI and install the npm and all dependencies. I include the bigquerie dependency in my JSON. But I am having the same error. Please help.

**Comment by inlined** [comment]
So you're saying that `functions/node_modules/@google-cloud/bigquery` exists in that project directory?

**Comment by fxo140130** [comment]
@inlined 

Exactly, 

![image](https://cloud.githubusercontent.com/assets/25092371/24521167/d54e4bce-1550-11e7-875e-d55861d56fa0.png)

I add every dependencies, add the big query to my node.js. But, I still received the error above.

**Comment by inlined** [comment]
I'm trying to see if it's on your disk, not package.json. That screen shot shows that your code depends on `@google-cloud/bigquery` but does not show whether that dependency is installed.

**Comment by nicolasgarnier** [comment]
@fxo140130 did you install the NPM dependencies locally?
i.e. you need to do this: `cd functions; npm install; cd -`
