### ISSUE TITLE
Infinit loop with the moderate-images example

### ISSUE THREAD

**Issue by iDams** [firebase/functions-samples#87]
Hi,

I've copy/paste the moderate-images example and when I'm uploading an image in Firebase Storage, it executes the cloud function like there was a loop. To stop it, I have to comment the code and deploy again.

Here is the copy/pasted code. The only difference is that I have removed to `google-cloud-vision` part and blurred the image every time.

```
// functions/index.js

'use strict';

const functions = require('firebase-functions');
const mkdirp = require('mkdirp-promise');
const gcs = require('@google-cloud/storage')();
const exec = require('child-process-promise').exec;
const LOCAL_TMP_FOLDER = '/tmp/';

/**
 * When an image is uploaded we check if it is flagged as Adult or Violence by the Cloud Vision
 * API and if it is we blur it using ImageMagick.
 */
exports.blurOffensiveImages = functions.storage.object().onChange(event => {
  const object = event.data;
  const file = gcs.bucket(object.bucket).file(object.name);

  // Exit if this is a move or deletion event.
  if (object.resourceState === 'not_exists') {
    return console.log('This is a deletion event.');
  }

  // Check the image content using the Cloud Vision API.
    return blurImage(object.name, object.bucket, object.metadata);

});

/**
 * Blurs the given image located in the given bucket using ImageMagick.
 */
function blurImage(filePath, bucketName, metadata) {
  const filePathSplit = filePath.split('/');
  filePathSplit.pop();
  const fileDir = filePathSplit.join('/');
  const tempLocalDir = `${LOCAL_TMP_FOLDER}${fileDir}`;
  const tempLocalFile = `${LOCAL_TMP_FOLDER}${filePath}`;
  const bucket = gcs.bucket(bucketName);

  // Create the temp directory where the storage file will be downloaded.
  return mkdirp(tempLocalDir).then(() => {
    console.log('Temporary directory has been created', tempLocalDir);
    // Download file from bucket.
    return bucket.file(filePath).download({
      destination: tempLocalFile
    });
  }).then(() => {
    console.log('The file has been downloaded to', tempLocalFile);
    // Blur the image using ImageMagick.
    return exec(`convert ${tempLocalFile} -channel RGBA -blur 0x8 ${tempLocalFile}`);
  }).then(() => {
    console.log('Blurred image created at', tempLocalFile);
    // Uploading the Blurred image.
    return bucket.upload(tempLocalFile, {
      destination: filePath,
      metadata: {metadata: metadata} // Keeping custom metadata.
    });
  }).then(() => {
    console.log('Blurred image uploaded to Storage at', filePath);
  });
}
```

And here is a screenshot of my dashboard when I only uploaded one image called "oss2.png"
<img width="962" alt="capture d ecran 2017-03-25 a 16 07 11" src="https://cloud.githubusercontent.com/assets/1591702/24323453/aedf86d0-1175-11e7-9f90-8bc19b83b375.png">

If you have any input on it, that would be great!

Thanks!

**Comment by iDams** [comment]
Hi,

After digging a little bit, it seems that `functions.storage.object().onChange(event` is causing the infinite loop.
Since it is listening to all changes of the storage and our function is uploading a new image at the end. It probably triggers an onchange event and here we go again?

**Comment by nicolasgarnier** [comment]
The trick is nice indeed :) (good way to use metadatas)

But normally the function does not run in a loop. The issue is that in your code it seems you have removed the Cloud Vision API call (this is what stops the loop).

In the original sample we first check if the image is offensive and, if it is, we blur it. The function gets called again on the new blurred image but - because it's been blurred - the image is not detected as being offensive on the second check and this ends the *loop*.

By the way be careful when using metadata because the users can set them from the client (when you upload the image) and they could use that to bypass the image check on the function. You can avoid that by using some special security rules to forbid setting the metadata from the client though.

**Comment by iDams** [comment]
Thanks for your tips! I was not aware of metadata risk :)
