### ISSUE TITLE
[DOCS] for sample: email-users

### ISSUE THREAD

**Issue by zair-t** [firebase/functions-samples#874]
Sample: https://github.com/firebase/functions-samples/tree/master/quickstarts/email-users
Hello! I have a problem, when I write a firebase deploy, I get an error: "Parsing error: Unexpected token function". How can I fix it?

**Comment by samtstern** [comment]
@zair-t that's not enough information to help you, can you provide more? If I had to guess your local version of `node` is too low. Can you check `node --version` and make sure it's 10 or higher?
