### ISSUE TITLE
When multiple RTDBs then background cloud functions triggers only for default database.

### ISSUE THREAD

**Issue by SanthoshEnricher** [firebase/functions-samples#881]
### Which sample has a bug?

When multiple RTDB background cloud functions triggers only for default database.

### Expected behavior

When have a single project for staging and production instances with different realtime databases.
Need to have a mechanism to trigger background functions for both databases.

When have a single project for staging and production instances with different realtime databases.
It is triggering only for default database.

**Comment by jhuleatt** [comment]
@SanthoshEnricher you'll need to create a trigger for each instance. Here are the docs for that: https://firebase.google.com/docs/functions/database-events#specify_the_instance_and_path

**Comment by SanthoshEnricher** [comment]
@jhuleatt Thank you.
