### ISSUE TITLE
fulltext-search - creating database ref with invalid path

### ISSUE THREAD

**Issue by nelsongonzalez** [firebase/functions-samples#90]
The function `exports.indexentry` is creating a database reference:
```javascript
return index.saveObject(firebaseObject).then(
      () => admin.database().ref(event.timestamp));
```
But `event.timestamp` is an RFC 3339 string (documentation [here](https://firebase.google.com/docs/reference/functions/functions.Event#timestamp)), then, the function is throwing an error:
`Error: Firebase.child failed: First argument was an invalid path: "2017-03-27T01:00:17.512Z". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"`

**Comment by nelsongonzalez** [comment]
A possible solution could be using `Date.parse(event.timestamp)`

```javascript
return index.saveObject(firebaseObject).then(
      () => admin.database().ref(Date.parse(event.timestamp)));
```

**Comment by inlined** [comment]
Is this a bug report against a particular sample?

**Comment by nelsongonzalez** [comment]
Hi,

It is a nice solution because the timestamp is not part of the path, but now there is another problem, the new code is throwing: `TypeError: Date.parse(...).getTime is not a function`

This is because `Date.parse(event.timestamp)` returns a `long type`, and it does not have a function called `getTime()`

```javascript
return index.saveObject(firebaseObject).then(
      () => event.data.adminRef.child('last_index_timestamp').set(
          Date.parse(event.timestamp).getTime())); // the problem is here
```

Maybe, we could use `event.timestamp` or `Date.parse(event.timestamp)` depending on the format we want to use:
```javascript
// this option works
return index.saveObject(firebaseObject).then(
      () => event.data.adminRef.child('last_index_timestamp').set(
          event.timestamp)); //

// or this option also works
return index.saveObject(firebaseObject).then(
      () => event.data.adminRef.child('last_index_timestamp').set(
          Date.parse(event.timestamp))); //
```

Thanks.

**Comment by nicolasgarnier** [comment]
Thanks for the report. Just fixed it!
