### ISSUE TITLE
Stripe with application_fee

### ISSUE THREAD

**Issue by iThinkersTeam** [firebase/functions-samples#92]
Hello,

Could I pass "application_fee" to charge functions?

Thanks

**Comment by inlined** [comment]
Could you be more specific in what you're asking? I suspect the answer is "yes" but I'd need to know more about what you're requesting. If you want to add a static "application fee" to any stripe charge, then I'd recommend [using Runtime Config within Cloud Functions for Firebase](https://firebase.google.com/docs/functions/config-env). Each project would be able to have its own const for the application_fee that you'd access with `functions.config().stripe_config.application_fee` and you can add as a line item.

**Comment by jamesdaniels** [comment]
You can [pass any attribute to the charge object](https://github.com/firebase/functions-samples/blob/070964e1ecbd66b146213f3e163e8b1da7cf9f19/stripe/functions/index.js#L41) that the [Stripe Node.js library would expect](https://stripe.com/docs/api/node#charge_object) and yes, that includes the [application_fee](https://stripe.com/docs/api/node#charge_object-application_fee).
