### ISSUE TITLE
Stripe deployment issue. 

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#97]
@jamesdaniels 

I have the following error while creating account while using your index.js

From the log :+1: 

![image](https://cloud.githubusercontent.com/assets/25092371/24487388/c947afc2-14d4-11e7-9a21-c64600feeb38.png)

![image](https://cloud.githubusercontent.com/assets/25092371/24487408/e5675cb6-14d4-11e7-8a99-fdbb407b6409.png)

**Comment by jamesdaniels** [comment]
the first error looks to be a bug with your code
the second was a typo, fixing now

**Comment by jamesdaniels** [comment]
actually maybe they're the same issue, let me know if that commit fixed

**Comment by fxo140130** [comment]
@jamesdaniels 

Thanks Sir, 

I will be around to see the stripe connect sample. Thanks
